src/MSAL.Common/CommonAssemblyInfo.cs
src/MSAL.PCL.Android/AuthenticationContinuationHelper.cs
src/MSAL.PCL.Android/WebUI.cs
src/MSAL.PCL.Desktop/CryptographyHelper.cs
src/MSAL.PCL.Desktop/Properties/AssemblyInfo.cs
src/MSAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs
src/MSAL.PCL.WinRT/Properties/AssemblyInfo.cs
src/MSAL.PCL/Properties/AssemblyInfo.cs

Port bug fixes and features from ADAL v3 since MSAL preview release (https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/131)
- AzureAD/azure-activedirectory-library-for-dotnet#451
- AzureAD/azure-activedirectory-library-for-dotnet#459
- Add semantic versioning for the library
- OnResume throws NullPointerException when no ADAL or broker activity is pending
- Ignoring Javascript:// in desktop webview as a non-https url
- Ignore webview error if dialogresult = OK in desktop webview

Port relevant fixes from ADAL v3.

---

src/MSAL.Common/ClientAssertionCertificate.cs

use GetCertHash() instead of Thumbprint per #124 as it would cause the server to fail the request

use GetCertHash() instead of Thumbprint

---

src/MSAL.PCL/Internal/Cache/BaseTokenCacheItem.cs
src/MSAL.PCL/Internal/OAuth2/TokenResponse.cs
src/MSAL.PCL/Internal/Requests/OnBehalfOfRequest.cs
src/MSAL.PCL/TokenCache.cs

remove userassertionHash from TokenCacheItem as we don't need to track this information anymore. Have acquireTokenOnBehalfOf() do network call and skip cache lookup, just like AcquireToken calls. Developer can always call acquire token silent to pull from cache.  #146

remove userassertionHash from TokenCacheItem

---

samples/TestApp.PCL/TokenBroker.cs
src/MSAL.PCL/ClientApplicationBase.cs
src/MSAL.PCL/ConfidentialClientApplication.cs
src/MSAL.PCL/Internal/Requests/AuthenticationRequestParameters.cs
src/MSAL.PCL/Internal/Requests/InteractiveRequest.cs
src/MSAL.PCL/Internal/Requests/SilentRequest.cs
src/MSAL.PCL/PublicClientApplication.cs
tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
tests/Test.MSAL.NET.Unit/RequestsTests/SilentRequestTests.cs

This PR contains the updates for 
(#119)  change the order of first 2 parameters here into code, scope. Same applies to other overloading methods.
(#117) Coding Style: method overload parameter ordering convention for constructors in public and confidential client class.
(#115)  Remove PlatformParameters from ClientApplicationBase and move it to public client class.

Update to the API surface

---

src/MSAL.PCL.WinRT/TokenCachePlugin.cs
src/MSAL.PCL/Internal/JsonHelper.cs

(#152) Update WinRT cache storage to slice cache data in chunks because the name of each setting can be 255 characters in length at most. Each setting can be up to 8K bytes in size and each composite setting can be up to 64K bytes in size.

Update WinRT cache storage to slice cache data in chunks 

---

GitVersion.yml
appveyor.yml
build.ps1
src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj

This PR introduces GitVersion to stamp the version number on the AssemblyInfo files and the NuGet packages during build.
Currently set to do -preview.* builds with SemVer 2.0, full configuration settings are here:
http://gitversion.readthedocs.io/en/latest/

auto generate version

---

src/Microsoft.Identity.Client/Features/UIBehavior.cs
src/Microsoft.Identity.Client/UIBehavior.cs

When used on static fields, readonly should come after static (i.e. static readonly not readonly static).
- https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Fixing violations of the C# Coding Style Guide.

---

src/Microsoft.Identity.Client/Features/ConfidentialClient/ClientAssertionCertificate.cs
src/Microsoft.Identity.Client/Features/ConfidentialClient/ClientCredential.cs
src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/Microsoft.Identity.Client/Platforms/net45/CustomWebBrowser.cs
src/Microsoft.Identity.Client/Platforms/net45/SilentWindowsFormsAuthenticationDialog.cs
src/Microsoft.Identity.Client/Platforms/net45/WinFormWebAuthenticationDialog.cs
src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
src/Microsoft.Identity.Client/TokenCache.cs

> We avoid `this.` unless absolutely necessary.
- https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md

Cleanup coding style: Removed unnecessary "this." qualifiers.

---

appveyor.yml
build/build.ps1

Relates to #180 
Uses the workaround from https://github.com/appveyor/ci/issues/1411#issuecomment-287678065 to install the Android SDK

Added appveyor workaround to install Android SDK 24

---

src/Microsoft.Identity.Client/ClientApplicationBase.cs
src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
src/Microsoft.Identity.Client/Features/ConfidentialClient/IConfidentialClientApplication.cs
src/Microsoft.Identity.Client/IClientApplicationBase.cs
src/Microsoft.Identity.Client/IPublicClientApplication.cs
src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
src/Microsoft.Identity.Client/Internal/Requests/BaseRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
src/Microsoft.Identity.Client/Platforms/Android/AuthenticationActivity.cs
src/Microsoft.Identity.Client/PublicClientApplication.cs
tests/Test.MSAL.NET.Unit/RequestsTests/SilentRequestTests.cs

Related to the earlier commit to remove arrays from interface outputs.
If there are usage patterns where the consumer will make a call to MSAL and then pass the _AuthenticationResult.Scope_ to another MSAL method then this change will mean that user won't have to convert the returned scopes from an enumerable to an array.
Also, it's good practice for APIs to accept the most general-purpose type that makes sense; unless a method has a specific reason to require a string array as input then it's better to use a string enumerable as that's more flexible - the user could pass an array, a list, an enumerable etc

Removed arrays from interface inputs

---

src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs

fix to check for javascript as the scheme in net45 and not absolute URI. Also made the fix to do OrginalIgnoreCase check. This fix was validated with Desktop dev app. #284

fix to check for javascript as the scheme in net45

---

AutomationApp/TokenHandler.cs
dev apps/DesktopTestApp/MainForm.cs
dev apps/XForms/XForms/AcquirePage.xaml.cs
samples/XForms/XForms.UWP/BundleArtifacts/x86.txt
src/Microsoft.Identity.Client/AuthenticationResult.cs
src/Microsoft.Identity.Client/ClientApplicationBase.cs
src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
src/Microsoft.Identity.Client/IAuthenticationResult.cs
src/Microsoft.Identity.Client/IClientApplicationBase.cs
src/Microsoft.Identity.Client/IPublicClientApplication.cs
src/Microsoft.Identity.Client/IUser.cs
src/Microsoft.Identity.Client/Internal/Cache/AccessTokenCacheItem.cs
src/Microsoft.Identity.Client/Internal/Cache/RefreshTokenCacheItem.cs
src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/Microsoft.Identity.Client/PublicClientApplication.cs
src/Microsoft.Identity.Client/TokenCache.cs
src/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
src/Microsoft.Identity.Client/User.cs
tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/UserTests.cs

The public API exposes the _User_ class which in turn exposes properties a developer might reasonably want to use in their app such as _Name_ and _DisplayableId_ - which in turn means they will want to be able to unit test their app.

Modified public API to allow unit testing of User class

---

dev apps/XForms/PATCH.Xamarin.Common.targets
dev apps/XForms/XForms.Android/XForms.Android.csproj
dev apps/XForms/XForms.iOS/XForms.iOS.csproj

If a project references multiple targets with the same name then the last one to be imported wins.
This commit contains a workaround for the Xamarin targets bug by redefining the buggy target for the two projects that use it. Implementing the workaround this way avoids the need to every developer to manually patch up their machine, and it also means the fix will be applied in appveyor builds.

Added workaround for Xamarin targets bug

---

src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
src/Microsoft.Identity.Client/Platforms/Android/WebUI.cs
tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs

redirectUri - use OriginalString instead of AbsoluteUri https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/160

redirectUri - use OriginalString instead of AbsoluteUri

---

src/Microsoft.Identity.Client/ClientApplicationBase.cs
src/Microsoft.Identity.Client/Internal/Instance/Authority.cs
src/Microsoft.Identity.Client/Internal/PlatformPlugin.cs
src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/Microsoft.Identity.Client/Internal/Requests/BaseRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/SilentRequest.cs
src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
src/Microsoft.Identity.Client/TokenCache.cs
tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
tests/Test.MSAL.NET.Unit/TestConstants.cs

Update cache lookup per #127. Also includes fix for #301 
Cache lookup works as follows
1) filter by client_id and user.
1.1) if nothing found, fail.
1.2) if no authority passed,
1.2.1) filter by scope.
1.2.1.1) if 1 entry found, save the authority (for later use).             
1.2.1.1.1) if AT expired, return null (use authority for RT redemption)
1.2.1.1.2) if AT not expired, then return.
1.2.1.2) if more than 1 entry found, FAIL.
1.2.1.3) if NO entry found, check if all cache entries from 1) were from single authority
1.2.1.3.1) if NO, then FAIL.
1.2.1.3.2) if YES, then save it for Refresh token redemption.
1.2) if authority is passed,
1.2.1) filter by scope + authority.
1.2.1.1) if 1 entry found, return it.             
1.2.1.1.1) if AT expired, return null
1.2.1.1.2) if AT not …

Update cache lookup per #127. Also includes fix for #301

---

src/Microsoft.Identity.Client/Internal/Instance/Authority.cs
src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
src/Microsoft.Identity.Client/Internal/OAuth2/OAuth2Client.cs
src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/InstanceTests/AadAuthorityTests.cs
tests/Test.MSAL.NET.Unit/Resources/OpenidConfiguration-B2C.json
tests/Test.MSAL.NET.Unit/Resources/OpenidConfiguration-MissingFields.json
tests/Test.MSAL.NET.Unit/Resources/OpenidConfiguration.json

Fix for dropped QPs from endpoints, per #238. B2C openid configuration endpoint returns auth urls with QPs and MSAL was dropping those QPs when constructing network requests.

Fix for dropped QPs from endpoints

---

tests/Test.MSAL.NET.Unit/TelemetryTests.cs

Our Jenkins build policy does not like foo bar.

Removing foo and bar in source code

---

src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
tests/Test.MSAL.NET.Unit/CacheTests/TokenCacheTests.cs

Token Cache FindAccessToken should be Scope case insensitiv https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/349

Find Access Token in cache case insensibly

---

src/Microsoft.Identity.Client/DefaultEvent.cs

It was "MSAL.Desktop". Now this is the DefaultEvent printed on console, after this PR change:
msal.event_name: msal.default_event
msal.start_time: 1493230041483
msal.elapsed_time: -1
msal.client_id: client_id
**msal.sdk_platform: msal.desktop**
msal.sdk_version: 1.1.0.0
Also note that, in future the telemetry operators will need to "translate" the original SDK version "MSAL.Desktop" into lowercase before he/she constructs the query.

Force sdk_platform in telemetry to be in lowercase

---

build/MSAL.CodeCoverage.runsettings

Same change that was made recently to ADAL.Net: including the test apps and test code in the code coverage skews the numbers.
Once this changed is merged I'll update the VSTS build definition to use the settings file.

Added run settings file to limit code coverage to product assemblies

---

src/Microsoft.Identity.Client/Internal/Telemetry/ApiEvent.cs
src/Microsoft.Identity.Client/Internal/Telemetry/CacheEvent.cs
src/Microsoft.Identity.Client/Internal/Telemetry/Event.cs
src/Microsoft.Identity.Client/Internal/Telemetry/HttpEvent.cs
src/Microsoft.Identity.Client/Internal/Telemetry/UiEvent.cs
src/Microsoft.Identity.Client/Telemetry.cs
tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
tests/Test.MSAL.NET.Unit/TelemetryTests.cs

Those fields used to contain a "Const-" prefix, in order to differentiate
their property name and their const string key names in the dictionary.
"-Key" suffix is now chosen because it has been a naming principle for years.

Change all ConstName to NameKey

---

src/Microsoft.Identity.Client/Features/PublicClient/PublicClientApplication.cs
src/Microsoft.Identity.Client/Internal/MsalError.cs
src/Microsoft.Identity.Client/Internal/PlatformInformationBase.cs
src/Microsoft.Identity.Client/Platforms/Android/PlatformInformation.cs
src/Microsoft.Identity.Client/Platforms/iOS/PlatformInformation.cs
src/Microsoft.Identity.Client/PublicClientApplication.cs

Add support for default redirect uri in iOS and Android https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/391

uri comparison fix, adding redirect_uri_validation_failed msal error

---

src/Microsoft.Identity.Client/Internal/Telemetry/Event.cs
src/Microsoft.Identity.Client/Telemetry.cs
tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
tests/Test.MSAL.NET.Unit/TelemetryTests.cs

This PR contains unit tests for the Telemetry internal implementation in situation of asymmetric calls to StartEvent(...) and StopEvent(...). The PR also contains integration tests (from the Telemetry perspective) to see Telemetry in action for API scenarios 726 & 727. Previously we already have covered API scenarios 170, 174, 30, 31. Together with the implementation decision that all the API events share the same one code path, all the test cases above give us a good coverage of Telemetry functionality.

Adding more test cases for Telemetry

---

src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/Microsoft.Identity.Client/Internal/Telemetry/ApiEvent.cs
tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs

Use `MsalException.ErrorCode` to populate the new `ApiEvent.ApiErrorCode`.

Add api_error_code into ApiEvent

---

appveyor.yml
src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
tests/Test.MSAL.NET.Unit/Test.MSAL.NET.Unit.csproj
tests/dev apps/WebTestApp/WebApi/WebApi.csproj
tests/dev apps/WebTestApp/WebApp/WebApp.csproj
tests/dev apps/XForms/XForms.Android/Resources/Resource.Designer.cs
tests/dev apps/XForms/XForms.Android/XForms.Android.csproj
tests/dev apps/XForms/XForms.UWP/project.json
tests/dev apps/XForms/XForms.iOS/XForms.iOS.csproj
tests/dev apps/XForms/XForms/XForms.csproj

Bug(#443) The current version (25.3.1) of Xamarin android support libraries is not being used by MSAL so I updated the NuGet packages within MSAL to use these new libraries.

Updated Xamarin Forms Android support libraries to 25.3.1.

---

src/Microsoft.Identity.Client/Platforms/net45/PlatformInformation.cs

Without this change, the code attempts to P/Invoke Win32 APIs on Unix causing a stackoverflow as the logging facility is triggered and in turn, calls the platform identification code to report the platform and so on.

Make this work on Unix with the Xamarin.Mac Full profile and Mono

---

build/inject-signed-binaries.cmd

Changed "mv" command to "copy" and removed a copy step at the beginning - this is now done as a build step in VSTS.
Thanks to @jennyf19 for spotting this problem.

Fixed binary injection script.

---

src/Microsoft.Identity.Client/MsalClientException.cs
src/Microsoft.Identity.Client/Platforms/Android/AuthenticationActivity.cs
tests/dev apps/XForms/XForms.Android/MainActivity.cs

- add try/catch block for StartActivity() to catch when Chrome packag…e is installed on device but Chrome is disabled
- add MsalClientException for Chrome disabled
- address Forms.Context is obsolete warning in XForms.Droid app
#567

Address issues w/Chrome disabled on android device: 

---

README.md

Seems that the markdown files are case sensitive. Meaning Contributing.md was producing a 404 link not found.
Changed typo to contributing.md

Contributing link fault

---

contributing.md

Seems MS has updated the CLA signing site for contributions.
The original URL is no longer active and no redirect is issued...

CLA site updated

---

LibsAndSamples.sln
LibsNoSamples.sln

this doesn't impact the release, but these files were not referenced properly in the solution directory layout so they weren't openable within VS.

fix path to msal common props in sln files

---

src/Microsoft.Identity.Client/Platforms/Android/BrowserTabActivity.cs

BrowserTabActivity is used w/system browser so we know were to return the redirect. This also has to be declared in the android manifest.
With the changes to MSAL restructuring, the namespace has changed to `Microsoft.Identity.Client.Platforms.Android.BrowserTabActivity`
In order to not make this a breaking change, changing the namespace back to Microsoft.identity.client
`<activity android:name="microsoft.identity.client.BrowserTabActivity">`
PS. I'll update the wiki was well. I don't see this documented anywhere 
cc: @jmprieur

browsertab fix

---

src/MSAL.Frameworks.props
src/Microsoft.Identity.Client/Features/ConfidentialClient/JsonWebToken.cs

We will also want to eventually fix this in JsonWebToken, since any desktop framework besides NET45 will break this.
#if NET45
X509CertificatePublicCertValue = Convert.ToBase64String(credential.Certificate.GetRawCertData());
#elif NETSTANDARD1_3
X509CertificatePublicCertValue = Convert.ToBase64String(credential.Certificate.RawData);
#endif

fix net45 instead of net452

---

src/Microsoft.Identity.Client/Platforms/Android/AuthenticationContinuationHelper.cs
src/Microsoft.Identity.Client/Platforms/iOS/AuthenticationContinuationHelper.cs

This represents a breaking change to 2.6.1, and it fixes a breaking change we accidentally introduced in 2.6.0.

Change AuthenticationContinuationHelper namespace

---

src/MSAL.Common.props

This will allow developers to debug into MSAL, as long as they use VS 15.7+ 
It will do 2 things: 
1. Generate a snupkg package that contains the pdb files (one for each platform). We will need to upload this to NuGet 
2. Add a manifest containing urls to source files in the nuget package (You can use NuGet package explorer to see this manifest)

Add support for source link

---

global.json

Adding an "sdk" property to our global.json to lock us to 2.1.502 since I (and possibly others) need to run later versions of .NET sdk (3.0 preview) and that interferes with the build of this product since dotnet defaults to the latest sdk installed by default.

add sdk flag to global.json

---

src/Microsoft.Identity.Client/Cache/ITokenCacheAccessor.cs
src/Microsoft.Identity.Client/Features/PublicClientWithTokenCache/TokenCacheAccessor.cs
src/Microsoft.Identity.Client/IPublicClientApplication.cs
src/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs
src/Microsoft.Identity.Client/PublicClientApplication.cs
src/Microsoft.Identity.Client/TelemetryCore/TelemetryTokenCacheAccessor.cs
tests/devapps/XForms/XForms.iOS/AppDelegate.cs

Make obsolete KeychainSecurityGroup property
closing this [PR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/742) but have address comments here. was easier to open a new one.

add iOSKeychainSecurityGroup property for handling TeamID()

---

src/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
src/Microsoft.Identity.Client/Http/RedirectUriHelper.cs
src/Microsoft.Identity.Client/Platforms/net45/UIParent.cs
src/Microsoft.Identity.Client/Platforms/netstandard13/UIParent.cs
src/Microsoft.Identity.Client/Platforms/uap/UIParent.cs
src/Microsoft.Identity.Client/PublicClientApplication.cs
src/Microsoft.Identity.Client/UI/CoreUIParent.cs
tests/devapps/XForms/XForms.Android/Properties/AndroidManifest.xml
tests/devapps/XForms/XForms/App.xaml.cs

**Tested with:**
iOS embedded & system browser
Android embedded & system browser
Android w/default browser (not chrome or custom tabs)
**Todo:** uwp
- I added in comments for the system browser configuration in the android and ios dev app so it's easier to test. 
- The iOS entitlements were acting up, so I had to use the wildcard in the entitlements.plist and the new keychain property, and that worked, but I did not commit those changes. would like to spend more time on that.
@MarkZuber thanks for looking at this w/me...hopefully i didn't forget anything.

Pass embedded webview to CoreUiParent

---

src/Microsoft.Identity.Client/Http/HttpManager.cs
src/Microsoft.Identity.Client/Http/IHttpManager.cs
src/Microsoft.Identity.Client/WsTrust/IWsTrustWebRequestManager.cs
src/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Test.Common/MsalTestConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/AuthorityAliasesTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheFormatTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AadAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AdfsAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/B2cAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/WsTrustTests/WsTrustEndpointTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/WsTrustTests/WsTrustTests.cs
tests/Microsoft.Identity.Test.Unit.net45/JsonWebTokenTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/DeviceCodeRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/SilentRequestTests.cs

[#820](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/820)

send client info headers to userrealm endpoint

---

src/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenCommonParameters.cs
src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/Microsoft.Identity.Client/AppConfig/IAppConfig.cs
src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
src/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
src/Microsoft.Identity.Client/Utils/UriBuilderExtensions.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpAndServiceBundle.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Test.Common/Mocks/MockWebUI.cs
tests/Microsoft.Identity.Test.Common/Mocks/MsalMockHelpers.cs
tests/Microsoft.Identity.Test.Common/MsalTestConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/ApiConfigTests/Harnesses/AbstractBuilderHarness.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/SilentRequestTests.cs

As discussed with @jmprieur , WithClaims behaves similarly to setting ExtraQueryParameters to claims="...". I discovered that neither ExtraQueryParameters nor Claims are respected in Device Code Flow. I will follow up with a separate PR to address this.

Add support for WIthClaims

---

src/Microsoft.Identity.Client/@Diagrams/ApplicationBuilders.cd
src/Microsoft.Identity.Client/@Diagrams/AppsWithBuilders.cd
src/Microsoft.Identity.Client/@Diagrams/TokenRequestBuilders.cd
src/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/PublicClientApplicationBuilderTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs

Pretty mechanical.
The only thing to watch out is that we had one override with .WithAadAuthority which had the same signature than a WithAuthority method. 
I merged the XML comments, and removed one of them (the AAD specific one)

Renaming WithAadAuthority to WithAuthority

---

.editorconfig
build/install_dependencies.ps1

I'd like to get an editorconfig file to use with VS 2017/2019 that we can agree on.  This is mostly the sample from here:  https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017 with a few tweaks.  
I've also added a rule for private fields to be prefixed with _.

Create .editorconfig file

---

tests/Microsoft.Identity.Test.Unit.net45/CacheTests/ManualCacheLoadTest.cs

i can use this test to validate reading and using the python bin file until I have time to build out python language test automation in the cachecompat test suite.

Add manual test to validate python cache

---

src/Microsoft.Identity.Client/ApiConfig/AbstractClientAppBaseAcquireTokenParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AbstractConfidentialClientAcquireTokenParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AbstractPublicClientAcquireTokenParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenByIntegratedWindowsAuthParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenByRefreshTokenParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenByUsernamePasswordParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenWithDeviceCodeParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/Executors/AbstractExecutor.cs
src/Microsoft.Identity.Client/ApiConfig/Executors/ClientApplicationBaseExecutor.cs
src/Microsoft.Identity.Client/ApiConfig/Executors/ClientExecutorFactory.cs
src/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
src/Microsoft.Identity.Client/ApiConfig/Executors/PublicClientExecutor.cs
src/Microsoft.Identity.Client/ApiConfig/GetAuthorizationRequestUrlParameterBuilder.cs
src/Microsoft.Identity.Client/ClientApplicationBase.WithBuilders.cs
src/Microsoft.Identity.Client/ConfidentialClientApplication.WithBuilders.cs
src/Microsoft.Identity.Client/ConfidentialClientApplication.cs
src/Microsoft.Identity.Client/PublicClientApplication.WithBuilders.cs
src/Microsoft.Identity.Client/PublicClientApplication.cs
tests/Microsoft.Identity.Test.Unit.net45/ApiConfigTests/AcquireTokenInteractiveBuilderTests.cs
tests/Microsoft.Identity.Test.Unit.net45/ApiConfigTests/Harnesses/AcquireTokenInteractiveBuilderHarness.cs

We need to be able to wrap every one of our APIs in appropriate success/failure telemetry actions via MATS.  So this restructures the executors a bit to make them independent classes that we can wrap in a proxy instead of having PCA/CCA implement the I***Executor interfaces directly.
This does NOT impact the public API surface as all of this is internal implementation.

restructure client executors to enable proxy for mats

---

src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/PublicClientApplicationBuilderTests.cs

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/969

Fix [969]: CreateWithApplicationOptions does not respect the audience

---

src/Microsoft.Identity.Client/Http/HttpClientFactory.cs

regarding this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1019)

add nsurlsessionhandler as httpclient for ios 7+

---

src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/Microsoft.Identity.Client/Exceptions/MsalErrorMessage.cs
src/Microsoft.Identity.Client/Instance/B2CAuthority.cs
src/Microsoft.Identity.Client/Instance/B2COpenIdConfigurationEndpointManager.cs
src/Microsoft.Identity.Client/MsalError.cs
tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
tests/Microsoft.Identity.Test.Common/MsalTestConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheFormatTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
tests/devapps/DesktopTestApp/MainForm.Designer.cs
tests/devapps/DesktopTestApp/MainForm.cs
tests/devapps/DesktopTestApp/PublicClientHandler.cs
tests/devapps/XForms/XForms.Android/XForms.Android.csproj

@henrik-me have a few questions for you.

add b2c authority host to list

---

global.json

This enables a machine with only VS2019 on it to actually work.
I've created a clone PR project just changing to 602 there as well and it passes:
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=325168&_a=summary

update dotnet sdk to 2.1.602 in global json

---

src/Microsoft.Identity.Client/Internal/JsonWebToken.cs

When using WithSendX5c, the "x5c" token is not set when running on .NET Core. This change ensures this token gets set on all runtimes.

Ensure JsonWebToken sets X509CertificatePublicCertValue on .NET Core

---

tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs

disabling temporarily.
Scenario will be covered by manual testing until resolved
BUG:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1154

Disabling unstable test

---

src/Microsoft.Identity.Client/Instance/AadInstanceDiscovery.cs
src/Microsoft.Identity.Client/Utils/TraceWrapper.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpAndServiceBundle.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManager.cs
tests/Microsoft.Identity.Test.Common/TestCommon.cs
tests/Microsoft.Identity.Test.Unit.net45/BrokerParametersTest.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheNotificationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheFormatTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheV2Tests/TokenCacheV2Tests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AadAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AdfsAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/B2cAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/OAuth2Tests/TokenResponseTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/Telemetry/XmsCliTelemTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/WsTrustTests/MexParserTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/WsTrustTests/WsTrustTests.cs
tests/Microsoft.Identity.Test.Unit.net45/MatsTests/MatsPublicClientTests.cs
tests/Microsoft.Identity.Test.Unit.net45/OAuthClientTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ClientCredentialWithCertTest.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/BrokerRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/DeviceCodeRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/FociTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestWithCustomWebUiTests.cs
tests/Microsoft.Identity.Test.Unit.net45/TestBase.cs

This will help debugging threading issues. Tracing is lower level than logging and has a reduced impact (in production, calls to Trace are ignored if no trace listener is registered, in VS traces are routed to the Output window and we can register a trace programatically).

Add tracing to tests and product and a trace 2 file

---

src/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
src/Microsoft.Identity.Client/ApiConfig/Executors/ClientApplicationBaseExecutor.cs
src/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenSilentParameters.cs
tests/Microsoft.Identity.Test.Common/MsalTestConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ClientCredentialWithCertTest.cs

adding withsendX5C() on acquire token silent for the confidential client application
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1149

Implementing sendX5C on silent client credential call

---

src/Microsoft.Identity.Client/ClientApplicationBase.cs

for the public method public AcquireTokenSilentParameterBuilder AcquireTokenSilent(IEnumerable<string> scopes, IAccount account),
The comment said that the account parameter was optional. However, if you do not pass in an account, MSAL throws an MsalUiRequiredException stating that no account was passed into the method. thus, the comment is wrong.

updating comment on acquire token silent api

---

.editorconfig

Sorry, I should have added that these are an exact match of the .Net Fx repo https://github.com/dotnet/corefx/blob/master/.editorconfig
The rules do not seem too different from what we have (maybe the Allman stuff, which allows single line blocks without braces). Sadly, the rules have been moved around in the file, so the diff is crap.

Use .editorconfig from .net core https://github.com/dotnet/corefx

---

src/Microsoft.Identity.Client/Instance/AuthorityEndpointResolutionManager.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs

utests
[issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1214)

null ref fix in adfs w/no login hint

---

src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/Microsoft.Identity.Client/IPublicClientApplication.cs
src/Microsoft.Identity.Client/MsalError.cs
tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs

Fixes https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1196

Fix 1196 handling of Instance value in builder with trailing slash

---

src/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
src/Microsoft.Identity.Client/Core/Constants.cs
src/Microsoft.Identity.Client/Platforms/Android/AndroidPlatformProxy.cs
src/Microsoft.Identity.Client/Platforms/Mac/MacPlatformProxy.cs
src/Microsoft.Identity.Client/Platforms/iOS/iOSPlatformProxy.cs
src/Microsoft.Identity.Client/Platforms/net45/NetDesktopPlatformProxy.cs
src/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs
src/Microsoft.Identity.Client/Platforms/netstandard13/NetStandard13PlatformProxy.cs
src/Microsoft.Identity.Client/Platforms/uap/UapPlatformProxy.cs
src/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
src/Microsoft.Identity.Client/PlatformsCommon/Shared/AbstractPlatformProxy.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs

implementation of .WithDefaultRedirectUri() [#1186](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1186)

Add .WithDefaultRedirectUri() method to the PublicClientApplicationBuilder

---

src/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
src/Microsoft.Identity.Client/Cache/cache.readme.md
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedSchemaValidationTests.cs

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1199
I've tried to keep these tests very similar to the iOS tests located here: 
https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/blob/master/IdentityCore/tests/integration/MSIDCacheSchemaValidationTests.m
So that we can keep in sync with them easier.

Add unified schema validation tests

---

src/Microsoft.Identity.Client/MsalException.cs
tests/Microsoft.Identity.Test.Unit.net45/ExceptionTests/MsalExceptionTests.cs

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1245
Exception example now looks like this (from a unit test):
MSAL.Desktop.4.0.0.0.MsalUiRequiredException: 
ErrorCode: exCode
Microsoft.Identity.Client.MsalUiRequiredException: exMessage
StatusCode: 400 
ResponseBody: { "error":"invalid_grant", "suberror":"some_suberror",
"claims":"some_claims",
"error_description":"AADSTS90002: Tenant 'x' not found. ", "error_codes":[90002],"timestamp":"2019-01-28 14:16:04Z",
"trace_id":"43f14373-8d7d-466e-a5f1-6e3889291e00",
"correlation_id":"6347d33d-941a-4c35-9912-a9cf54fb1b3e"} 
Headers: Retry-After: 0

[1245] Add framework and version to MsalException ToString()

---

src/Microsoft.Identity.Client/MsalError.cs
src/Microsoft.Identity.Client/MsalErrorMessage.cs
src/Microsoft.Identity.Client/MsalServiceExceptionFactory.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Unit.net45/ExceptionTests/MsalExceptionTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs

fix for [making iwa/up/device code error better](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1249)
I tried it out w/a conf client i made in the portal. For all three auth flows (device code, iwa, u/p), i always got the same error:
{"error":"invalid_client","error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 3859ae12-01bc-4f57-9fd8-0bee7ec87b00\r\nCorrelation ID: 5467e70d-2025-43a8-92e9-758a143c0319\r\nTimestamp: 2019-07-12 23:33:09Z","error_codes":[7000218],"timestamp":"2019-07-12 23:33:09Z","trace_id":"3859ae12-01bc-4f57-9fd8-0bee7ec87b00","correlation_id":"5467e70d-2025-43a8-92e9-758a143c0319"}
So, @bgavrilMS  not sure how you got something else for u/p.
@jmprieur …

fix error message for invalid_client

---

src/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs

Removing the EnableBroker flag from the builder so we can release 4.2.  Broker will be back for 4.3 with a few fixes.

remove enablebroker flag from api

---

src/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
tests/Microsoft.Identity.Test.Common/MsalTestConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AadAuthorityTests.cs

Resolving issue with authority api adding an additional "/" to the end of the authority.
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1270

Resolving issue with authority api adding an additional "/" to the authority.

---

src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
src/Microsoft.Identity.Client/LogMessages.cs
src/Microsoft.Identity.Client/UI/AuthorizationResult.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs

[1276](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1276)
@jmprieur and @henrik-me we need to discuss this change and versioning.

change client exception back to service

---

src/Microsoft.Identity.Client/MsalError.cs
src/Microsoft.Identity.Client/MsalErrorMessage.cs
src/Microsoft.Identity.Client/Platforms/net45/WebUI.cs
src/Microsoft.Identity.Client/Platforms/uap/WebUI.cs

…Essentials for that.
Fixes bug https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/592 by providing a **consistent** approach to HTTP errors. See more details in the bug.
Note that this is theoretically a breaking change because we are changing exception logic, but in practice it should not make a difference, because if the network is down, MSAL will fail with an Http exception when making a discovery call.

Stop custom handling network down error

---

src/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
src/Microsoft.Identity.Client/Cache/ICacheSessionManager.cs
src/Microsoft.Identity.Client/Internal/Requests/ByRefreshTokenRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/Microsoft.Identity.Client/Internal/Requests/SilentRequest.cs
src/Microsoft.Identity.Client/MsalError.cs
src/Microsoft.Identity.Client/MsalErrorMessage.cs
src/Microsoft.Identity.Client/TokenCache.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpAndServiceBundle.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/BrokerParametersTest.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheTests.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheV2Tests/TokenCacheV2Tests.cs
tests/Microsoft.Identity.Test.Unit.net45/OAuthClientTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/BrokerRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestWithCustomWebUiTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/SilentRequestTests.cs

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1345
This is leftover from ADAL. In MSAL, you cannot set the TokenCache to null. There is a bit of product code and quite a few tests that internally set it to null, but it not a valid scenario.

Cleanup null cache non-used code paths

---

src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
tests/Microsoft.Identity.Test.Common/Mocks/MsalMockHelpers.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs

Send claims as query param to /authorize endpoint as per OIDC spec

---

build/pipeline-pullrequest.yaml
build/pipeline-releasebuild.yaml
build/pipeline-uiautomation.yaml
build/template-bootstrap-build.yaml
build/template-install-dotnet-core.yaml
build/template-install-keyvault-secrets.yaml
build/template-install-nuget.yaml
build/template-nuget-pack.yaml
build/template-pack-and-sign-all-nugets.yaml
build/template-pack-and-sign-nuget.yaml
build/template-postbuild-code-analysis.yaml
build/template-prebuild-code-analysis.yaml
build/template-publish-analysis-and-cleanup.yaml
build/template-publish-packages-and-symbols.yaml
build/template-python-config.yaml
build/template-restore-build-libsandsamples.yaml
build/template-run-integration-tests.yaml
build/template-run-unit-tests.yaml
build/template-sign-binary.yaml
src/Directory.build.props
src/extensions.msal/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj

Main thing I still need to fix is the warning on release builds around SemVer 2.0.  If folks know how to disable this warning, that would be helpful.
C:\Program   Files\dotnet\sdk\2.2.105\Sdks\NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(202,5):   Error NU5105: The package version '4.3.1-internal20190906.4yamltemplates'   uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on   legacy clients. Change the package version to a SemVer 1.0.0 string. If the   version contains a release label it must start with a letter. This message   can be ignored if the package is not intended for older clients.
--

Convert YAML builds into templates to share build steps

---

src/client/Microsoft.Identity.Client/Internal/Broker/BrokerParameter.cs
src/client/Microsoft.Identity.Client/Internal/Broker/BrokerResponseConst.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/AuthenticationContinuationHelper.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBroker.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBrokerConstants.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs
tests/devapps/XamarinDev/XamarinDev.iOS/Info.plist

**Part 1: iOS 13 broker support**
- Generate a nonce to send in the broker request, only if msauthv3 (iOS broker 6.3.19+) is installed on the device
- Check that the nonce in the broker response matches the nonce sent in the request
- Update info.plist in dev app for msauthv3
More info on these required changes [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/wiki/iOS-13-and-macOS-10.15-support-in-MSAL)
**Tested w/:**
- msauthv3 (iOS broker 6.3.19+)
- msauthv2 (iOS broker 6.3.12)
**TODO**: 
- Test w/iOS 13 and XCode 11 where source application returns null
- Create aka.ms link
- Update wiki and/or link to iOS team's docs
**Part 2:** Will include handling an application token, storing it in keychain and sending in the broker responses, but will do ADAL.NET work …

Part 1: iOS 13 broker support

---

src/client/Microsoft.Identity.Client/UI/CoreUIParent.cs

This change permits calling AcquireAuthorizationAsync() with an app RootViewController that is a UINavigationController with an empty navigation stack.
The top-level view controller will now be returned, rather than trying to recursively call FindCurrentViewController() on a null VisibleViewController (which causes a NullReferenceException).
Build the solution at https://github.com/davidjohnoliver/active-directory-Uno and run the iOS head.

[iOS] Support UINavigationController with empty stack

---

src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs

Removes the restriction common => organizations that was set up when Device Code flow did not work yet for Microsoft personal accounts.
When this PR is in, we also need to:
- Update https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Device-Code-Flow#constraints
- Update the following page in docs.ms: scenario-desktop-acquire-token.md (several locations in the page)
- remove references to AADSTS90133
- update docs.ms: scenario-desktop-app-registration.md
- update v2-supported-account-types.md
- update https://github.com/Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2/blob/master/device-code-flow-console/appsettings.json#L16

Enabling Device Code flow with personal accounts

---

src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/SystemWebUI.cs

i could not find any official documentation on .Start() and the main ui thread...also, Xamarin has not come out w/docs yet for the presentationContext and iOS 13 methods.

cleanup for presentationContext

---

.gitignore
tests/CacheCompat/CommonCache.Test.Common/ProcessUtils.cs
tests/CacheCompat/CommonCache.Test.MsalJava/JavaLanguageExecutor.cs
tests/CacheCompat/CommonCache.Test.MsalJava/Properties/launchSettings.json
tests/CacheCompat/CommonCache.Test.MsalJava/pom.xml
tests/CacheCompat/CommonCache.Test.MsalJava/src/main/java/TestConsoleApp.java
tests/CacheCompat/CommonCache.Test.MsalPython/PythonLanguageExecutor.cs
tests/CacheCompat/CommonCache.Test.Unit/CacheExecutionTests.cs

A few issues:
* Maven was not found as the process is a cmd, 
* The process runner was not able to run the cmd with-out a complete path to the cmd. 
* The latest Java library had introduced some updates to the public api
* Python executable location improved to enable local test runs (should not be needed but was not working locally on my box)
TODO:
* Lookup env var M2_HOME to find maven installation
* Add logging to the Java cache test

Update cache tests to enable the java to .net and python tests

---

src/client/Microsoft.Identity.Client/Internal/Broker/BrokerResponseConst.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBroker.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBrokerConstants.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs

- get application token in broker response
- save in keychain
- send in subsequent requests to v3 broker
tested w/iOS v3 broker
@bgavrilMS maybe you'll have time to take a look at this. also one for [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/pull/1672), but the changes are the same, so whatever comments made here, i will update in ADAL as well. 
Am also going to confirm w/iOS team tomorrow that this works as expected and they see the right stuff on their end. Also, am not sure which specific use case or test should be run to ensure the expected behavior happens, so will find out tomorrow. wanted to give you time to review, if you have time. 😼 thx.

iOS Broker Part II

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByRefreshTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Executors/ClientApplicationBaseExecutor.cs
src/client/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByAuthorizationCodeParameters.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByRefreshTokenParameters.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ClientCredentialWithCertTest.cs

fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1490

Adding sendX5C api to the acquire token by refresh token and auth code flows for confidential clients to enable SN+I.

---

tests/Microsoft.Identity.Test.Common/TestConstants.cs

Same as https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/commit/11326f0e4145a04e5ed33f9a3af1bcdcef1c862c
but for different tests

Fixing another instance of the certificate thumbprint

---

src/client/Microsoft.Identity.Client/Core/Constants.cs
src/client/Microsoft.Identity.Client/Internal/Requests/SilentRequest.cs
src/client/Microsoft.Identity.Client/Platforms/uap/WebUI.cs
tests/devapps/UWP standalone/MainPage.xaml
tests/devapps/UWP standalone/MainPage.xaml.cs
tests/devapps/UWP standalone/Package.appxmanifest

Using the test app, select the null redirect uri, which will use https://sso and then WEB auth to handle "sso". I signed in w/corp account and cloud account, and both show as previously signed in accounts using the UWP stand-alone test app. Similar to how we handle this in ADAL.

fix sso on uap and update uwp test app

---

src/client/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/Utils/ScopeHelper.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpAndServiceBundle.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheTests.cs

Ignore reserved OIDC scopes when searching the token cache

---

src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs

@bgavrilMS this resolves the null ref during interactive without broker. i know you want to do more refactoring, but wasn't sure if we wanted a quick fix or something more long term. here is a quick fix.
- tested w/system browser and embedded webview. I don't have the v2 android broker on my device, so didn't test any broker related flows.

fix for null ref during interactive flow w/out android broker

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByRefreshTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs

This is solving https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1568

Adding an aka.ms link (for first party partners) to the XML doc for WithSendX5C.

---

src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs

Removing unneeded semaphore as it has the potential to cause threading issues in the future.

Removing unneeded semaphore release

---

src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs

Why?
The username from the IDToken could not match the username provided by the user, provoking a cache miss. 
This fixes this issue

Removing case sensitive check from MSAL broker

---

src/client/Microsoft.Identity.Client/Instance/AuthorityEndpointResolutionManager.cs
src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs
src/client/Microsoft.Identity.Client/Internal/JsonWebTokenConstants.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/B2cAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit.net45/UtilTests/JsonHelperTests.cs

This fixes the ADFS + confidential client scenario
Tested on an Azure Stack env which uses ADFS 2019. 
Needs an integration test, for which I am discussing with the lab team. Will follow up separately.

Fix for #1708 - use token_endpoint as issuer and x5t in header

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/Internal/Broker/IBroker.cs
src/client/Microsoft.Identity.Client/Internal/Broker/NullBroker.cs
src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs
src/client/Microsoft.Identity.Client/Platforms/Android/BrokerConstants.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBroker.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/BrokerRequestTests.cs

Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1676

Enabling the Remove account api on MSAL for andorid broker

---

src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs

fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1642
Disabling warning for CRL check

Disabling warning for the CRL check in the android broker flow

---

src/client/Microsoft.Identity.Client/Cache/CacheFallbackOperations.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/CacheTests/CacheFallbackOperationsTests.cs

When upn provided as a filter GetAllAdalEntriesForMsal is returning full list when upn is not found. Same problem with uniqueid. This creates issue when cache contains other accounts and library tries to use refresh token from other that account provided in login hint resulting in "Returned user identifier does not match the sent user identifier when saving the token to the cache" errors

Fixed filtering by upn and uniqueid

---

src/client/Microsoft.Identity.Client/Internal/ClientCredentialWrapper.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/RequestValidationHelperTests.cs

Fix for [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1795) 
Also related to this issue in [ms identity web](https://github.com/AzureAD/microsoft-identity-web/pull/139)
Repro: 
- Create a confidential client using application options (or without, based on my testing), and do not include a client secret, certificate or assertion. 
- In `ClientCredentialWrapper` the default enum value is `ClientCertificate`, so when no value is provided in creating the cca, the default AuthenticationType is `ClientCertificate`. Later, in `ClientCredentialHelper`, we go the path of `ClientCertificate` and MSAL throws a null ref on line 80 when trying to sign something it doesn't have:
`clientCredential.CachedAssertion = jwtToken.Sign(clientCredential, sendX5C);` …

fix enum default value for `ConfidentialClientAuthenticationType`

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/BrokerRequestTests.cs

Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1775
Validated with manual testing.
Adding a new manual test for this to the spreadsheet
I also verified that this is the same behavior on MSAL Andorid

Allowing android broker flow to return accounts from local MSAL cache when broker is not installed and WithBroker() is true

---

tests/devapps/XamarinDev/XamarinDev/App.xaml.cs

This default clientId will not work w/any non-broker flow, as it doesn't have the correct redirect uri registered and the android manifest was not updated. I have added the android broker redirect uri to this client Id in the portal, so everything should work with this one client id.

use previous clientId w/mobile apps

---

tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.netcore.csproj
tests/Microsoft.Identity.Test.Unit.netcore/Microsoft.Identity.Test.Unit.netcore.csproj
tests/devapps/NetCoreTestApp/NetCoreTestApp.csproj

This should improve team experience, as .net core 2.1 SDK is no longer installed by default with VS and people cannot easily run netcore tests locally.

Update test projects to netcore 3.1

---

src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs

Found a bug in the android broker where if you send the prompt without making the text uppercase the json parsing will sometimes fail on the broker side and crash the broker app. It just so happened that adding claims to the json trigged this bug. They are going to fix in the next release.

Uppercasing prompt parameters to avoid broker failures

---

src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
tests/Microsoft.Identity.Test.Unit.net45/CoreTests/WsTrustTests/WsTrustTests.cs

This returns the body of the response if there is a parse error. It would have been really helpful to realize what this issue was. Instead I had to compile the library from source and debug it.
This drove me crazy. I kept getting an error attempting to Seamless SSO that spawned this issue here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1825
Turns out our firewall was intercepting the traffic and categorizing the SSSO site as "uncategorized" which requires a manual step to approve. It was basically impossible for me to determine this was an issue because the body was not being returned when there was a parse error.

On WsTrust parse error, return body

---

src/client/Microsoft.Identity.Client/Instance/Validation/AdfsAuthorityValidator.cs
src/client/Microsoft.Identity.Client/Internal/Broker/BrokerInteractiveRequestComponent.cs
src/client/Microsoft.Identity.Client/Internal/Broker/BrokerSilentRequest.cs
src/client/Microsoft.Identity.Client/Internal/Logger/ICoreLogger.cs
src/client/Microsoft.Identity.Client/Internal/Logger/MsalLogger.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs

There should be only 1 place to get the CorrelationId from - the RequestContext.

Make correlationID available only on RequestContext

---

src/client/Microsoft.Identity.Client/Platforms/net45/NetDesktopPlatformProxy.cs

Added try/catch around InternalGetDeviceId for NetDesktop as this causes a crash when used from an Azure Runbook.
This can be simulated by running the following line in an Azure Runbook which equals the line being wrapped in try/catch here:
```powershell
[System.Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces()
```
It will throw the exception:
`_Get-PnPAccessToken : Unable to find an entry point named 'GetPerAdapterInfo' in DLL 'iphlpapi.dll'_.`
Reported to us via https://github.com/pnp/PnP-PowerShell/issues/2726
We can't switch to using MSAL .Net Core or MSAL .Net Standard as within [PnP PowerShell](https://aka.ms/pnp-powershell) we are also using the interactive login method:
```c#
var token = await AzureAuthHelper.AuthenticateAsync(Tenant);
```
which requires a …

Added try/catch around InternalGetDeviceId for NetDesktop

---

src/client/Microsoft.Identity.Client/AccountId.cs
src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentClientAuthStrategy.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentRequest.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/AcquireTokenSilentTests.cs

This is for #1902 for confidential client scenarios, and has more info on the issue.
[ ] OBO should use the AT hash as the cache key, because the claims in the AT can change, so we use the AT directly to determine the cache key so the right AT is used.
[ ] Client credentials uses `{client_id} + "_AppTokenCache"`, as it's using the app token cache, so it needs the token based on the client id. MS Identity Web suffixes it w/`"_AppTokenCache"`, so we'd like to keep this pattern to not break current customers.
[ ] all other confidential client flows (including silent) use the home account id, as the key, because there is a user account. 
In order to make the changes in MS Identity Web, we'd need to have this addition included in a nuget package. We have a deadline of July 6 on our end. cc: …

Add suggested cache key for confidential client scenarios

---

src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryManager.cs
tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/TelemetryTests.cs

Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1912

Disable all MATS telemetry if not configured

---

src/client/Microsoft.Identity.Client/Cache/CacheFallbackOperations.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Unit.net45/CacheTests/CacheFallbackOperationsTests.cs

Potential fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1925
This error occurs when that ADAL cache is invalid due to multiple RTs for one account. This change will clear the ADAL cache to allow the user to continue

WIP Clear ADAL cache during error

---

src/client/Directory.Build.props
tests/Microsoft.Identity.Test.Unit.net45/UtilTests/JsonHelperTests.cs

Remove legacy netstandard1.x package references for .NET Core 2.1+ target.
Also fixed a test that fails in UTC+N timezones.

Remove obsolete dependencies

---

src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs

Testing workaround for PKey Auth bypass

Adding PKey Auth bypass to interactive auth flows

---

tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs

Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1920

Enabling AcquireTokenADFSV4InteractiveFederatedTest

---

src/client/Microsoft.Identity.Client/IPublicClientApplication.cs

The reference's documentation cosmetics was broken
Attempting to fix it by adding a table
No semantics change

Fixes #1890

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/Platforms/netdesktop/Http/NetDesktopHttpClientFactory.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/SimpleHttpClientFactory.cs

Addressing this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2046#discussion_r526348786

Update comments about missing exception in http client

---

src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/WsTrustTests/WsTrustTests.cs

This is related to #2193 but it is not a fix.

Remove misleading / badly named header from Kerberos

---

changelog.txt
src/client/Microsoft.Identity.Client/ApiConfig/AbstractConfidentialClientAcquireTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
tests/Microsoft.Identity.Test.Unit/ExceptionTests/ExperimentalFeatureTests.cs
tests/Microsoft.Identity.Test.Unit/pop/PopAuthenticationSchemeTests.cs
tests/devapps/NetFxConsoleTestApp/Program.cs

@jmprieur @bgavrilMS  i don't think possession is spelled right. i was updating the PoP sample and noticed it. [See below](https://tools.ietf.org/html/draft-ietf-oauth-pop-architecture-08#:~:text=OAuth%202.0%20Proof-of-Possession%20%28PoP%29%20Security%20Architecture%20draft-ietf-oauth-pop-architecture-08.txt%20Abstract,resources%20%28without%20demonstrating%20possession%20of%20a%20cryptographic%20key%29.):

fix spelling

---

build/pipeline-releasebuild.yaml
build/template-ci-and-pr.yaml
build/template-run-all-tests.yaml
build/template-run-integration-tests.yaml
build/template-run-unit-tests.yaml

Making changes to pipeline to allow tests to run on release build based on the value of RunTests.
RunTests can be set in the beginning of the test run.
true to run tests, false not to.
This will be true by default so tests will always run.
This will also trigger ui automation on the master branch
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2278

Adding test runs to release build

---

src/client/Microsoft.Identity.Client/Region/IRegionDiscoveryProvider.cs
src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RegionalAuthIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/RegionDiscoveryProviderTests.cs

Proposed fix for issue https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2260

remove original authority from metadata aliases

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationOptions.cs
src/client/Microsoft.Identity.Client/AppConfig/IAppConfig.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCache.cs
tests/Microsoft.Identity.Client.Performance/AdalCacheOperationsTests.cs
tests/Microsoft.Identity.Client.Performance/LegacyCacheOperationsTests.cs
tests/Microsoft.Identity.Client.Performance/Program.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/LegacyTokenCacheHelper.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
tests/Microsoft.Identity.Test.Common/TestCommon.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/CacheFallbackOperationsTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs

Issue #1770 
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-9850H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.101
[Host]                      : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT
Job-GetAllAccessTokensTests : .NET Core 3.1.10 (CoreCLR 4.700.20.51601, CoreFX 4.700.20.51901), X64 RyuJIT
Job=Job-GetAllAccessTokensTests  
```
|      Method | Cache Size | ADAL Cache Enabled |          Mean |         Error |        StdDev |        Median |
|------------ |--------------- |---------------- |--------------:|--------------:|--------------:|--------------:|
|   SaveToken |              1 |           False |    **114.627 μs** |     5.0409 μs |    14.3002 μs |    110.700 μs |
|   SaveToken |              1 | …

Disable ADAL cache

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RegionalAuthIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs
tests/Microsoft.Identity.Test.Unit/TelemetryTests/RegionalTelemetryTests.cs
tests/devapps/RegionalTestApp/Program.cs

Update the api as discussed in the meeting with default value for FallbackToGlobal as true.

Fix spelling and mark default to true for FallbackToGlobal

---

tests/CacheCompat/CommonCache.Test.MsalV3/Program.cs

I assume the Debugger calls were for manual testing. @bgavrilMS proposing to remove them because every time I run unit tests locally, the Attach Debugger window pop ups...

Remove debugger in CacheCompat.Test.MsalV3 project

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/Internal/Logger/MsalLogger.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs

No perf impact on FindAccessToken logic...
Before
|                         Method | TokenCacheSize |     Mean |   Error |  StdDev |
|------------------------------- |--------------- |---------:|--------:|--------:|
| AcquireTokenForClientTestAsync |         100000 | 104.9 ms | 2.06 ms | 2.37 ms |
After
|                         Method | TokenCacheSize |     Mean |   Error |  StdDev |
|------------------------------- |--------------- |---------:|--------:|--------:|
| AcquireTokenForClientTestAsync |         100000 | 104.4 ms | 2.05 ms | 2.52 ms |

More verbose logging around FindAT and SaveMsalResponse

---

src/client/Microsoft.Identity.Client/Cache/SuggestedWebCacheKeyFactory.cs
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs

@bgavrilMS here's a proposed fix to adding the tenantID to the suggested cache key on app tokens (see #2381).

Added tenantID to suggested app token cache key

---

src/client/Microsoft.Identity.Client/Cache/CacheRefresh.cs
src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Silent/CacheSilentStrategy.cs
src/client/Microsoft.Identity.Client/TelemetryCore/Http/HttpTelemetryManager.cs
src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Constants/MsalTelemetryBlobEventNames.cs
src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Events/ApiEvent.cs
src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryConstants.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpAndServiceBundle.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RegionalAuthIntegrationTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/UsernamePasswordIntegrationTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/HttpTelemetryRecorder.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
tests/Microsoft.Identity.Test.Unit/TelemetryTests/HttpTelemetryTests.cs
tests/Microsoft.Identity.Test.Unit/TelemetryTests/RegionalTelemetryTests.cs

#2356 
As per spec:
0 if token request goes to ESTS because no cached AT exists, 
1 if token request goes to ESTS becasue cached AT expired, 
2 if token request goes to ESTS because refresh_in was used and the existing token needs to be refreshed, 
3 if token request goes to ESTS because force_refresh was set to true, blank if the cache is not hit to make the request
@neha-bhargava  - if you're using a broker, please confirm that the value will be ""

Add telemetry for cache refresh

---

src/client/Microsoft.Identity.Client/Http/HttpManager.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RegionalAuthIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/RegionDiscoveryProviderTests.cs
tests/devapps/RegionalTestApp/Program.cs

Fixes for two bugs with regional instance discovery.
After the app startup, during the instance discovery flow, there are at least two calls made to the `TryGetMetadataAsync` in `RegionDiscoveryProvider`. First call passes in a known authority (like login.microsoft.com). Second call passes in a regionalized authority (like region.login.microsoft.com).
1
In `BuildAuthorityWithRegionAsync` method there's [code at the end that transforms the passed-in URL by adding a region](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/018c34ef0efbd7902aa71a1370609998911c345d/src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs#L263). During the first call, the known authority is correctly transformed into a regionalized authority. However, during the second …

Fix instance discovery caching.

---

build/platform_and_feature_flags.props
src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
src/client/Microsoft.Identity.Client/json/Serialization/DefaultContractResolver.cs
src/client/Microsoft.Identity.Client/json/Serialization/ExpressionValueProvider.cs
src/client/Microsoft.Identity.Client/json/Serialization/JsonTypeReflector.cs
src/client/Microsoft.Identity.Client/json/Utilities/ExpressionReflectionDelegateFactory.cs
tests/Microsoft.Identity.Test.Performance/JsonTests.cs
tests/Microsoft.Identity.Test.Performance/Program.cs

One of the possible solutions to #2428.
Adds a Unity preprocessor flag. Updates the JSON.NET code to use late bound serializers for Unity.
**Perf test results**
NetCore3.1 before changes:
|                                     Method |      Mean |     Error |    StdDev |
|------------------------------------------- |----------:|----------:|----------:|
|           Serialize_MsalTokenResponse_Test |  7.819 μs | 0.0984 μs | 0.0920 μs |
|         Deserialize_MsalTokenResponse_Test | 12.899 μs | 0.1522 μs | 0.1423 μs |
|   Serialize_InstanceDiscoveryResponse_Test | 41.662 μs | 0.0342 μs | 0.0267 μs |
| Deserialize_InstanceDiscoveryResponse_Test | 72.998 μs | 0.8727 μs | 0.7288 μs |
|          Serialize_OAuth2ResponseBase_Test |  2.213 μs | 0.0152 μs | 0.0134 μs |
| …

Update JSON.NET code to work with Unity.

---

src/client/Microsoft.Identity.Client/Properties/Microsoft.Identity.Client.rd.xml

Issue #1617
Adds Microsoft.Identity.Client to rd.xml, which prevents MSAL code from being stripped out when the app build is optimized.
**Testing**
1. Use [MsalDotNetNative.zip](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/files/6066658/MsalDotNetNative.zip)
2. Update `ClientID` property in MainPage.xaml.cs and UWP redirect URI in Azure app registration.
3. Verify correct MSAL dependency version.
4. Change configuration to **Release x64**.
5. Make sure **Optimize code** and **Compile with .NET Native tool chain** in project **Build** properties are checked.
5. Click **Log in** button and log in.
6. A dialog should display **Success** text.

Add Microsoft.Identity.Client to rd.xml

---

src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs

Issue #1967
`GetAccountsAsync` in `IConfidentialClientApplication` overwrites one in `IClientApplicationBase`. Adds `obsolete` attribute.

Obsolete attribute to GetAccounts for CCA.

---

src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs

Issue #2461
As discussed with Bogdan, logging this in the `RequestBase` seemed the most appropriate because during CCA/PCA app instance creation/building we don't know yet if the cache is serialized, and we don't have existing way elsewhere to check if app instance is PCA or CCA.

Log error when CCA doesn't use cache serialization.

---

src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopCryptographyManager.cs

Should help with https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2305

.NET classic - use absctract cprypto builders instead of concrete impl

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTests.cs

Issue #2434.
When merging broker accounts into a resulting collection with cached accounts, check the resulting collection, instead of the original cached one, for duplicates.
Also add test that adds two identical accounts to broker, then calls `GetAccountAsync`.
Wasn't able to repro the bug. Performed general testing with Xamarin dev app and broker.

When merging cache and broker accounts, check resulting collection.

---

src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamAdapters.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs

Please see #2476 for details 
Fix works for: 
|                     | Works ?|
| ------------- |:-------------:|
| AAD User + normal app    | yes |
| MSA User + normal app  | yes |
| AAD User + MSA-PT app    | yes |
| MSA User + MSA-PT app  | no |
which is better than current status, where AAD users cannot login.

Partial fix for #2476 - WAM + /organizations + login hint

---

src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ConfidentialClientIntegrationTests.cs

Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1845

Adding support for Service principasl on OBO

---

src/client/Microsoft.Identity.Client/Platforms/Android/SystemWebview/AuthenticationActivity.cs

Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2418
The proper way to support custom tabs on android 29+ is to use the new custom tab intent as described [here](https://developer.android.com/reference/androidx/browser/customtabs/CustomTabsIntent).
While trying out the new CustomTabsIntent, the custom tab shows up but our code does not capture the auth response. It will take a bit of work in MSAL to get this to happen so in the meantime we can use the android.support.customtabs implemented in this PR
Tested on andoridX and 11

Using android.support.customtabs for android api 29+

---

src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
src/client/Microsoft.Identity.Client/MsalError.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RegionalAuthIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs
tests/Microsoft.Identity.Test.Unit/TelemetryTests/RegionalTelemetryTests.cs
tests/devapps/RegionalTestApp/Program.cs

When using regional authorities, they are not validated and as such, `validateAuthority` should be set to false explicitly to drive expectations. 
A regionalized authority is seen as invalid by ESTS, e.g. `westus.microsoft.com` is not valid. So there is no support for validating the regionalized authority.
There is however support to validate the original authority, i.e. `login.microsoftonline.com` or whatever is passed in. And we could assume that if original authority is valid, then `region + original env` is also valid. This would be an improvement over the existing implemenattion and should be treated separately.

ValidateAuthority must be false when using regional

---

src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs

Issue #2427
Refactored open browser code. For Linux, added more "open" tools and searching for them in PATH variable.
Tested on Ubuntu, seems to work. Windows also still works.
To do after release:
- Update [Linux section](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/System-Browser-on-.Net-Core#linux-and-mac) in System Browser wiki.

Redirect outputs for xdg-open in Linux

---

build/template-publish-packages-and-symbols.yaml

Suggested to be enabled in 1ES [wiki](https://www.1eswiki.com/wiki/Using_Azure_DevOps_Symbols#Source_Indexing) and [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/index-sources-publish-symbols?view=azure-devops).
> Indexing source code enables you to use your .pdb symbol files to debug an app on a machine other than the one you used to build the app. For example, you can debug an app built by a build agent from a dev machine that does not have the source code.

Set IndexSource to true (by default) for symbol publishing

---

src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DeviceAuthHelper.cs
tests/Microsoft.Identity.Test.Android.UIAutomation/Microsoft.Identity.Test.Android.UIAutomation.csproj
tests/Microsoft.Identity.Test.Core.UIAutomation/Microsoft.Identity.Test.UIAutomation.Infrastructure.csproj
tests/Microsoft.Identity.Test.iOS.UIAutomation/Microsoft.Identity.Test.iOS.UIAutomation.csproj

The issue is when running automated mobile UI tests, NETSTANDARD flag is set (instead of the mobile flags), which results in DesktopOsHelper method being called and throwing an error. When running the Xamarin app, the mobile flags are set correctly, so the logic is correct. I tried adding a MOBILE_UI_TESTS flag in UI test projects (d34079242a4ff4a936266de30bca8ecaec45d102) but it didn't work. For now just catching that error and returning false. (Although, adding a tests flag would be better).

Fix automated UI tests

---

src/client/Microsoft.Identity.Client/Platforms/iOS/IosHttpClientFactory.cs

The iOS NSUrlSessionHandler needed to use a workaround to ensure that
Http requests that were performed by the application did not end up in a
stale situation in which the completion would never be reached. This was
due to https://github.com/xamarin/xamarin-macios/pull/5463
This workound will listen to the UIApplication notifications and would
cancel all the inflight requests. For reference, this happens here:
https://github.com/xamarin/xamarin-macios/blob/main/src/Foundation/NSUrlSessionHandler.cs#L174
As you can see, if we set the property to false, we will get the
notification. This is **not longer needed** as mono fixed the runtime
issue. The Xamairn.iOS team skips that workaround by default as per
this commit:
https://github.com/xamarin/xamarin-macios/commit/b6fbae5cfb90361605e9608b3b …

[iOS] Do not use the background check in the iOS handler.

---

src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/Platforms/Features/DefaultOSBrowser/HttpListenerInterceptor.cs

Issue #2219
We don't really know why a HttpListenerException will be thrown, so just adding a more descriptive error message.

More descriptive error message when MSAL is listening for OS browser.

---

src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AbstractConfidentialClientAcquireTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
src/client/Microsoft.Identity.Client/ApiConfig/GetAuthorizationRequestUrlParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenInteractiveParameters.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/GetAuthorizationRequestUrlParameters.cs
src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

from @jmprieur:
```csharp
// Get the authorization URL
string codeVerifier = null;
url = await cca.GetAuthorizationRequestUrl(scopes)
.WithPkce(ref codeVerifier)
.ExecuteAsync()
...
// use the authorization request URL to let the user sign-in, which provides the code
...
// and redeem the code
cca.AcquireTokenByAuthorizationCode(scopes, code, codeVerifier)
.ExecuteAsync();
```
```CSharp
// I generate myself the code verifier (with my own algorithm)
string codeVerifier = GenerateMyHomeGrownSpecialCodeVerifier();
// Get the authorization URL
url = await cca.GetAuthorizationRequestUrl(scopes)
.WithPkce(ref codeVerifier)
.ExecuteAsync();
...
// use the authorization request URL to let the user sign-in, which provides the code
...
// and redeem the code …
```

Jennyf/pkce - public API example

---

src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidAccountManagerBroker.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidContentProviderBroker.cs

Fix for querying Android content provider plus nit renamings. Fix is to do normal Base64 encoding instead of Base64 URL encoding. Repro is to provide the bundle (basically just the client Id and redirect URI) that would result in Base64 and Base64Url encoded values being different. Android then throws an exception trying to Base64 decode a Base64Url encoded value.
Issue #2554 
Also (unverified) possible fix for #2467 as Android seemed to throw bad magic exception if operation parameters passed to query method where malformed.

Fix for querying Android content provider

---

global.json

Newer version of MSBuild.Sdk.Extras fixes the MSB4011 warnings. ([PR](https://github.com/novotnyllc/MSBuildSdkExtras/pull/249) for reference.)

Update MSBuild.Sdk.Extras version.

---

src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
tests/Microsoft.Identity.Test.Performance/AcquireTokenForClientLargeCacheTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSerializationTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheNotificationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs
tests/devapps/NetFxConsoleTestApp/Program.cs
tests/devapps/WAM/UWPWam/MainPage.xaml.cs

Fixes # .
#2551 
Add UserCancellationToken from the request context to [TokenCacheNotificationArgs.cs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2658/files#diff-b0faf05b6dd32a06c308fcd6ddc4ccbaaf7379349017eb821f9701820a06e5f4R23)
Updated calling methods to pass in UserCancellationToken
**Testing**
Added unit tests [TokenCacheNotificationTests.cs](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/2658/files#diff-cf04432db495972478d12c22d59cd3f47b88964cb0ebe9358cb23c1cad119546R275)
No

Add UserCancellationToken to CacheNotificationArgs

---

src/client/Microsoft.Identity.Client/WsTrust/MexDocument.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
tests/Microsoft.Identity.Test.Unit/Resources/TestMex3rdParty.xml

Fixes # .
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2665
Enabling mexDocument to search for wsdl:definition node in federation metadata XML
Added proper exception for federation metadata parsing
Added unit test
**Testing**
Added unit test
None

Enabling mexDocument to search for wsdl:definition node in federation metadata XML

---

src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs

Fixes # .
Add extra verbose logging when filtering access tokens by environment. We had logs for other filters, but not this one.
**Testing**
Manually with a dev app.
Only for Verbose logging, extra `.Count` on token collection.

Add extra filtering by env logs.

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
src/client/Microsoft.Identity.Client/Internal/IServiceBundle.cs
src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/Internal/ServiceBundle.cs
src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs
src/client/Microsoft.Identity.Client/TokenCache.cs
tests/Microsoft.Identity.Test.Common/TestCommon.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ConfidentialClientIntegrationTests.cs
tests/Microsoft.Identity.Test.Performance/LegacyCacheOperationsTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/UnifiedCacheTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/OAuth2Tests/TokenResponseTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/RegionDiscoveryProviderTests.cs
tests/Microsoft.Identity.Test.Unit/OAuthClientTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryTests.cs

Fixes - no work item, need more logging for investigation.
- log app config hash code, to be able to tell if requests belong to same app
- rename DefaultLogger to AppLogger
- enhance an integration test to use WithAuthority at request level
**Testing**

Add more logging and small enhacement to an int test

---

src/client/Microsoft.Identity.Client/Http/HttpManager.cs

Fixes # .
Measure GetHttpClient call in "time spent in HTTP"
**Testing**

Measure GetHttpClient call as well

---

src/client/Microsoft.Identity.Client/Internal/Constants.cs
src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/IntegratedWindowsAuthRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeExchangeComponent.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/IAuthCodeRequestComponent.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/InteractiveRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/Internal/Requests/UsernamePasswordRequest.cs
src/client/Microsoft.Identity.Client/UI/AuthorizationResult.cs
src/client/Microsoft.Identity.Client/Utils/CoreHelpers.cs
tests/Microsoft.Identity.Test.Common/TestCommon.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/UsernamePasswordIntegrationTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/InteractiveFlowTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/InteractiveRequestOrchestrationTests.cs

Adding ccs header for interactive request using client info.
Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2525
Adding ccs header for interactive request using client info.
Requesting client info from authorize endpoint
**Testing**
existing integration tests cover scenario
Minor. For interactive flow only

CCS Header updates for interactive request

---

tests/Microsoft.Identity.Test.Performance/AcquireTokenForClientLargeCacheTests.cs

Fixes # .
Fix for performance test
Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.Identity.Client.MsalClientException: You did not define an authority at the application level, so it defaults to the https://login.microsoftonline.com/common.
However, the request is for a different cloud login.microsoft.com. This is not supported - the app and the request must target the same cloud.
Correct Authority
**Testing**
Manual testing of performance app
None

Fixing performance test project

---

.editorconfig

Fixes # .
Updated EditorConfig to add copyright header to new files. 
Note: If the file doesn't have a header, set the rule to warning, but it doesn't seem to work for existing files.

Update EditorConfig to add copyright file header for new files.

---

src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Common/TestCommon.cs
tests/Microsoft.Identity.Test.Performance/AcquireTokenForClientLargeCacheTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2486
Adds SuggestedCacheExpiry to the TokenCacheNotificationArgs
**Testing**
Manual testing
Unit test
Negligible performance impact

Add token expiry to token cache notification args

---

tests/Microsoft.Identity.Test.Performance/AcquireTokenForClientLargeCacheTests.cs

Speeds up the large cache perf test. For ByScope test, serializing internal cache only after all tokes are added to the internal cache, since there's only partition.

Improve large cache test populate perf cache.

---

src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AccountPicker.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamProxy.cs

Fixes # .
Fixing build error: "WebAuthenticationCoreManagerInterop' is an ambiguous reference between 'Microsoft.Identity.Client.Platforms.net5win.WebAuthenticationCoreManagerInterop' and 'Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManagerInterop"

Fix build issue (Ambiguous reference)

---

src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
src/client/Microsoft.Identity.Client/Platforms/Features/WebView2WebUi/WinFormsPanelWithWebView2.cs

Fixes #2685.
Upgrade to WebView2 SDK 1.0.864.35.
Disable Accelerator keys like F12, Ctrl+P (allowing keys like Ctrl+C, Ctrl+V, arrow keys). (Change is needed because the behavior on the new version is different from older one.)
**Testing**
Tested in NetFx, Net5, and NetCore.

Upgrade WebView2 SDK and disable accelerator keys

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/GetAuthorizationRequestUrlParameterBuilder.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/OboRequestTests.cs

Fixes # .
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2755
Removes null check from WithCCS apis
**Testing**
Adding unit test
None

Remove null check from CCS APIs

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.WithRegion.cs

Ignoring regional test InvalidRegion_GoesToInvalidAuthority_Async
See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2781
Fixes # .
Ignoring regional test InvalidRegion_GoesToInvalidAuthority_Async
Ignoring regional test InvalidRegion_GoesToInvalidAuthority_Async

Ignoring failing test

---

src/client/Microsoft.Identity.Client/Account.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationOptions.cs
src/client/Microsoft.Identity.Client/Cache/AdalCacheOperations.cs
src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
src/client/Microsoft.Identity.Client/ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/MigrationAid/TokenCache.MigrationAid.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCache.cs
src/client/Microsoft.Identity.Client/Utils/OptionalSemaphoreSlim.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/InMemoryTokenCache.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests2.cs
tests/Microsoft.Identity.Test.Unit/AuthorityAliasesTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSerializationTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSyncronizationTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheNotificationTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/UnifiedCacheFormatTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/FociTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/SilentRequestTests.cs
tests/devapps/DesktopTestApp/MainForm.cs
tests/devapps/XamarinDev/XamarinDev/CachePage.xaml.cs

One of the fixes related to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2443 / MyApps
Disables the internal cache semaphore, which allows requests to bypass other requests that timeout.

Allow apps to disable the cache semaphore

---

src/client/Microsoft.Identity.Client/Instance/AuthorityManager.cs
src/client/Microsoft.Identity.Client/Instance/Discovery/KnownMetadataProvider.cs
src/client/Microsoft.Identity.Client/Instance/Discovery/RegionDiscoveryProvider.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.WithRegion.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/RegionDiscoveryProviderTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs

Fixes #2777 #2778 
1. Ensure instance discovery does not occur on known clouds (this was happening already, but added some tests)
2. Use "preferred_network" value for known clouds
**Testing**
unit
reduce number of http calls -> better perf
also removed a string comparison

Use preferred_network and skip discovery for known clouds

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByRefreshTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Executors/ClientApplicationBaseExecutor.cs
src/client/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByAuthorizationCodeParameters.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByRefreshTokenParameters.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenForClientParameters.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenOnBehalfOfParameters.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenSilentParameters.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/IAppConfig.cs
src/client/Microsoft.Identity.Client/Internal/ClientCredentialWrapper.cs
src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs
src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.WithRegion.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
tests/Microsoft.Identity.Test.Unit/UtilTests/JsonHelperTests.cs

Proposes a solution for #2804
Add WithSendX5C to ConfidentialClientApplicationBuilder. 
Makes the existing SendX5C channeled throughout confidential clients nullable, to be overwritten at request time by the default-null SendX5C within the ConfidentialClient. 
Marks the per-request SendX5C Builder methods as Obsolete, so that devs know to switch to per-app X5C. 
**Testing**
Inline updates to the existing unit tests, to switch away from the per-request model and into the per-app model.  This should validate that the claim is appearing as expected as a result of this change. 
No perf impact expected.

ConfidentalClientApplicationBuilder WithSendX5C

---

LibsAndSamples.sln
build/pipeline-ci.yaml
build/pipeline-releasebuild.yaml

Fixes # .
Fixing scheduled builds not running nightly
Adding "always: true" to ensure scheduled builds run always.
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#running-even-when-there-are-no-code-changes

Adding "always: true" to ensure scheduled builds run continuously.

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/ConfidentialAppSettings.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs

Fixes # .
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2852
Enabling App Id Uri to be used with web apps
**Testing**
Unit/Integration
None

Enabling App Id Uri to be used with web apps

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs

Moving target to buildAutomation keyvault
Fixes # .
Fix for CreateWwwAuthenticateResponseFromKeyVaultUrlAsync Test
Changing target to buildAutomation keyvault
**Testing**
Integration test
N/A

Fix for CreateWwwAuthenticateResponseFromKeyVaultUrlAsync Test

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
src/client/Microsoft.Identity.Client/IClientApplicationBase.cs
src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs
src/client/Microsoft.Identity.Client/MigrationAid/MigrationAid.cs
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs

Fixes #2872
Summary vs summary. Looks like docs.microsoft.com is case sensitive

Correct XML summary element casing

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/Internal/ClientCredentialWrapper.cs
src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #2863 
Add async delegate. 
Note to self: always go for async + cancellation token.

Add async delegate for WithClientAssertion

---

Directory.Build.props
src/client/Microsoft.Identity.Client/Internal/ClientInfo.cs
src/client/Microsoft.Identity.Client/Internal/IdToken.cs
src/client/Microsoft.Identity.Client/Kerberos/KerberosSupplementalTicketManager.cs
src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/BrokerKeyHelper.cs
src/client/Microsoft.Identity.Client/Utils/Base64UrlHelpers.cs
tests/Microsoft.Identity.Test.Performance/Base64Encode.cs
tests/Microsoft.Identity.Test.Performance/Program.cs

Fixes # .
Copy UrlEncoders from Wilson
Add     `<LangVersion>latest</LangVersion>` - this will allow us to use newer language features, but we are still bound to c# 7.3 due to net45 and netstandard1.3 ... Once we stop supporting those, we can move to C# 8 or 9 consistently. 
**Testing**
perf test. existing ut cover functionality
Encode operations are 2x+ faster and consume 1/2 memory. Decode operations are more or less the same.
|              Method |           Job |       Runtime | Server |    StdDev |     Median | Allocated |
|-------------------- |-------------- |-------------- |------- |----------:|-----------:|----------:|
| Encoding_String_Old |    .NET 4.7.2 |    .NET 4.7.2 |  False |  10.17 ns | 1,080.9 ns |    2006 B | …

Optimization of Base64UrlEncode operations based (copy from Wilson)

---

src/client/Microsoft.Identity.Client/Instance/AadAuthority.cs
src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes # .
fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2887
Log error when common or organizations were used for client credential flow
**Testing**
unit test
negligable

Log error when common or organizations were used for client credential flow

---

tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
tests/Microsoft.Identity.Test.Performance/AcquireTokenForOboCacheTests.cs
tests/Microsoft.Identity.Test.Performance/Program.cs
tests/Microsoft.Identity.Test.Performance/TokenCacheTests.cs

Fixes # .
Related to #2881, which also has the test results.. Just adding perf tests as a separate PR.
Tests for `AcquireTokenForOBO`, `GetAccount`, `GetAccounts`, `AcquireTokenSilent`, `RemoveAccount`. Also adds some helper methods.
**Testing**

Add performance tests for user cache

---

src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalServiceExceptionFactory.cs
src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
src/client/Microsoft.Identity.Client/OAuth2/Throttling/ThrottleCommon.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Unit/OAuthClientTests.cs
tests/Microsoft.Identity.Test.Unit/Throttling/ThrottlingAcceptanceTests.cs

Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2855
Adding better message for retry after error for client credential request
**Testing**
Unit test
none

Adding better message for retry after error for client credential request

---

build/template-build-and-run-all-tests.yaml
src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentRequest.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSPlatformProxy.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/AbstractPlatformProxy.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/PlatformProxyFactoryTests.cs

Fixes # 2897.
Issue about broker failure in iOS
Merging hotfix back in the master
**Testing**
As per the Hotfix branch
NA

Hot fix 4.36.2

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/client/Microsoft.Identity.Client/AppConfig/InternalMemoryTokenCacheOptions.cs
src/client/Microsoft.Identity.Client/MigrationAid/TokenCache.MigrationAid.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/Platforms/Android/AndroidPlatformProxy.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSPlatformProxy.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/AbstractPlatformProxy.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedAppTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedUserTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/TokenCache.Notifications.cs
src/client/Microsoft.Identity.Client/TokenCache.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/AppAccessorWithPartitionAsserts.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/AppConfigTestExtensions.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/UserAccessorWithPartitionAsserts.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSerializationTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/InMemoryPartitionedTokenCacheAccessorTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/InternalCacheOptionsTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/PlatformProxyFactoryTests.cs
tests/devapps/WebApi/Controllers/FlatCacheController.cs
tests/devapps/WebApi/Controllers/OboController.cs
tests/devapps/WebApi/Controllers/PrototypeController.cs
tests/devapps/WebApi/Controllers/WilsonLruCacheController.cs
tests/devapps/WebApi/Misc/AbstractPartitionedCacheSerializer.cs
tests/devapps/WebApi/Misc/InMemoryPartitionedCacheSerializer.cs

Fixes #2849
**Testing**
ut + perf
**Performance impact** No difference
|                                    Method | Tenants | TokensPerTenant |     Mean |     Error |    StdDev |    Median |       Min |      Max | Allocated |
|------------------------------------------ |-------- |---------------- |---------:|----------:|----------:|----------:|----------:|---------:|----------:|
| AcquireTokenForClient_Singleton_TestAsync |    1000 |            1000 | 1.029 ms | 0.0878 ms | 0.2546 ms | 0.9091 ms | 0.7325 ms | 1.746 ms |    185 KB |
|                          Method | Tenants | TokensPerTenant |     Mean |    Error |   StdDev |   Median |      Min |        Max | Allocated |
|-------------------------------- |-------- |---------------- …

Add static cache options

---

src/client/Microsoft.Identity.Client/Http/HttpClientConfig.cs
src/client/Microsoft.Identity.Client/WwwAuthenticateParameters.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
tests/Microsoft.Identity.Test.Unit/TestBase.cs
tests/Microsoft.Identity.Test.Unit/WwwAuthenticateParametersTests.cs

- Added optional `cancellationToken` to `CreateFromResourceResponseAsync()`
- Used `is null`, `is object` for null checks
- Used `string.Equals()` with `StringComparison.OrdinalIgnoreCase` for string comparison
- Removed no-op `try/catch` that does nothing but erases the exception stack trace
**Testing**
- Refactored unit tests
- Added integration test to call [ARM](https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/get)
Will slightly improve the performance of the helper methods.

Refactored WwwAuthenticateParameters

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/GetAuthorizationRequestUrlParameterBuilder.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs

Fixes # .
#2919 
- Replacing CCS by "backup authentication system" in docs, comments
- Updated Wiki Page : [https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Backup-Authentication-System](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Backup-Authentication-System)
- Couldn't find any aka/ms links or reference to the old CCS wiki page
Closes #2919

updating CCS naming

---

.github/pull_request_template.md

Updates PR template to remind to mention if any manual testing is needed during release process.

Mention manual release testing needed in PR template

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs
tests/Microsoft.Identity.Test.Unit/ExceptionTests/ExperimentalFeatureTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #2920 
- Adding experimental flag to the hybrid SPA feature.
- Added an experimental feature test for the flag.
- updated other tests for hybrid spa to use .WithExperimentalFeatures().
**Testing**
unit and integration.
none.

Adds experimental flag to Hybrid SPA feature

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCache.Serialization.cs
src/client/Microsoft.Identity.Client/TokenCache.cs
src/client/Microsoft.Identity.Client/TokenCacheExtensions.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/InternalCacheOptionsTests.cs

This will enable `Microsoft.Identity.Web.TokenCache` to migrate the uses of `InMemoryCache` to MSAL's static cache.

Expose SetCacheOptions at the ITokenCache level

---

src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
tests/devapps/NetCoreTestApp/Program.cs

Fixes #3024
Fix multi-threading issue in telemetry.
Add [multi-threading run option](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/7cfb2a9de4613f6ccc0a597ca1c2c9fa012741ce/tests/devapps/NetCoreTestApp/Program.cs#L123) to NET Core console dev app.
**Testing**
Manual with NetCoreTestApp + existing tests.

Fix multi-threading issue in telemetry

---

src/client/Microsoft.Identity.Client/AppConfig/PopAuthenticationConfiguration.cs
src/client/Microsoft.Identity.Client/AuthScheme/PoP/IPoPCryptoProvider.cs
src/client/Microsoft.Identity.Client/AuthScheme/PoP/PoPAuthenticationScheme.cs
tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.NetCore.csproj
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/Microsoft.Identity.Test.Integration.NetFx.csproj
tests/Microsoft.Identity.Test.Integration.netfx/MsalExtensions.cs

Fixes # 
TBD
SAL likes to create the Singed Http Request envelope separately, so MSAL should just give the assertion from the cache.
**Testing**
integration test 

[SAL] Add support for POP tokens without signed http envelope

---

src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
tests/Microsoft.Identity.Test.Integration.Win8/Microsoft.Identity.Test.Integration.Win8.csproj
tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
tests/devapps/NetFxConsoleTestApp/NetFxConsoleApp.csproj

Moves reference of System.Windows.Forms to only be applicable for NetDesktop and not NetCore.
The following warning exists in several places in the merge validation builds.
"##[warning]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2203,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Windows.Forms". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors."
**Testing**
Validated unit tests locally.

Fix warnings in merge validation build for System.Windows.Forms

---

src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj

Internal improvement
Set `MSAL_DESKTOP_ONLY_DEV` and msbuild will ignore the mobile targets and net45. No more need to comment targets out, just set an env variable (and restart VS).

[Internal] Ignore mobile and legacy target on env variable

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs
tests/Microsoft.Identity.Test.Unit/ExceptionTests/ExperimentalFeatureTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #2920 
- Removed experimental flag from the hybrid SPA feature.
- Removed the experimental feature test for the flag.
- Updated hybrid spa tests and removed .WithExperimentalFeatures().
**Testing**
unit and integration.
none

Removes experimental flag from Hybrid SPA feature

---

src/client/Microsoft.Identity.Client/Platforms/Features/DesktopOS/WindowsNativeUtils.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs

Fixes #2289  
- Use AAD plugin's account selector if authority is AAD only 
- But not for msa-pt
- Use "select_account" prompt unless the user set smth else.
**Testing**
ut
part of AcquireTokenInteractive, which is not perf sensitive.

#2289 Do not show account picker if authority is AAD only

---

tests/CacheCompat/CommonCache.Test.MsalJava/pom.xml

Fixes # 
#3098 
Update pom.xml for cache compat tests for java to pull latest version for gson.
**Testing**

Update to point to latest version of gson

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes # 
GetAccountAsync fix by checking for null on accountId
**Testing**
unit tests
n/a

GetAccountAsync fix by checking for null on accountId

---

src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/Internal/Broker/BrokerInteractiveRequestComponent.cs
src/client/Microsoft.Identity.Client/Internal/Broker/IBroker.cs
src/client/Microsoft.Identity.Client/Internal/Broker/NullBroker.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Silent/BrokerSilentStrategy.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidAccountManagerBroker.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerFactory.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidContentProviderBroker.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/iOSBroker.cs
src/client/Microsoft.Identity.Client/PublicClientApplication.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/PublicClientApplicationBuilderTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/WamGetAccountsTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/SilentRequestTests.cs

Fixes #2836 
WAM is not supported in pure ADFS environments. We do not get an ID token from WAM for ADFS scenarios, hence we are not able to properly form the TokenResponse object and also caching fails. TO fix the issue, we are falling back to browser if the Authority is set as ADFS. 
**Testing**
Unit Tests, Manual Testing. For Release 4.41.0 this needs a manual testing on an ADFS 2019 domain joined machine
N/A

WAM Fix for ADFS 2019

---

src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs

Fixes #3130 
if no tokens are in the cache, suggested expiry = NOW
**Testing**
unit
1 extra int comparison will not degrade perf

Fix for #3130 - if no tokens are in the cache, suggested expiry = null

---

src/client/Microsoft.Identity.Client/WwwAuthenticateParameters.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/WwwAuthenticateParametersTests.cs

Fixes #3144 
- WwwAuthenticateParameters should not expose Resource/Scopes
- Marked both resource and scopes property in WwwAuthenticateParameters as Obsolete
- Added notes to bug [3144](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3144) to update docs 
**Testing**
- unit, integration
- created a test app based on suggested usage, [How to - use the WwwAuthenticateParameters class](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WWW-Authenticate-parameters#how-to---use-the-wwwauthenticateparameters-class), found scopes will be null if we marked Resource as obsolete. Per discussion marking scope as obsolete. 
none. we no longer calculate scope based on the resource that …

WwwAuthenticateParameters should not expose Resource/Scopes

---

src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/InteractiveRequest.cs

Fixes: Update to the PR #3141 for #2524 
When user selects .WithMultiCloudSupport(true) and calls interactive request we need to add the extraQueryParam to the request. But if the query param is already added, then ExtraQueryParam.Add() will throw an exception. So checking if the key exists before adding it.
**Testing**

Add instance_aware extra query param only if one does not exist

---

src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/Win32VersionApi.cs

Adding `ExactSpelling = true` on [DllImport("ntdll.dll"] to fix UWP packaging warning `MCG : warning MCG0007: Unresolved P/Invoke method 'ntdll.dll!RtlGetVersion' for method 'System.Int32 `
Fixes #3184 
Adding `ExactSpelling = true` on [DllImport("ntdll.dll"] 
**Testing**
- Manual testing of UWP package publishing for all supported platforms. 
- WAM testing on all supported OSs
none

Adding `ExactSpelling = true` on [DllImport("ntdll.dll"] 

---

build/template-pack-and-sign-all-nugets.yaml

This reverts commit 4b194f533bf74606f5a456ea82429adb68bc7a3a which brakes the one branch release build. Need to do this in the meantime to make OneBranch build work again. Fix to make oneBranch and legacy release build work together coming shortly
Fixes # 
Fixes OneBranch build
revert commit 4b194f533bf74606f5a456ea82429adb68bc7a3a.
**Testing**

Revert "Fix path variables. (#3202) to fix OneBranch release"

---

src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IWebAccountProviderFactory.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WebAccountProviderFactory.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs

Fixes #3217
Replace env/organizations with env/common when we can reliably detect an AAD interactive login. 
**Testing**
unit
manual
1. {normal app, msa-pt app} with authority {global cloud, sovereign cloud}/organizations logging in an {aad/msa} account, {silent, interactive}
(16 tests)
2. log in the default account {aad, msa}, {silent, interactive}  with {normal, msa-pt} app (8 tests) 
only string comparisons

Add a workaround for PRT update failure on /organizations

---

src/client/Microsoft.Identity.Client/Platforms/Features/DesktopOS/Win32VersionApi.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DesktopOsHelper.cs

Fixes #3184
UWP does not provide a mechanism to tell if machine is running Win Server 2016, so we just assume WAM is present on all UWP compatible OSes. 
On UWP, it seems that we cannot have any "illegal" DllImport statetems in the code, even if these are not in the call path.

Fix for UWP packaging

---

src/client/Microsoft.Identity.Client/Cache/ITokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/Platforms/Android/AndroidTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedAppTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedUserTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/TokenCache.cs
src/client/Microsoft.Identity.Client/Utils/CollectionHelpers.cs
src/client/Microsoft.Identity.Client/Utils/EnumerableExtensions.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/AppAccessorWithPartitionAsserts.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/UserAccessorWithPartitionAsserts.cs
tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
tests/Microsoft.Identity.Test.Performance/Program.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs

Fixes #3178
- Replace `IReadOnlyList` with `List` in accessor and filtering methods (`RemoveAll` is in concrete `List` implementation).
- In `FilterWithLogging`, replace `list = list.Where(predicate).ToList();` with `list.RemoveAll(e => !predicate(e));`
- Add a boolean parameter whether to filter on the current list or create a new one.
- In other methods, replace `Where` with `RemoveAll` and reverse filtering predicate (since instead of keeping the items based on a filter, we now remove items based on the opposite of that filter).
**Testing**
Existing tests.
Tested with 1 tenant and 10K tokens in cache (tenants don't matter in this scenario). About 40% reduction in memory allocated for client, OBO, and silent calls. Perf …

Reuse lists in token cache filtering logic.

---

src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs

Fixes #3248  
**Testing**
Manual test only. We don't have infrastructure to run integration tests and the WebAccount objects used are not testable.

Fix for #3248 - use the correct plugin to sing out

---

README.md
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3147 actually references broken XML in Azure SDK, that XML comment in MSAL works.
Created PR https://github.com/Azure/azure-sdk-for-net/pull/28128 to fix it there.
- Minor fix to SuggestedCacheKey comment.
- Add Msal.Desktop NuGet icon in Readme.

Minor fix to SuggestedCacheKey comment and update NuGet icon in Readme.

---

tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs

Fixes # 
Test failures
Lab Vault access cert was auto renewed, since we refer using thumbprints builds are broken. 
**Testing**
CI
None

Lab Access Cert update - Fix for CI test failures

---

src/client/Microsoft.Identity.Client/Instance/Discovery/KnownMetadataProvider.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/AuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/AuthorityAliasesTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/InstanceProviderTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs

Fixes # 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3265
Adding PPE to known instance discovery metadata
**Testing**

Adding PPE to known discovery endpoints

---

src/client/Microsoft.Identity.Client/Http/HttpManager.cs
src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs

Fixes #3283 
When auth is cancelled, throw TaskCancelledException instead of converting it to TimeoutException
**Testing**
Updated an existing unit test
None

Throw TaskCancelledException when request gets cancelled.

---

src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopCryptographyManager.cs

Fixes #3324 
Disable the cert size check. We only perform it on .NET classic, which is a deprecated fwk. AAD enforces everything related to cert security, this is not an SDK concern.

Disable cert size check

---

src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs

Fixes # 3327
Accounts for null values
**Testing**
Added unit tests
None

CreateFromiOSBrokerResponse is safer now

---

tests/devapps/WebApi/Controllers/AsyncTestController.cs
tests/devapps/WebApi/MockHttp/MockHttpClientFactory.cs

- Added controller with actions to test with and without wait.
- Added ability to add delay to mocked Http client.
**Testing**
- Did a few test runs on my machine using [bombardier](https://github.com/codesenberg/bombardier) tool. Test results below using 500ms delay in mocked HTTP call. Seems like a method with `GetAwaiter().GetResult()` is faster than with using `await` but did result in a bit more timeout exceptions. This test could also probably be updated with something like adding a count of threads in a pool or maybe increasing the delay.
Each test run is 1m0s using 125 connection(s). The `others` error category is timeout exceptions, which is also probably why 99% numbers are outliers.
**bombardier -d 60s -l …

Test with and without await

---

build/template-android-appcenter-tests.yaml

Use new Android device set (Pixel 6 Pro Android 12, Pixel 5 Android 11) that covers the 2 latest OSs.

Use new Android device set for App Center tests

---

src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests2.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/ConfidentialAppSettings.cs
tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/FociTests.cs
tests/Microsoft.Identity.Test.LabInfrastructure/KeyVaultSecretsProvider.cs
tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
tests/Microsoft.Identity.Test.LabInfrastructure/LabServiceApi.cs
tests/Microsoft.Identity.Test.LabInfrastructure/LabUserHelper.cs
tests/Microsoft.Identity.Test.LabInfrastructure/Microsoft.Identity.Test.LabInfrastructure.csproj

- Replace obsolete Microsoft.Azure.KeyVault with Azure.Security.KeyVault.* libraries
- As long as the integration tests pass, this seems like a low risk PR. Only test projects changed.
**Testing**
- We'll see when Integration tests run :)

Replace obsolete KeyVault library

---

Directory.Build.props
tests/Microsoft.Identity.Test.Common/Microsoft.Identity.Test.Common.csproj
tests/Microsoft.Identity.Test.LabInfrastructure/Microsoft.Identity.Test.LabInfrastructure.csproj
tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml.cs
tests/devapps/XamarinDev/XamarinDev/CachePage.xaml.cs

Merges https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3444 into main after tests are run.

Remove some build warnings (#3444)

---

tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs

Fixes # 
Clearing the cache for the WAM perf test so the calls are made to the broker every time
**Testing**
used the app 
none

WAM Dev app Perf test update

---

src/client/Microsoft.Identity.Client.Desktop/DesktopExtensions.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenSilentParameters.cs
src/client/Microsoft.Identity.Client/AppConfig/AssertionRequestOptions.cs
src/client/Microsoft.Identity.Client/AuthScheme/PoP/JWKConstants.cs
src/client/Microsoft.Identity.Client/Cache/CacheImpl/ICacheSerializationProvider.cs
src/client/Microsoft.Identity.Client/Instance/Region/RegionAutodetectionSource.cs
src/client/Microsoft.Identity.Client/Instance/Region/RegionOutcome.cs
src/client/Microsoft.Identity.Client/IntuneAppProtectionPolicyRequiredException.cs
src/client/Microsoft.Identity.Client/MigrationAid/MigrationAid.cs
src/client/Microsoft.Identity.Client/Platforms/Features/DesktopOS/Kerberos/TicketCacheWriter.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IWebTokenRequestResultWrapper.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WebTokenRequestResultWrapper.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/win32/Splash.cs
src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/win32/Win32Window.cs
src/client/Microsoft.Identity.Client/Platforms/netdesktop/Http/EndpointCacheKey.cs
src/client/Microsoft.Identity.Client/Platforms/netdesktop/Native/ICngAlgorithm.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/NullLegacyCachePersistence.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/PKeyAuthConstants.cs
src/client/Microsoft.Identity.Client/json/.editorconfig

Working on https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2912
Not the most glamurous, but reduces analyzer warnings :)

Unify licenses for IDE0073 warning

---

src/client/Microsoft.Identity.Client/Internal/Constants.cs

Fixes #1777
Increase the PKCE Code Verifier size from 32 to 96 bytes. See #1777

Increase PKCE Code Verifier Size

---

README.md

.NET Standard was upgraded in the last version, but the README still states 1.3

Update .NET Standard from 1.3 to 2.0 in README

---

tests/CacheCompat/CommonCache.Test.MsalJava/CommonCache.Test.MsalJava.csproj
tests/CacheCompat/CommonCache.Test.MsalNode/CommonCache.Test.MsalNode.csproj
tests/CacheCompat/CommonCache.Test.MsalPython/CommonCache.Test.MsalPython.csproj
tests/Microsoft.Identity.Test.Integration.Win8/Microsoft.Identity.Test.Integration.Win8.csproj
tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
tests/devapps/WAM/NetDesktopWpf/App.config
tests/devapps/WAM/NetDesktopWpf/NetDesktopWpfWAM.csproj

Does it make sense to unifi the .NET Framework Version that's used? most seem to be using .NET 4.8 already, but there are a few "strays"

Unifi/Upgrade NetFramework for Tests

---

src/client/Microsoft.Identity.Client/Platforms/uap/DispatcherTaskExtensions.cs

Another one from #2912 bites the dust.
Suppressing the warning as all exceptions are handled

Suppress warning as all exceptions are handled properly

---

src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs

Fixes #3585
Add MSALRuntime TelemetryData to verbose logging when an exception is thrown
**Testing**
Dev Apps
none

Add MSALRuntime TelemetryData to verbose logging when an exception is thrown

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs

Fixes #3612 
Fixes a bug where netstandard2.0 support was dropped for Interop. [See 3067](https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/3067)
**Testing**
Dev Apps
None

Update Microsoft.Identity.Client.NativeInterop reference to 0.12.1

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj

Fixes # [Bug 1858419](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1858419) [#3604](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3604) [3612](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3612)
Update to Microsoft.Identity.Client.NativeInterop Version 0.12.2, this fixes a few msal runtime bugs 
- [Bug 1858419](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1858419): [Tracking] Error when calling SignInInteractively twice
**Testing**
Dev Apps (WPF, Net Core, Net FWK)
**More on testing :** Tested with the WPF app where the 2nd interactive request will fail with the "Unexpected exception while waiting for accounts control to finish: '(pii)'" …

Update Microsoft.Identity.Client.NativeInterop to Version 0.12.2

---

CHANGELOG.md

**Updated Changelog for MSAL 4.46.2**
[Feature Request] WAM Authentication Library Should Support .NET 4.5 for Back Compatibility. See [#3539](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3539)
Log exceptions which are not converted to MsalExceptions to telemetry. See [#3547](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3547)
[Bug]Authenticator Factory has already been started. See [#3604](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3604)
[Bug] MSAL.NativeInterop only targets .net fwk. See [#3612](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3612)
Fixes #
changelog update
**Testing**
N/A
N/A …

Updated Changelog for MSAL 4.46.2

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryClientTests.cs

Fixes #
Move .WithTelemetryClient() api to ConfidentialCLientApplicationBuilder
Move .WithTelemetryClient() api to ConfidentialCLientApplicationBuilder
**Testing**
Updated the unit tests

Move the api for ITelemetryClient to Confidential Client app

---

src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidContentProviderBroker.cs
tests/Microsoft.Identity.Test.Common/Mocks/MsalMockHelpers.cs
tests/Microsoft.Identity.Test.Unit/Throttling/ThrottlingAcceptanceTests.cs
tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
tests/devapps/WAM/NetFrameworkWam/Form1.cs

Fixes #3654 
- checks if user passes scopes in the request. MSAL Runtime needs scopes to be passed. Else users will hit this issue
`GlobalExceptionHandler: Status: ApiContractViolation
Context: (pii)
Tag: 0x2039c1cb`
- few dev app fixes to test this 
- typos
- more logging
**Testing**
Dev Apps
none

[WAM Broker] Check if scopes are passed when broker is invoked

---

src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj

Remove net6 target from MSAL and unit tests, instead of reverting the whole code base. Since SUPPORTS_SYSTEM_TEXT_JSON flag is only added for net6, the code paths for other targets are unchanged. Left net6 target in integration tests, but it'll run using netcoreapp2.1 MSAL binary.

Remove net6 target

---

src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs

Fixes #3654 
Fix for empty/null scopes. HasScopes does return true when empty scopes are passed but works for null scopes.  
This fixes the user issue 
`GlobalExceptionHandler: 
Status: ApiContractViolation
Context: (pii)`
**Testing**
Dev Apps
none

Fix for empty scopes. HasScopes does return true when empty scopes are passed

---

build/template-publish-packages-and-symbols.yaml

Fixes #3689 
Adding a PublishNugetAndSymbols Build Variable check on Task `'Publish packages to VSTS feed'` and on `'Publish symbols'`
**Testing**
none
n/a

Adding a PublishNugetAndSymbols Build Variable

---

src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs

Fixes #
Hide `WithAuthority` methods.
**Testing**

Soft deprecate WithAuthority on request level

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj

Fixes #
Setting broker and desktop AssemblyVersion to a pre-released version. This the version we use in the client project as well. Our build pipeline sets the `MsalClientSemVer` but if it is not set then `4.7.1` will be used. 
**Testing**
none
none

Setting broker and desktop AssemblyVersion to a pre-released version

---

src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs

Fixes #3699
throwing when MSAL runtime init fails
**Testing**
Dev App
none

WAM - throw when msalruntime.dll is not found

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj

Fixes #
Update NativeInterop to 0.13.0 in Broker project. This will fail in the PR till we publish the Interop to NuGet
**Testing**
Dev Apps
None

Update NativeInterop to 0.13.0 in Broker project

---

src/client/Microsoft.Identity.Client/Extensibility/AcquireTokenForClientBuilderExtensions.cs

Fixing a typo in the public API `WithProofOfPosessionKeyId`

Fixing a typo in the public API `WithProofOfPosessionKeyId`

---

tests/CacheCompat/CommonCache.Test.MsalJava/pom.xml

Moving to use latest msal4j library for cache compatibility tests, this will ensure we always consume the latest MSAL Java release. 
During MSAL release we found that we were using an older version of the msal4j that had some issues. This will help us test against the latest msal4j as they fix and release newer versions

Use Latest msal4j library for cache compatibility tests

---

src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryClient/MsalTelemetryEventDetails.cs
src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryConstants.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryClientTests.cs

Fixes #
#3745 
Log MSAL version
**Testing**

Log MsalVersion to ITelemetryClient

---

src/client/Microsoft.Identity.Client/Internal/Requests/ByRefreshTokenRequest.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs

Fixes #3736
[[Bug] Incorrect HomeAccount details populated in AuthenticationResult of AcquireTokenByRefreshToken](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3736)
Adding client info to IByRefreshToken request
**Testing**
Integration test
N/A

Resolving issue with IByRefreshToken

---

src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
tests/devapps/WAM/NetFrameworkWam/Form1.cs

Fixes : #3743 
With the new broker, ATS with loginHint fails with a Null Reference Exception. When we do a silent call with the new broker we need to pass an account. This works when we call ATS with the IAccount overload. With login_hint the acquireTokenSilentParameters.Account comes back as null. Using authenticationRequestParameters.Account instead.
```cs
// Fails with NRE
var result2 = await app.AcquireTokenSilent(scopes, loginHint).ExecuteAsync();
Console.WriteLine(result2.AccessToken);
```

Broker Silent NRE

---

src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs

Fixes #3769
Add check for OS account in authority creation logic
**Testing**
Tested manually.
Added tests.
N/A

NRE fix in authority creation logic when using ATS with OS account.

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
tests/devapps/WAM/NetFrameworkWam/Program.cs

Fixes #
[Internal tracking item VS#1988070)](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1988070)
- Updated to Microsoft.Identity.Client.NativeInterop 0.13.2, that fixes a bug around ORG workaround. ESTS fixed the issue and MSAL Runtime removed the local fix. This fixes an issue with getting AAD account token in MSA-PT scenario
- Providing Broker options header text to Interop that will add a title to the AAD Account picker (works only on non-admin mode). Bug [2159876](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2159876), is tracking a fix for admin mode header title
**Testing**
Dev App
None

Broker : Updating to Interop 0.13.2 and passing Broker Options Header text to Interop

---

tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs

Fixes #3809
Using the lab app for integration tests. The lab app needed an updated redirectURI and the for-cca-testing certificate. I will also add comments to the test on which lab is hosting this app, so it is easier to update the app when the next cert rollover happens 
**Testing**
CI
none

Update ConfidentialClientAuthorizationTests.cs to use lab app

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs

To fix a GC issue : Managed Debugging Assistant 'CallbackOnCollectedDelegate'  A callback was made on a garbage collected delegate of type 'Microsoft.Identity.Client.NativeInterop!Microsoft.Identity.Client.NativeInterop.API+MSALRUNTIME_LOG_CALLBACK_ROUTINE::Invoke'.

Update Broker to use Interop 0.13.3

---

src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs

Fixes #
- disabling runtime logger by not passing the log callback delegate from broker
- Verified that logger is not initialized after removing the code using the Dev App (NetDesktopWinFormsWAM)
- Minimal amount of code removal so it will be easier to plugin the feature for the next release
- updated the failing tests (WamUsernamePasswordRequestWithPOPAsync/WamUsernamePasswordRequestAsync) by commenting it. 
**Testing**
NetDesktopWinFormsWAM Dev App 
should improve perf for new broker as we are not logging broker messages anymore

Disable runtime logging from new preview broker

---

LibsAndSamples.sln
build/policheck_exclusion.xml
build/template-build-and-run-all-tests.yaml
build/template-postbuild-code-analysis.yaml
build/template-prebuild-code-analysis.yaml
build/template-publish-analysis-and-cleanup.yaml
build/template-run-integration-tests.yaml
build/template-run-unit-tests.yaml
build/template-sign-binary.yaml

- Update analysis build tool versions
- Exclude Newtonsoft code from Policheck
- Fix Policheck warnings

Update analysis build tools versions (per warnings)

---

LibsAndSamples.sln
build/template-postbuild-code-analysis.yaml
build/template-publish-analysis-and-cleanup.yaml
build/tsaConfig.json

- Update Roslyn analyzers task version and input
- Update TSA upload task version and use config file (required) instead of input parameters
All of the compliance tasks need to be on the latest version to be able to work together. The newer and older versions don't seem to be backwards compatible.

Update TSA upload and Roslyn analyzer tasks

---

src/client/Microsoft.Identity.Client/AuthenticationResult.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationResultTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTestsWithB2C.cs
tests/devapps/KerberosConsole/Program.cs

Fixes #1377
Not used. Funny how the comments mention that app developer must configure this via `ClientApplicationBase` but no such config exists.

Deprecate extended expiry API

---

build/template-build-and-run-all-tests.yaml
build/template-prebuild-code-analysis.yaml

The latest version of compliance tool was updated, and it looks and tries to install .NET 6 instead of .NET Core 3.1. After installing it can't find dotnet path. So adding this install task explicitly fixes the issue.

Add dotnet task for prebuild compliance tasks.

---

build/template-build-and-run-all-tests.yaml

Container was added as an experiment (per Travis); can be removed, as it adds like 5 min to build time. We only have it for the PreBuild stage and the compliance tasks there don't use it.

Remove container from build

---

src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs

Fixes #3685 
- Was wrongly passing SignOutResult object to ThrowExceptionFromWamError(), the exception handler only accepts authResult object
- Fixes the APIContractViolation error during signout 
**Testing**
Dev App
None

Fix WAM exception thrown during sign out for the new preview broker 

---

src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs

Fixes #3301
In majority of cases, MSALRuntime will know which identity provider to invoke based on the authority. However, in the consumer pass through scenario where the authority is /organizations or /<tanent_id> but the application accepts MSA, passing the account_hint itself will not able to disambiguate the identity provider. 
Hence, if there is an account_hint in the SignInInteractively, MSAL need to pass this additional key value pair if the identity provider is MSA:
````
{"msal_identity_provider":"msa"}
````
If this key value is missing or the value is not msa, the account_hint will be treated as AAD by default.  
If the account was signed in before and has an account object in MSAL C++ (By calling ReadAccountById), the token acquisition path …

Bypass the Accounts Control when there is an account hint

---

tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
tests/Microsoft.Identity.Test.Unit/CryptographyTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs

Fixes ##[error]1. RoslynAnalyzers Error IA5352 - File: [tests/Microsoft.Identity.Test.Unit/CryptographyTests.cs](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1051408&view=logs&j=9906ff93-67e4-5c55-442d-8f18d4fd3348&t=dd131459-e75d-50d9-3ace-869ae72cdd79&l=94). Line: 29. Column 81.
RoslynAnalyzers: Rule: IA5352 (Do Not Misuse Cryptographic APIs ). http://aka.ms/IA5352-   Do Not Use Plain Password in PKIs
**Testing**
Build
none

Roslyn : Do Not Use Plain Password in PKIs

---

src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs

Fixes #3929
- Account switch comes back as error from MSALRuntime but with a valid token for the new account
- Check account switch status and process the access token instead of throwing an unknown error 
**Testing**
Dev App. 
none

WAM - Let user perform account switch

---

src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj

Fixes 
- Update Broker to use Interop 0.13.5. This will consume the latest interop package
- ***NOTE*** this will fail till the Interop is updated in NuGet with version 0.13.5 (NuGet published now)
**Testing**
Dev Apps
None

Update Broker to use Interop 0.13.5

---

src/client/Microsoft.Identity.Client.Broker/BrokerExtension.cs
src/client/Microsoft.Identity.Client.Desktop/DesktopExtensions.cs
src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
src/client/Microsoft.Identity.Client.Desktop/WamExtension.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/PublicClientApplicationBuilderTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/RuntimeBrokerTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationSchemeTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
tests/devapps/NetCoreTestApp/Program.cs
tests/devapps/WAM/MSIX/WPF/MainWindow.xaml.cs
tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml.cs
tests/devapps/WAM/NetFrameworkWam/Form1.cs
tests/devapps/WAM/UWPWam/MainPage.xaml
tests/devapps/WAM/UWPWam/MainPage.xaml.cs
tests/devapps/WAM/UWPWam/UWP standalone WAM.csproj

This reverts commit 3d20374e4bd9ed621119b917c51e4c1eb68d3032.
Fixes #
Revert broker changes
Revert the last
**Testing**
Automated tests
NA

Revert "RuntimeBroker is now default broker for non-UWP (#3976)"

---

src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/OBOTests.cs

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3825
Enabling obo request to acquire new token if user cached assertion is different from the one provided.
This is done by ensuring `InitiateLongRunningProcessInWebApi` always goes to get a new token rather than using what is already in the cache for a specified cache key.
**Testing**
Unit

LongRunning OBO cache fix for different user assertions

---

Directory.Build.props
src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
src/client/Microsoft.Identity.Client/Extensibility/ConfidentialClientApplicationExtensions.cs
src/client/Microsoft.Identity.Client/ILongRunningWebApi.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests2.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/OBOTests.cs

Related to #3913, #3973
- Suggestion to rename `StopLongRunningWebApiAsync` to `StopLongRunningProcessInWebApiAsync` to match `InitiateLongRunningProcessInWebApi` and `AcquireTokenInLongRunningProcess`.
- Update service principal long-running OBO test.
- Fix comments.
- Set analyzers version to wildcard, so latest one is always used.

Update a service principal long running OBO test. Rename StopLR API. Update analyzers. Fix comments.

---

Directory.Build.props

Update to Microsoft.Identity.Client.NativeInterop version 0.13.7
- fixes packaging issue with arch targeted specific projects 
- this version of the interop loads msalruntime from default search order in addition to the custom search 
- this version re-introduces the build.props file

Update to Microsoft.Identity.Client.NativeInterop version 0.13.7

---

build/template-run-integration-tests.yaml
build/template-run-unit-tests.yaml
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs
tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj

Adds back running netcore3.1 unit and integration tests.
Fixed some broker tests to call the correct Msal Runtime broker API.
Created issue #4052 as a follow up improvement to this.

Add back netcore tests.

---

tests/Microsoft.Identity.Test.LabInfrastructure/CertificateHelper.cs

Test only. 
On my machine, I have 4 certs with the same name. Current logic loads a random one.

Fix test loading cert by name when multiple certs with same name exist

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs

Token protection (sometimes referred to as token binding in the industry) attempts to reduce attacks using token theft by ensuring a token is usable only from the intended device. When an attacker is able to steal a token, by hijacking or replay, they can impersonate their victim until the token expires or is revoked. Token theft is thought to be a relatively rare event, but the damage from it can be significant.
learn more : [https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-token-protection](https://learn.microsoft.com/en-us/azure/active-directory/conditional-access/concept-token-protection)
In msidlab4 lab, we now have a valid resource (SPO) to test for POP tokens and also a CA Policy for token issuance. AAD will only get a token back for the popUser …

[WAM] Token protection validation with CA Policy

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ManagedIdentityTests.cs

Rerun tests which contain spaces in their names does not work. 
Issue : https://github.com/microsoft/azure-pipelines-tasks/issues/10709

Remove test name with spaces as it fails in re-run

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs

Replace "login.windows.net" with "login.microsoftonline.com"
**Testing**
test
none

Replace "login.windows.net" with "login.microsoftonline.com" in WwwAuthenticateParameters Tests

---

src/client/Microsoft.Identity.Client/AuthenticationResult.cs
src/client/Microsoft.Identity.Client/Cache/Items/MsalAccountCacheItem.cs
src/client/Microsoft.Identity.Client/Internal/IdToken.cs
src/client/Microsoft.Identity.Client/TenantProfile.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Use sub claim if oid is missing

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenOnBehalfOfParameters.cs
src/client/Microsoft.Identity.Client/Extensibility/AcquireTokenOnBehalfOfParameterBuilderExtensions.cs
src/client/Microsoft.Identity.Client/ILongRunningWebApi.cs
src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSerializationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/OBOTests.cs
tests/Microsoft.Identity.Test.Unit/TelemetryTests/HttpTelemetryTests.cs

Fixes #4124
Related to #4111
Adds new API `WithSearchInCacheForLongRunningProcess`.
Only affects `InitiateLongRunningProcessInWebApi`.
When enabled, mimics MSAL 4.50.0 and below behavior - checks in cache for cached tokens.
When disabled (default behavior), doesn't search in cache, but uses the user assertion to retrieve tokens from AAD.
**Testing**
Unit test. Manual.

Add public API to search in cache for Initiate long-running OBO

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ManagedIdentityTests.cs

Fixes #
Disable azure arc tests and add a variable to enable them if needed for release. Disabling them as the infrastructure is not there to run these tests
**Testing**

Disable azure arc tests

---

src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/RuntimeBroker.cs

Minor updates to WAM logging.

---

build/pipeline-perf-tests-automation.yaml
src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
tests/devapps/WAM/UWPWam/MainPage.xaml.cs

INCLUDE_MOBILE_AND_LEGACY_TFM is triggering the Mobile workloads, hence removing it

Remove INCLUDE_MOBILE_AND_LEGACY_TFM from Perf builds

---

build/template-build-and-run-all-tests.yaml

Disable CodeQL in the classic pipeline, since it runs in the other one. Make sure to skip the auto-injected task, since it's unnecessary.

Disable CodeQL

---

tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OnBehalfOfServicePrincipalTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/ConfidentialAppSettings.cs

Fixes #4281.
Updated some of the tests to replace the old tenant (Azure Dogfood) with the new tenant (Azure Control Plane Dogfood).
Ping _alexbat_ for invitation and/or permissions.
**What's not included**
The [OBO tests ](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OnBehalfOfServicePrincipalTests.cs) as they rely on a special configuration of the SPN.
**Testing**
The change touches the tests only.
N/A
N/A

Updated tests after migrating test subscription to new Dogfood tenant

---

src/client/Microsoft.Identity.Client/Instance/AdfsAuthority.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/MsalException.cs
src/client/Microsoft.Identity.Client/PublicClientApplication.cs
src/client/Microsoft.Identity.Client/Utils/EnumerableExtensions.cs
src/client/Microsoft.Identity.Client/json/Utilities/AsyncUtils.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OnBehalfOfServicePrincipalTests.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/CiamAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/RuntimeBrokerTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryClientTests.cs

Fix warnings.

---

src/client/Microsoft.Identity.Client/Internal/Requests/ManagedIdentityAuthRequest.cs
src/client/Microsoft.Identity.Client/ManagedIdentityApplication.cs
src/client/Microsoft.Identity.Client/MsalError.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs

Fixes #4332.
Check for null and empty scopes in managed identity

Check for null and empty scopes in managed identity

---

tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs

Adding Client Capabilities test to CCA App Builder Tests, as there was no test coverage on these.

Add Client Capabilities test to CCA App Builder Tests

---

src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/RuntimeBroker.cs

Fixes #4353 
**Background :** LogEventWrapper helps setting up an event handler for log events from MSALRuntime.
**Fix :** Removing LogEventWrapper call from Interactive methods that gets called from the main `AcquireTokenInteractiveAsync` API call. Since `AcquireTokenInteractiveAsync` API method gets executed first every time when an Interactive request is made, Runtime logger gets invoked once, but then it (LogEventWrapper ) gets invoked again in the subsequent interactive methods. Removing the LogEventWrapper from the subsequent calls fixes the dupe issue. 
**Testing**
Dev App
none

Fix for WAM Runtime error logs duplicated info

---

src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs
src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopCryptographyManager.cs
src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopPlatformProxy.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs

Fixes #4366
Adds one retry when an `RSA.SignData` operation fails. Recreates the RSA key, in case the old one is faulted, try signing again.
**Testing**
Manual tests with multi-threaded requests.
Can't really add unit tests since the code can't be mocked.
Negligible during a successful operation.

Add one retry to assertion signing.

---

Directory.Build.props

Bug [2468329](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2468329)
Bump MSALRuntime Native Interop version to 0.13.12
Bumping Interop version for this fix, [Add check for user canceled in GetTransferToken flow #3710](https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/3710) in msalruntime.

Bump MSALRuntime Native Interop version to 0.13.12

---

src/client/Microsoft.Identity.Client/AuthenticationHeaderParser.cs

Fixes warnings. Seems like with `ineritdoc`, if you add a `param` comment for a missing parameter, you have to add them for all parameters.

Fix comments warnings.

---

src/client/Microsoft.Identity.Client/MsalException.cs
src/client/Microsoft.Identity.Client/MsalServiceException.cs
tests/Microsoft.Identity.Test.Unit/ExceptionTests/MsalExceptionSerializationTests.cs

Fixes #4371
- Adds additional broker exception data to exception de/serialization.
- Added a flag for less escaping in STJ.
- System.Text.Json, by default, escapes more characters than Newtonsoft. This makes broker telemetry, which is a JSON string, less readable (see [doc](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0#minimal-character-escaping) and [doc](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/character-encoding#serialize-all-characters)). Something like: 
```text
"broker_telemetry": "{\u0022additional_query_parameters_count\u0022:\u00220\u0022,\u0022all_error_tags\u0022:\u00229zdfv\u0022,\u0022api_error_code\u0022:\u00220\u0022,\u0022 …
```

Add serialization of broker error data in exceptions

---

CONTRIBUTING.md

Adapted the team contributing guide to the one in MSAL. Did not remove anything from the original MSAL guide as it had a lot of great information, and I think the newest additions plug in nicely.

add to MSAL contributing guide

---

src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentRequest.cs
tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
tests/Microsoft.Identity.Test.Unit/RequestsTests/SilentRequestTests.cs

Fixes #4209
WithBroker = true, interactive token call falls back correctly to browser and completes the flow. With silent token call for the same account, currently there is no fallback to local cache if broker fails to return result. BrokerStrategy can fail for example if the broker is not available in the machine. The fix is to fall back to local cache for silent token call as well similar to interactive call. 
**Testing**
The existing unit tests were modified to account for the new bahavior
Ran through the scenario manually in the WinForms test app and verified its working as expected
None
None

Fall back to local cache if broker fails to return result for silent token call 

---

src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
src/client/Microsoft.Identity.Client/Instance/AadAuthority.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/AadAuthorityTests.cs

Fixes #4425
Currently MSA passthrough doesn't work as expected for silent token acquisition flows because MSAL.net normalizes /organizations authority using accounts home tenant. This logic made sense for V1 requests, but it breaks MSA passthrough flows using the runtime.  
Stop normalizing /organizations authority for MSA passthrough flows.
**Testing**
Unit and component tests added.
Negligible

Add support for MSA passthrough for silent token acquisition calls through the boker

---

src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryClientTests.cs

Fixes #4414 
Fix the cache level, when in memory cache is used cache level will be L1Cache.
**Testing**
Updated tests to verify

Cache level should be L1 in case of default in memory cache.

---

Directory.Packages.props

Update MSALNativeInterop version to 0.13.14 which has various bug fixes and stability improvements.

Update MSALNativeInterop version to 0.13.14

---

src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/RuntimeBroker.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs
tests/devapps/WAM/NetCoreWinFormsWam/Form1.Designer.cs
tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs

Fixes #4457
Currently Broker flows don't allow bypassing broker cache when option .WithForceRefresh(true) is set. This PR proposes to fix that.
**Testing**
No e2e test infra seem to exist for e2e WAM tests. 
Manual validation was done. Test app has been updated to support this option.
There's possibility that using builder  .WithForceRefresh(true) will result in 2 network calls if the cache is already expired.

Add .WithForceRefresh support for silent broker flows

---

src/client/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
src/client/Microsoft.Identity.Client/Internal/IdToken.cs
src/client/Microsoft.Identity.Client/TokenResponseHelper.cs
src/client/Microsoft.Identity.Client/Utils/ScopeHelper.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/CoreAssert.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/B2CUsernamePasswordIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/UnifiedCacheFormatTests.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/UnifiedSchemaValidationTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/GenericAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/Resources/AADTestData.txt
tests/Microsoft.Identity.Test.Unit/Resources/MSATestData.txt

Fixes #4474 
I verified that I am not touching the hot path (getting token from the cache), the reorder happens on saving token response from HTTP, which is already heavy operation.

Order scopes on save to avoid access token duplication in the cache

---

build/template-pack-and-sign-packages.yaml

We're seeing build failures due to an outdated Java version. The error XA0031 indicates we need Java SDK 11.0 or higher for the Xamarin Android project, hence including it now in the pack and sign step for the legacy builds.

[BUILDS] Add Java SDK Version 11 in packaging step to Resolve Xamarin Build Failure 

---

src/Directory.Build.props
src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
tests/Directory.Build.props
tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.NetCore.csproj
tests/Microsoft.Identity.Test.Integration.netfx/Microsoft.Identity.Test.Integration.NetFx.csproj
tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
tests/devapps/DesktopTestApp/DesktopTestApp.csproj
tests/devapps/FociTestApp/FociTestApp.csproj
tests/devapps/Intune-xamarin-Android/Intune-xamarin-Android.csproj
tests/devapps/Intune-xamarin-ios/IntuneMAMSampleiOS.csproj
tests/devapps/MultiCloudTestApp/MultiCloudTestApp.csproj
tests/devapps/NetFxConsoleTestApp/NetFxConsoleApp.csproj
tests/devapps/WAM/NetDesktopWpf/NetDesktopWpfWAM.csproj
tests/devapps/WAM/NetFrameworkWam/NetDesktopWinFormsWAM.csproj
tests/devapps/WAM/UWPWam/UWP standalone WAM.csproj

Reverts AzureAD/microsoft-authentication-library-for-dotnet#4494 to unblock the release. The one branch release build fails for lang version 12.

Revert "update langVersion to 12"

---

src/client/Microsoft.Identity.Client.Extensions.Msal/Accessors/LinuxKeyRingAccessor.cs
src/client/Microsoft.Identity.Client/WsTrust/MexDocument.cs
tests/Microsoft.Identity.Test.Integration.Win8/DeviceAuthenticationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

less code and faster since it it only on lambda allocation

replace combo of where and FirstOrDefault with only FirstOrDefault

---

src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs

since null checks are inside a if not null for _interactiveParameters.Account

remove redundant null checks in CreateInteractiveRequestParameters

---

src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DeviceAuthHelper.cs

since SingleOrDefault is used above, i assume might not exist in the values ?

dont throw for no WwwAuthenticateHeader in Challenge result

---

src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs

Reverts AzureAD/microsoft-authentication-library-for-dotnet#4577.
This breaks the one branch build for release:
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1246330&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=cdee0a61-8978-5bd6-7f9d-8251f4e5ad03&l=27

Revert "avoid allocating full scopes string twice ParseScopesForTelemetry"

---

src/client/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj
src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj

Fixes #4605 
- Add net 6 as TFM for Microsoft.Identity.Client.Extensions.Msal
- Make System.IO.FileSystem.AccessControl only included for Net standard 2.0 in Microsoft.Identity.Client.Extensions.Msal

#4605 Only include needed packages

---

src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/MigrationAid/MigrationAid.cs

Fixes #
Broken links
Minor change to resolve broken links on MS Learn. In reference docs where the example authority `https://login.microsoftonline.com/common`  and others surface without backticks, it's picked up as a broken link, as per the broken links report. 
**Testing**
None
- Once merged and a CI job to auto-generate the reference is triggered,  about 5 broken links on MS Learn will auto-resolve.

Resolve broken MS Learn links stemming from auto-generated reference.

---

src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
src/client/Microsoft.Identity.Client/Http/HttpManager.cs
src/client/Microsoft.Identity.Client/Internal/Logger/DurationLogHelper.cs
src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
src/client/Microsoft.Identity.Client/Utils/MeasureDurationResult.cs
src/client/Microsoft.Identity.Client/Utils/StopWatchService.cs

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4442
Updating stopwatch operations to use singleton
**Testing**
Negligible impact
Previous benchmark
| Method                | CacheSize   | EnableCacheSerialization | Mean       | Min        | Max        | Gen0    | Gen1    | Allocated |
|---------------------- |------------ |------------------------- |-----------:|-----------:|-----------:|--------:|--------:|----------:|
| AcquireTokenForClient | (1, 10)     | False                    |  10.998 us |  10.525 us |  12.647 us |  0.6714 |       - |  11.36 KB |
| AcquireTokenForClient | (1, 10)     | True                     | 110.139 us | 105.564 us | 118.477 us | 11.4746 |  3.4180 | 188.86 KB | …

Updating stopwatch operations to use singleton

---

src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4602
Updating cryptographic error when cert is disposed.
**Testing**
Unit
N/A

Updating cryptographic error when cert is disposed.

---

src/client/Microsoft.Identity.Client/AuthScheme/PoP/InMemoryCryptoProvider.cs

Fixes #4633
Existing integration tests cover this well. Took me quite some time to fix them :)

Fix for #4633 - use PSS padding for SHR POP memory crypto provider

---

.github/workflows/benchmark-action.yml

Fixes #
[https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/security/code-scanning](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/security/code-scanning)
Harden-Runner GitHub Action installs a security agent on the Github-hosted runner to prevent exfiltration of credentials, monitor the build process, and detect compromised dependencies
**Testing**
gh security
none

Add harden runner on benchmark-action.yml

---

.github/workflows/trigger_onebranch_ci.yml

Fixes #
[https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/security/code-scanning](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/security/code-scanning)
Harden-Runner GitHub Action installs a security agent on the Github-hosted runner to prevent exfiltration of credentials, monitor the build process, and detect compromised dependencies
**Testing**
gh security
none

Add harden runner on trigger_onebranch_ci.yml

---

.github/workflows/benchmark-action.yml
.github/workflows/trigger_onebranch_ci.yml

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/security/code-scanning
This pull request introduces adjustments to the GitHub Actions workflow configuration to align with best practices for security, specifically adhering to the principle of least privilege. The changes aim to minimize the permissions granted to the GitHub Actions runner, reducing potential security risks while maintaining the workflow's functionality.
**Testing**
none

[Code Scan] Refine GitHub Actions Workflow Permissions for Enhanced Security

---

tests/Microsoft.Identity.Test.Core.UIAutomation/CoreUiTestConstants.cs
tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/SeleniumExtensions.cs

Fixes #
Fix for selenium tests in build
Add a step to click next button if the confirmation page comes
**Testing**

Added fix for selenium tests

---

src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsTests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs

Fixes #4402 
* Add error message parsing for cloud shell error response where the message is in nested JSON
* Add mock for error messages from different sources.
**Testing**
Updated unit tests

Handle error response from cloud shell and add tests

---

src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
src/client/Microsoft.Identity.Client/MsalException.cs
src/client/Microsoft.Identity.Client/MsalServiceException.cs
tests/Microsoft.Identity.Test.Unit/ExceptionTests/MsalExceptionTests.cs

Fixes #
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4187
Adding correlation id to `MsalException` class
**Testing**
Unit

Adding correlation id to MSAL Exception

---

build/template-install-keyvault-secrets.yaml

Use MSI based Resource Manager for Builds / Tests

Use MSI based Resource Manager for Builds / Tests

---

src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs

Fixes #4690
- Because of a bug in Azure Active Directory (AAD) related to handling JWT tokens signed with certain algorithms. This bug prevents the successful utilization of SHA2 and PSS signing algorithms under specific conditions, leading to authentication failures.
- As a temporary measure to circumvent this AAD issue, we have disabled the use of SHA2 and PSS for creating client credentials from certificates. This is achieved by setting IsSha2CredentialSupported to false. This change ensures compatibility with AAD's current capabilities and allows token acquisition to proceed without encountering the identified bug.
- Modified the `IsSha2CredentialSupported` property to always return false, bypassing the SHA2 and PSS check for certificate-based …

Temporary Workaround for AAD JWT Token Signing Algorithm Issue

---

src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs

Fixes #4695
Relates to #4690 
Because of a bug in Azure Active Directory (AAD) related to handling JWT tokens signed with certain algorithms, we rolled back the usage of SHA2 and PSS for creating client creds.
**Testing**
Unit tests 
None

re-enabling the use of SHA2 and PSS for creating client credentials from certificate

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.NetFwk.cs

Move CodeQL exclusion to the correct line

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.NetFwk.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/OnBehalfOfServicePrincipalTests.cs

Fixes #
Disable PPE tests until labs is ready. Will be enabled as part of https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4749
**Testing**

Disable ppe tests

---

src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/GenericAuthorityTests.cs
tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/InteractiveFlowTests.NetFwk.cs
tests/Microsoft.Identity.Test.Unit/AppConfigTests/PublicClientApplicationBuilderTests.cs

Fixes #4686
- allowed non-GUID client ids for `AuthorityType.Generic`
- this allows usage of `PublicClientApplicationBuilder` with Identity Providers such as Duende IdentityServer or Keycloak
**Testing**
- added test for `AcquireTokenInteractive` in `GenericAuthorityTests` which uses [Duende IdentityServer](https://demo.duendesoftware.com)
- also manually tested with Keycloak
- no performance impact for existing functionality

PublicClientApplicationBuilder - allow non-GUID client id for AuthorityType.Generic

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/WwwAuthenticateParametersIntegrationTests.NetFwk.cs

Currently ARM API for subscriptions/get supports multiple API versions, this PR updates the one used to the currently latest.
**Testing**
Yes, the PR updates the integration tests only.
No perf impact.
<s>- [ ] All relevant documentation is updated.</s>

Used multiple ARM API versions for subscriptions/get in WwwAuthenticateParametersIntegrationTests

---

src/client/Microsoft.Identity.Client/AppConfig/BaseAbstractApplicationBuilder.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs

Fixes #4608 
This will help partners (Id.Web) keep their code simple and not having to worry about authority type in OBO.
https://github.com/AzureAD/microsoft-identity-web/issues/2509
**Testing**

Fix for #4608- do not throw exception for ADFS + WithTenantId

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/CiamIntegrationTests.cs

Lab now switched to a new API and this test is now failing. The data was wrongly added to the old Lab DB, and is now corrected in the new Lab DB.

Fix failing CIAM tests

---

src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.NetFwk.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.WithRegion.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/TelemetryClientTests.cs

Fixes #4775 
CC @Robbie-Microsoft @Avery-Dunn @rayluo - please review and if we agree on this, let's apply it to all MSALs.

Fix for #4775 - deprecate WithClientAssertion(string)

---

CHANGELOG.md

Update CHANGELOG.md for MSAL Release 4.61.1

Update CHANGELOG.md for MSAL Release 4.61.1

---

tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ManagedIdentityTests.NetFwk.cs

Fixes #4834
This PR introduces a new unit test to validate the process of acquiring a MSI token and subsequently using it as an assertion to obtain a token from ESTS. The test performs the following steps:
- Acquires an MSI token using a user-assigned Managed Identity.
- Validates the token acquisition from the MSI endpoint.
- Uses the obtained MSI token to create and configure a Confidential Client Application.
- Acquires a token for the CCA with the appropriate scopes.
- Validates the successful acquisition and properties of the CCA token.
Was able to use the existing lab setup and the msi helper service for this test. 
**Testing**
test itself
none

Add Test for Acquiring MSI Token and Exchanging for ESTS Token in Confidential Client Application

---

src/client/Microsoft.Identity.Client/IAccount.cs
src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentRequest.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/DeviceCodeFlowIntegrationTest.cs
tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs

The previous check in to fix a device code flow issue unintentionally introduced a breaking change by adding a new property in IAccount public interface. Remove the new property in IAccount and only depend on the internal Account object for the new property.
**Testing**
The Integration test has been updated to test the change.
None

Remove AccountSource from public IAccount interface to avoid breaking change

---

src/client/Microsoft.Identity.Client/AuthScheme/PoP/InMemoryCryptoProvider.cs
tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/InteractiveFlowTests.NetFwk.cs
tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs

Fixes #4881
This pull request addresses a regression identified in the pre-release phase that caused incorrect encoding of JSON Web Key (JWK) parameters in the RSA public key export function. 
- revert the change.
- Added unit tests to verify the correct encoding of JWK parameters.
**Testing**
unit tests
none

Fix Pre-release Regression: Correct JSON Web Key (JWK) Encoding for RSA Public Key Export

---

CHANGELOG.md

Update CHANGELOG for MSAL 4.63.0 Release

Update CHANGELOG for MSAL 4.63.0 Release

---

tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/SeleniumExtensions.cs
tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/InteractiveFlowTests.NetFwk.cs

…from id to name
Fixes #
#4879 
Edited HandleConsent in SeleniumExtensions.cs to search for the element by name instead of id since an id was not assigned to the "Accept" Button on the consent UI
**Testing**

Changed consent handler to find element by name instead of ID

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.NetFwk.cs
tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/SeleniumExtensions.cs

Fixes #
Broken build. See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4905
**Testing**

Disabling arlinton test case for "WithSecret_TestAsync"

---

build/platform_and_feature_flags.props
src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenCommonParameters.cs
src/client/Microsoft.Identity.Client/AuthenticationResult.cs
src/client/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
src/client/Microsoft.Identity.Client/Extensibility/AbstractConfidentialClientAcquireTokenParameterBuilderExtension.cs
src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationResultTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ExtensiblityTests.cs

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4922
Adding WithAdditionalCacheParameters api
**Testing**
Unit

Adding api to enable additional caching parameters

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForManagedIdentityParameterBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/ManagedIdentityApplicationBuilder.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ManagedIdentityTests.NetFwk.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs

Fixes #4921
Remove experimental flag on Managed Identity Claims and Capabilities APIs
**Testing**
unit and integ tests 
none
still in internal preview so nothing to update yet.

Remove experimental flag on Managed Identity Claims and Capabilities APIs

---

src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/DstsAuthorityTests.cs

Fixes #4927 
Update code to use the type from authority info to build authority instead of creating aad authority 
**Testing**
Unit tests

Fix the config authority type to acquire the type from AuthorityInfo

---

src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
src/client/Microsoft.Identity.Client/Utils/DateTimeHelpers.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs
tests/Microsoft.Identity.Test.Unit/UtilTests/DateTimeHelperTests.cs

Fixes #4963
This PR add a new GetDurationFromNowInSeconds specific to MI in MSAL to handle multiple date-time formats while calculating the duration from now. Specifically, the fix:
- Adds support for Unix timestamps, ISO 8601 and other common date-time formats.
- Adds improved error handling for unsupported or invalid date formats by throwing an MsalClientException.
- Ensures that fallback logic only throws an exception after attempting valid date-time parsing strategies.
**Testing**
- Added additional test cases to validate handling of various date-time formats including Unix timestamps, ISO 8601, and common date-time formats (MM/dd/yyyy HH:mm:ss, yyyy-MM-dd HH:mm:ss).
- Added a test case for invalid date-time formats to ensure that the method throws …

Fix Date-Time Parsing in GetDurationFromNowInSeconds for Multiple Formats

---

src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/iOSBroker.cs

Fix for the issue - https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4958

update the deprecated openURL(:) api to openURL(:options:completionHandler) 

---

build/template-OneBranch-CI-libsandsamples.yaml
build/template-OneBranch-Tests-libsandsamples.yaml
build/template-pack-and-sign-packages.yaml

Update OB tests to use OB CI template due to [S360 items](https://vnext.s360.msftcloudes.com/blades/security?blade=AssignedTo:All~KPI:1a423da8-b18d-4fd5-b881-9d7a40860434~SLA:1~Forums:All~Program:65a010a5-1e3d-4777-bb89-f149470a507d~waves:All~KPI%20Ranking:All~Tab:Summary~_loc:Security&peopleBasedNodes=jmprieur_team;ddelimarsky_team;bogavril_team&global=4:38bfcbed-2abb-4fe1-9eb7-7df98a14bcfb)
OB pipeline was calling into the classic YAML which points to nuget.org.

Update OB tests to use OB CI template

---

build/template-pack-and-sign-all-nugets.yaml

Fixes #5007
Remove obsolete sbom task, as per OB [instructions ](https://eng.ms/docs/products/onebranch/securitycompliancegovernanceandpolicies/pipelinerequirements/generatingsbom)it is auto added. Also the old task is [calling into maven based on the S360](https://msit.powerbi.com/groups/me/apps/8eed334f-05e9-4651-a3a1-280eab2d78b1/reports/b03c5e3f-b064-413d-8464-c3e2478cacfa/b249ddf707be1eb3a4dc?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47&experience=power-bi&filter=S360DetailsWave2%2Fs360Id%20eq%20%274c65f0a86de9821c8d0e008814c00b672a3f8079832c09c51bf5d741d95de53f%27). 
Click [here](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1394750&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=5ba6599d-da82-5bef-521d-5e569b80bee0&l=1) …

Remove obsolete Software Bill Of Materials (SBOM) task

---

src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedUserTokenCacheAccessor.cs
src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs

Add more logging to GetAccounts by id

---

build/template-build-and-run-all-tests.yaml

Adding variables to code coverage check

---

src/client/Microsoft.Identity.Client/AuthenticationResultMetadata.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt

Fixes #4996
This is for internal usages only. For external use, ppl should use `AuthenicationResult.TokenType`

Remove TokenType from auth result metadata

---

src/client/Microsoft.Identity.Client/Utils/MeasureDurationResult.cs
src/client/Microsoft.Identity.Client/Utils/StopWatchService.cs
tests/Microsoft.Identity.Test.Unit/UtilTests/StopWatchServiceTests.cs

Fixes #4895 and #5036
Updated the MeasureDurationResult class to properly measure milliseconds and microseconds so that the measuredurationresult accurately reflects the total elapsed time without being limited by the modulus operator
**Testing**
Used the sample app to ensure that stopwatch measured time aligned with the durationtotalinms within the authenticationresultmetadata when there is a change of scopes

Fix bug in MeasureDurationResult

---

src/client/Microsoft.Identity.Client/ApiConfig/AbstractConfidentialClientAcquireTokenParameterBuilder.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/PoPTests.NetFwk.cs
tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
tests/Microsoft.Identity.Test.Unit/pop/PopAuthenticationOperationTests.cs

Mark `WithSignedHttpRequestProofOfPossession` as experimental

Mark `WithSignedHttpRequestProofOfPossession` as experimental

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/MtlsPopTests.cs

This pull request introduces changes to the Microsoft Authentication Library (MSAL) for .NET to support Mutual TLS (mTLS) Proof of Possession (PoP) when using DSTS authority. 
Fixes : #5060 
Modified the validation logic in AcquireTokenForClientParameterBuilder to accept DSTS as a valid authority type for MTLS PoP operations. Previously, the logic only supported Azure AD authorities. This change allows the library to handle MTLS PoP with DSTS, broadening the scope of its applicability.
Updated the logic to enforce region checks strictly for Azure AD authorities when performing MTLS PoP. This modification prevents the region-related exception from being incorrectly applied to DSTS authorities, which do not utilize Azure regions in the same manner.
Added new unit tests in MtlsPopTests.cs to …

Support for SNI MTLS POP with DSTS Authorities

---

src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs

Fix for 5033 - MSI response json parse failure error code

---

src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj

Fixes: [Perf run failure](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1411117&view=logs&j=97e6c0f4-d22b-53e5-1a93-e7d20714371e&t=b4dce3fc-ba9a-595d-5211-18b24f8149a9) 
This pull request includes a small but important change to the `Microsoft.Identity.Client.csproj` file. The change updates the `System.Security.SecureString` package reference instead of including it, which ensures that the latest version of the package is used.
* [`src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj`](diffhunk://#diff-9ac6db6bc92909bb7098ee9bef1bdf9d3b58b44ea30beb38e6844493426c8543L149-R155): Changed `PackageReference Include` to `PackageReference Update` for `System.Security.SecureString` to ensure the latest version is used.

Update the System.Security.SecureString package reference instead of including it

---

src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt

The primary changes involve moving constants and methods between the shipped and unshipped API files across various target frameworks.
* Added new MSAL error constants and token parameter builder methods to the shipped API files for `net462`, `net472`, `net8.0-android`, `net8.0-ios`, `net8.0`, and `netstandard2.0` frameworks. [[1]](diffhunk://#diff-cbf7ceab1866a87ca05ef66c7a043bce3f21b454700e64c182b403f3884ad195R1021-R1027) [[2]](diffhunk://#diff-ba02fd692f23584ac367416f93f025aafe3ee9535e714b7ad1f46486a18c81c7R987-R993) [[3]](diffhunk://#diff-521cf91ecf46f87e497e10f087b1a619fa9cdf96c4698ae336c7dd47324092e1R989-R995) [[4]](diffhunk://#diff-ffdc781f3ef8f95fb6c862704d1835c18d30398d487f8bba40c46091311be10aR983-R989) [[5]](diffhunk://#diff-9f88cae51dd278939a6c4dd17a5f89c65e7bd3560ab630ed505b869 …

Moving constants and methods between the shipped and unshipped API files across various target frameworks

---

src/client/Microsoft.Identity.Client/ManagedIdentity/EnvironmentVariables.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/MachineLearningManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
tests/Microsoft.Identity.Test.Common/Core/Helpers/ManagedIdentityTestUtil.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/MachineLearningTests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs

Fixes #4984
- Add ML MSI Source
**Testing**
- Unit tests
none

Add ML MSI Source

---

src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt

This pull request includes updates to the `Microsoft.Identity.Client` library across multiple .NET target frameworks. The main change involves the addition of a new managed identity source, `MachineLearning`, to the public API shipped files, and the removal of the same from the unshipped files.
* Added `Microsoft.Identity.Client.ManagedIdentity.ManagedIdentitySource.MachineLearning = 7` to the following public API shipped files:
- `src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt`
- `src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt`
- `src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt`
- `src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt`
- …

Updates to Public API

---

build/template-OneBranch-Tests-libsandsamples.yaml

Disable OB Test Code Coverage
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1412185&view=codecoverage-tab

Disable OB Test Code Coverage

---

src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/ManagedIdentityTestUtil.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/AppServiceTests.cs

Fixes #5077
This pull request includes updates to the `ManagedIdentityClient` to enhance the logic for determining the managed identity source and adds new test methods to cover these changes. The most important changes include reordering the conditions in the `GetManagedIdentitySource` method, adding a new method to set environment variables for upgrade scenarios, and introducing new test cases for various managed identity sources.
Enhancements to managed identity source logic:
* [`src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs`](diffhunk://#diff-13058fddef4867b4d36dca3120b5b961ae64b039b32bcf5ad410a364b36fbfa8L65-R65): Reordered the conditions in the `GetManagedIdentitySource` method to check for `identityEndpoint` and `identityHeader` before …

Reordered the condition for ManagedIdentitySource.MachineLearning to be checked after ManagedIdentitySource.AppService instead of before it. 

---

build/template-build-and-run-all-tests.yaml

Enabling the build to not fail if the code coverage value is maintained
Fixes #
Basically, this will allow us to make changes to non covered lines without the build failing. the policy is a lot more lenient while still nudging us in the right direction. The build will now fail if the code coverage falls below the baseline which is set by the nightly build that targets main
**Testing**

Update code coverage policy

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsMtlsPopTests.cs

This pull request includes a small change to the `tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsMtlsPopTests.cs` file. The change re-enables the `Sni_Gets_Pop_Token_Successfully_TestAsync` test method by uncommenting the `[TestMethod]` attribute.
ESTS confirmed of the fix and this should be good to go

Enable SNI + MTLS Pop Integration Tests

---

src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs

Fixes #5097
This pull request focuses on enhancing the logging within the `ManagedIdentityClient` class to provide more detailed information about the detection of managed identity sources. The most important changes include adding informative log messages at various points in the identity detection process and removing a redundant warning message.
Enhancements to logging:
* [`src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs`](diffhunk://#diff-13058fddef4867b4d36dca3120b5b961ae64b039b32bcf5ad410a364b36fbfa8L63-R91): Added log messages to indicate the detection of different managed identity sources, such as Service Fabric, App Service, Machine Learning, Cloud Shell, and Azure Arc.
* …

Enhancing the logging within the ManagedIdentityClient class to provide more detailed information about the detection of managed identity sources.

---

src/client/Microsoft.Identity.Client/Platforms/netstandard/NetCorePlatformProxy.cs

Fixes #5075
Set `UseShellExecute` to false when set `RedirectStandardOutput` to true.
Ref: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=net-8.0#remarks
**Testing**

Set UseShellExecute to false in OpenLinuxBrowser

---

src/client/Microsoft.Identity.Client/Utils/CoreHelpers.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/CoreHelperTests.cs

Fixes #5061 https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5061
MSAL .NET is converting "openid%20profile%20offline_access" to "openid+profile+offline_access"
Partner prefers the original format since: "Some third party Identity Providers [namely Broadcom Siteminder] do NOT allow the usage of "+" to represent a space in URLs, in particular to separate scopes in the "authorize" endpoint."
“+” is defined in rfc1866 https://www.rfc-editor.org/rfc/rfc1866.txt made in 1995:
7.5. Queries and Indexes
The keywords are escaped according to [URL] and joined
by `+'.
rfc1866 is obsoleted by rfc2854 https://www.rfc-editor.org/rfc/rfc2854.txt made in 2000, while rfc2854 does not suggest using "+"
**Testing** …

Stop replacing "%20" to "+" since it is obsoleted

---

src/client/Microsoft.Identity.Client/Cache/StorageJsonKeys.cs
src/client/Microsoft.Identity.Client/Extensibility/AcquireTokenForClientBuilderExtensions.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/CacheKeyExtensionTests.cs

Fixes #
Removing known key check for cache key extension. This is no longer needed because cache key components are added to an additional node which prevents clashing with known JSON keys.
Removing known key check for cache key extension.
**Testing**

Removing known key check for cache key extensions

---

src/client/Microsoft.Identity.Client/Internal/Requests/ManagedIdentityAuthRequest.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsCredentialProbeManager.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsV2ManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityRequest.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/ManagedIdentityApplication.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Common/TestCommon.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/AppServiceTests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsTests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs
tests/devapps/Managed Identity apps/ManagedIdentityAppVM/Program.cs

Fixes [#5115](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5115)
Please refer to the above task for more details. This is PR is part of a feature branch. 
This pull request introduces several changes to the `Microsoft.Identity.Client` library, focusing on enhancing managed identity support, particularly with the addition of a new `ImdsV2` managed identity source. The changes include creating new classes, updating existing methods, and adding new methods to support asynchronous operations.
Key changes include:
* Introduced `ImdsV2ManagedIdentitySource` class to handle the new `ImdsV2` managed identity source. (`src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsV2ManagedIdentitySource.cs`)
* Added `ImdsCredentialProbeManager` class to probe the IMDS …

[MSI V2 Feature] Adding IMDSV2 probe logic

---

src/client/Microsoft.Identity.Client/AppConfig/AssertionRequestOptions.cs
src/client/Microsoft.Identity.Client/Internal/ClientCredential/SignedAssertionDelegateClientCredential.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #4948
This pull request introduces new functionality to handle client capabilities in the `Microsoft.Identity.Client` library. The changes include updates to the `AssertionRequestOptions` class, modifications to the `SignedAssertionDelegateClientCredential` class to utilize these capabilities, and corresponding updates to the public API and unit tests.
* [`src/client/Microsoft.Identity.Client/AppConfig/AssertionRequestOptions.cs`](diffhunk://#diff-b48cd0f220d91dbc6af2b3db8a7c7c9ba353d1bf24fe9a90bba7e19e48d60f62R34-R39): Added a new property, `ClientCapabilities`, to the `AssertionRequestOptions` class. This property allows client applications to declare capabilities in the assertion.
* [`src/client/Microsoft.Identity.Client/Internal/ClientCredenti …

Expose client capabilities in AssertionRequestOptions for MSI FIC scenarios

---

src/client/Microsoft.Identity.Client/Internal/ClientCredential/SignedAssertionDelegateClientCredential.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #5143
This pull request introduces changes to the `SignedAssertionDelegateClientCredential` class to handle client capabilities and claims more effectively, and adds corresponding unit tests to verify these changes.
Improvements to handling client capabilities and claims:
* [`src/client/Microsoft.Identity.Client/Internal/ClientCredential/SignedAssertionDelegateClientCredential.cs`](diffhunk://#diff-a748b78c034c87d7a7fc04df5974cdbb703ce39a7ef692b02ebb79a141afbd83L58-R68): Simplified the logic for setting client capabilities and added a new section to set claims within the `AddConfidentialClientParametersAsync` method.
Unit tests for new functionality:
* [`tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs`](diff …

Add the missing claims in SignedAssertion With AssertionRequestOptions Delegate 

---

tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs

Fixes #
Fix for test issue for EnsureDefaultCacheKeyBehaviorWhenCertSerialNumberIsNotUsedTestAsync
using the shared cache in unit tests seems to cause collisions from different threads. Disabling for now
**Testing**

Fix for test issue for EnsureDefaultCacheKeyBehaviorWhenCertSerialNumberIsNotUsedTestAsync

---

src/client/Microsoft.Identity.Client/Internal/ClientCredential/CertificateAndClaimsClientCredential.cs
src/client/Microsoft.Identity.Client/Internal/ClientCredential/SignedAssertionClientCredential.cs
src/client/Microsoft.Identity.Client/Internal/ClientCredential/SignedAssertionDelegateClientCredential.cs
src/client/Microsoft.Identity.Client/Internal/Constants.cs
src/client/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/FmiTests.cs

Fixes #
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/3166310
Update MSAL to send "fmi-bearer" client assertion type based on the provided client id.
If Client id = "urn:microsoft:identity:fmi" Assertion type = "uurn:ietf:params:oauth:client-assertion-type:fmi-bearer"
If Client id != "urn:microsoft:identity:fmi" Assertion type = "uurn:ietf:params:oauth:client-assertion-type:jwt-bearer"
This will occur when using the `WithCertificate()` and `WithClientAssertion(func<>)` methods
**Testing**
Unit testing

Update MSAL to send "fmi-bearer" client assertion type based on the client id

---

src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt

Fixes - post release updates
This pull request includes updates to the `PublicAPI.Shipped.txt` and `PublicAPI.Unshipped.txt` files across multiple target frameworks. The changes primarily focus on adding new API members to the shipped files and removing them from the unshipped files, reflecting their new shipped status.
* Added new API members to `PublicAPI.Shipped.txt` files:
* `Microsoft.Identity.Client.BrokerOptions.OperatingSystems.Linux` [[1]](diffhunk://#diff-cbf7ceab1866a87ca05ef66c7a043bce3f21b454700e64c182b403f3884ad195R1030-R1034) [[2]](diffhunk://#diff-cbf7ceab1866a87ca05ef66c7a043bce3f21b454700e64c182b403f3884ad195R1030-R1034) [[3]](diffhunk://#diff-ba02fd692f23584ac367416f93f025aafe3ee9535e714b7ad1f46486a18c81c7R996-R1000) …

Update to the `PublicAPI.Shipped.txt` and `PublicAPI.Unshipped.txt` files across multiple target frameworks

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/MtlsPopTests.cs

This PR fixes throwing exception when service config region is set to null for Mtls.
Fixes #5181 
- Replaced `string.IsNullOrEmpty` with `null` in `AcquireTokenForClientParameterBuilder.cs` for Azure region check when the authority is AAD.
**Testing**
- Updates existing unit tests to cover another case for this case when service config region is set to null and fixes existing tests.
N/A

For Mtls, throw exception when service config region is set to null.

---

docs/msiv1_token_revocation.md

Fixes #
The first diagram introduced in [MSI v1 token revocation specification #5137](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/5137) missed a parameter that the Resource Provider needs to use.
Added missing param in arrow 8, also refined headers
**Testing**
This is a diagram change. Let's just visually check the diagrams, [before](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/622fa2a/docs/msiv1_token_revocation.md#flow-diagram---revocation-event) and [after](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/rayluo/refine-MSIv1-token-revocation-diagram/docs/msiv1_token_revocation.md#flow-diagram---revocation-event).
N/A

Added missing param in arrow 8, also refined headers

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenForClientParameters.cs
src/client/Microsoft.Identity.Client/Extensibility/RP/AcquireTokenForClientParameterBuilderForResourceProviders.cs
src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/client/Microsoft.Identity.Client/MsalError.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #5111
**Specification -** https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/docs/msiv1_token_revocation.md
This pull request includes several changes to enhance token acquisition and revocation capabilities in the MSAL library. The most important changes focus on adding support for token hash-based refresh, improving cache handling, and updating error handling.
* Added a new method `WithAccessTokenSha256ToRefresh` to the `AcquireTokenForClientParameterBuilder` for configuring the SDK to bypass the cache for a specific token based on its SHA-256 hash.
* Introduced a new property `AccessTokenHashToRefresh` in `AcquireTokenForClientParameters` to store the hash of the token to be refreshed.
* Updated …

Enhancing Token Refresh Control in MSAL: Introducing .WithAccessTokenSha256ToRefresh() in AcquireTokenForClient Flows

---

src/client/Microsoft.Identity.Client/Internal/Constants.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheNotificationTests.cs

Fixes #
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/3174516
Adding a flag to `TokenCacheNotificationArgs` to signal that the clientId is an RMA node.
**Testing**
Unit testing

Adding a flag to TokenCacheNotificationArgs to signal that the clientId is an RMA node.

---

src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt

This pull request includes changes to the public API shipped and unshipped files across multiple frameworks and platforms. The main changes involve adding new methods and constants related to token cache notifications and token acquisition, and removing them from the unshipped files.
* Added `Microsoft.Identity.Client.TokenCacheNotificationArgs.NoDistributedCacheUseReason.get` method. [[1]](diffhunk://#diff-cbf7ceab1866a87ca05ef66c7a043bce3f21b454700e64c182b403f3884ad195R1035-R1038) [[2]](diffhunk://#diff-cbf7ceab1866a87ca05ef66c7a043bce3f21b454700e64c182b403f3884ad195R1035-R1038) [[3]](diffhunk://#diff-ba02fd692f23584ac367416f93f025aafe3ee9535e714b7ad1f46486a18c81c7R1001-R1004) [[4]](diffhunk://#diff-521cf91ecf46f87e497e10f087b1a619fa9cdf96c4698ae336c7 …

MSAL 4.70.0 Public API updates

---

src/client/Microsoft.Identity.Client/Internal/Constants.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/MachineLearningManagedIdentitySource.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationResultTests.cs

Fixes #5183
This pull request includes several changes to the Microsoft Identity Client library to support different managed identity configurations and improve test coverage. The most important changes include adding a new constant for the 2017 managed identity client ID, updating the request creation logic for older machine learning environments, and adding a new unit test to verify the default token type.
* [`src/client/Microsoft.Identity.Client/Internal/Constants.cs`](diffhunk://#diff-69a69c54931b0896394c0c0ba76f1642cd6931ce882c112675804793bea7a5daR45): Added a new constant `ManagedIdentityClientId2017` for the 2017 managed identity client ID.
* [`src/client/Microsoft.Identity.Client/ManagedIdentity/MachineLearningManagedIdentitySource.cs`](diffhunk …

Fix Machine Learning Source to Use "clientid" Instead of "client_id"

---

src/client/Microsoft.Identity.Client/Instance/AadAuthority.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/AadAuthorityTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #
[Fix for5184](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5184)
Fixing IsCommonOrOrganizationsTenant check to not return true for consumers by adding back the consumers check. This will prevent this api from returning true.
**Testing**
Unit testing

Fixing IsCommonOrOrganizationsTenant check to not return true for consumers

---

tests/Microsoft.Identity.Test.Unit/Helpers/ParallelRequestMockHandler.cs
tests/Microsoft.Identity.Test.Unit/ParallelRequestsTests.cs

Fixes #5191
This pull request introduces enhancements to the `ParallelRequestMockHandler` class and adds new unit tests to validate concurrent tenant requests and per-tenant caching in the `ParallelRequestsTests` class. The most important changes include adding request counting functionality, modifying token endpoint handling, and adding new test methods to ensure proper handling of concurrent requests and caching.
Enhancements to `ParallelRequestMockHandler`:
* Added `_requestCount` field and `RequestsMade` property to track the number of requests made.
* Incremented `_requestCount` in `SendRequestAsync` method to count each request made.
* Modified the endpoint comparison to use `EndsWith` for better flexibility.
* Enhanced token generation to …

Add Concurrency Test for Multi-Tenant AcquireTokenForClient Scenario

---

tests/Microsoft.Identity.Test.Unit/CacheExtension/MsalCacheHelperTests.cs

Fixes #5198
This pull request focuses on improving the reliability of a test in the `MsalCacheHelperTests` class by addressing a flaky test issue. The key changes include adding a bug reference comment and replacing the use of `SemaphoreSlim` with `TaskCompletionSource` to handle asynchronous event firing more effectively.
Improvements to test reliability:
* [`tests/Microsoft.Identity.Test.Unit/CacheExtension/MsalCacheHelperTests.cs`](diffhunk://#diff-ec551df56e4886a439b04558f8165b4be6d4fdedebdddaa49263f772ecda89a7R490-L492): Added a comment to reference the bug fix for the flaky test `EventFires2Async` (#5198).
* [`tests/Microsoft.Identity.Test.Unit/CacheExtension/MsalCacheHelperTests.cs`](diffhunk://#diff-ec551df56e4886a439b04558f8165b4be6d4fdedebddda …

Fix the flaky test EventFires2Async

---

src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs

Fixes - The condition skipCache remains the same. We have not touched the functionality that determines whether the cache is skipped or not.
**Improved Clarity:**
The new log message precisely matches the condition in skipCache. That clarity helps developers and maintainers quickly understand why the cache was not used.
By removing misleading wording, we reduce confusion and potential troubleshooting errors.

Fix logger message to accurately reflect skipCache condition

---

docs/msiv1_token_revocation.md

Fixes - spec clarity
This pull request includes a small update to the `docs/msiv1_token_revocation.md` file. The change adds an important note about the applicability of the design to specific API versions.
Documentation update:
* [`docs/msiv1_token_revocation.md`](diffhunk://#diff-708928b0ae864249d92886b9476987f030e1ffa83a0f529e2f6df380c06a7676R50-R51): Added a note specifying that the design is only applicable to MIRP api-version=2025-03-30 for App Service, with the service fabric API version to be made available soon.

Update msiv1_token_revocation.md to specify MIRP api-version

---

.github/workflows/benchmark-action.yml

Fixes #5159
This pull request includes updates to the `.github/workflows/benchmark-action.yml` file to ensure compatibility with the latest .NET version.
Updates to `.github/workflows/benchmark-action.yml`:
* Updated the `dotnet-version` from `6.0.418` to `8.0.x` to use the latest .NET version.
* Changed the target framework in the benchmark run command from `net6.0` to `net8.0` to align with the updated .NET version.
**Testing**
build
none

Update benchmark-action.yml to use NET 8

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
src/client/Microsoft.Identity.Client/Extensibility/AcquireTokenForClientBuilderExtensions.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/FmiIntegrationTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/CacheKeyExtensionTests.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/FmiTests.cs

Fixes #
Removing experimental feature Flag from `WithFmiPath` and `WithAdditionalCacheKeyComponents` which is used by `WithFmiPath`
**Testing**

Removing experimental feature Flag from WithFmiPath

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/LegacyPopTest.NetFwk.cs

This pull request introduces significant changes to the `LegacyPopTest.NetFwk.cs` file to support new authentication protocols and enhance testing capabilities. The most important changes include the addition of a new internal class for handling PoP (Proof of Possession) authentication, new test methods for different PoP scenarios, and a utility method for computing SHA256 hashes.
* Added `MsAuth10AtPop` internal static class and `MsAuth10AtPopOperation` class to handle PoP authentication operations, including methods to format results and get token request parameters.
* Introduced `LegacyPopUsingNewProtocol_CertThumbprinJWK_Async` and `LegacyPopUsingNewProtocol_RsaKey_Async` test methods to validate the new PoP authentication protocols using certificate thumbprints and RSA keys, …

Add a test for msauth  pop

---

src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/ICryptographyManager.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #5228
This pull request introduces a new method for creating SHA256 hashes in hexadecimal format and updates various parts of the codebase to utilize this new method. The most important changes include adding the new method to the cryptography manager interface, implementing the method, and updating relevant tests to use the hexadecimal hash method.
* [`src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/ICryptographyManager.cs`](diffhunk://#diff-7736527ce2bf61a9eb62e73d8785842efe27ebf94de620d5f757389df9d34874R14): Added `CreateSha256HashHex` method to the `ICryptographyManager` interface.
* [`src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs`](diffhunk://#diff-49bdf0a5cd26d0edc922e07676c2ad3f8426 …

Update MSIv1 Token Revocation's token_sha256_to_refresh param to use sha256's HEX representation

---

src/client/Microsoft.Identity.Client/AppConfig/IMsalSFHttpClientFactory.cs
src/client/Microsoft.Identity.Client/Http/HttpManager.cs
src/client/Microsoft.Identity.Client/Http/IHttpManager.cs
src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
src/client/Microsoft.Identity.Client/Instance/Validation/AdfsAuthorityValidator.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/AzureArcManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ServiceFabricManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/SimpleHttpClientFactory.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManager.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/FmiIntegrationTests.cs
tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/MsiProxyHttpManager.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpClientFactoryTests.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs
tests/Microsoft.Identity.Test.Unit/Helpers/ParallelRequestMockHandler.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ServiceFabricTests.cs
tests/Microsoft.Identity.Test.Unit/ParallelRequestsTests.cs

This pull request introduces a new interface `IMsalSFHttpClientFactory` to handle custom server certificate validation for Service Fabric scenarios and refactors the existing HTTP manager code to support this new interface. The most important changes include the addition of the new interface, modification of existing methods to use the new validation callback, and updates to various classes to ensure compatibility.
* [`src/client/Microsoft.Identity.Client/AppConfig/IMsalSFHttpClientFactory.cs`](diffhunk://#diff-11e54d923daddeb63995b7cc7077a2078616f28a67b9bab8db5dbf3f4024aaf7R1-R33): Introduced the `IMsalSFHttpClientFactory` interface to create `HttpClient` instances with custom server certificate validation callbacks.
* [`src/client/Microsoft.Identity.Client/Http/HttpManager.cs`](diffhunk: …

Update the SF flow to get a http client from the factory

---

LibsAndSamples.sln
ManagedIdentityTokenRevocation/ManagedIdentityTokenRevocation.csproj
ManagedIdentityTokenRevocation/Program.cs
prototype/token-revocation-msiv1.md

This pull request includes the addition of a new project, `ManagedIdentityTokenRevocation`, to the solution and updates to the solution configuration to support this new project.
Addition of new project:
* [`LibsAndSamples.sln`](diffhunk://#diff-658b40bd7b7140793d178fa774659068a808830dff1ac411909eb534f86a479fR183-R184): Added the `ManagedIdentityTokenRevocation` project to the solution file.
Solution configuration updates:
* [`LibsAndSamples.sln`](diffhunk://#diff-658b40bd7b7140793d178fa774659068a808830dff1ac411909eb534f86a479fR1739-R1780): Updated the solution configuration platforms to include various configurations (Debug, Release) for the new `ManagedIdentityTokenRevocation` project across different platforms (Any CPU, ARM, ARM64, iPhone, iPhoneSimulator, x64, x86).
* …

[Managed Identity] Token Revocation Dev App

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/LongRunningOnBehalfOfTests.cs

This pull request introduces a new test case to validate the behavior of long-running On-Behalf-Of (OBO) token acquisition with a custom cache key. The test ensures that MSAL respects custom keys during token initiation and reuses them correctly during subsequent token acquisitions. Validates to confirm that MSAL respects a user‐provided, non‐empty key string during Long‐Running On‐Behalf‐Of (OBO) flows. Specifically, we verify that:
When a custom key (e.g. "MyCustomKey") is passed to InitiateLongRunningProcessInWebApi(...), MSAL does not overwrite it with an assertion hash 
Subsequent calls to AcquireTokenInLongRunningProcess(...) with the same custom key succeed without requiring a new user assertion.
* `tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/LongRunningOnBehalfO …

Add test verifying custom user‐provided LR session key usage in OBO scenario

---

src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs

Fixes #5277
This pull request includes minor documentation corrections in the `ConfidentialClientApplicationBuilder` and `PublicClientApplicationBuilder` classes to fix a typo in the example URL for Entra ID authorities.
Documentation fixes:
* Corrected the typo in the example URL for Entra ID authorities in the `WithGenericAuthority` method of `ConfidentialClientApplicationBuilder` (`https://login.microsfoftonline.com/common` → `https://login.microsoftonline.com/common`). (`src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs`, [src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.csL342-R342](diffhunk://#diff-e2e87b43b43d31cdb3c62ecf8c6e1a5a1985291f458f89737a1237136f9c4c82L342-R342))
* …

fixes typo in the example Entra ID authority URL in two builder classes XML comments.

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/FmiIntegrationTests.cs

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5275
Adding regional versions of FMI tests
These tests are intended to demonstrate how to use FMI tests with regions. therefore, the code is not consolidated.
**Testing**
Unit

Adding regional tests for FMI

---

build/template-build-and-run-all-tests.yaml

Set Build Env variables to skip MSI E2E tests if needed

---

src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ServiceFabricManagedIdentitySource.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ServiceFabricTests.cs

Fixes #5286 5286
Update the flow to only set the callback for service fabric
**Testing**
Unit tests

Fix regression in ManagedIdentity flows

---

tests/devapps/MacMauiAppWithBroker/MacMauiAppWithBroker.csproj

Build is broken because it uses "warnings as errors" and a custom msbuild target is emitting a warning. I've made it a non-warning message.

Fix the build

---

tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/SeleniumExtensions.cs

Fixes #
This pull request refactors the `CreateDefaultWebDriver` method in `SeleniumExtensions` to improve configurability, enhance debugging options, and ensure better compatibility with CI environments. Additionally, it introduces a helper method for window maximization and removes redundant code.
* Enhanced Chrome options:
- Added modern headless mode (`--headless=new`) and other flags for improved performance and compatibility in CI environments.
* Improved driver binary selection:
- Introduced a prioritized approach to locate the ChromeDriver binary:
1. Explicit environment variable (`CHROMEWEBDRIVER`) for local overrides.
2. Default fallback to a predefined `drivers` folder in the application directory for CI.
3. Final fallback to the system …

Set a generous startup timeout of 120 seconds for the `ChromeDriver` to accommodate slower environments.

---

src/client/Microsoft.Identity.Client/Http/HttpManager.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/HttpSnifferClientFactory.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs

Use HTTP 2 on .NET

---

src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/iOSBroker.cs
src/client/Microsoft.Identity.Client/Platforms/iOS/EmbeddedWebview/WKWebNavigationDelegate.cs

update the api openURL(:) to open(:options:completionHandler) as openURL(:) is deprecated in iOS 18.
https://developer.apple.com/documentation/uikit/uiapplication/openurl(_:)/

update the deprecated openURL(:) api to openURL(:options:completionHandler)

---

src/client/Microsoft.Identity.Client/Http/HttpManager.cs
src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs

Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5255
Adds the correlation id when the request_timeout exception is thrown if it is available
**Testing**
Unit testing

Ensure correlationId is added to request_timeout exception when available

---

tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/SeleniumExtensions.cs

Attempts to resolve some of the flaky tests described in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5357
One of the most common failure occurs during interactive tests, occasionally there's a timeout when trying to create the web driver for Selenium:
```
Test method Microsoft.Identity.Test.Integration.SeleniumTests.InteractiveFlowTests.Interactive_AADAsync threw exception:
OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:52547/session timed out after 120 seconds.
Stack trace
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at …
```

Improve stability of Selenium tests

---

README.md
supportPolicy.md

Update supportPolicy.md
This pull request updates the MSAL.NET support policy and documentation to reflect changes in supported and unsupported versions. The updates include adjustments to version ranges, release dates, and end-of-support dates for MSAL.NET.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L22-R22): Updated the supported version range for MSAL.NET 4.x from `4.71.2` to `4.72.1` and clarified that versions `< 4.72.1` are unsupported.
* `supportPolicy.md`: 
- Updated the supported version range for MSAL.NET 4.x from `4.61.2` to `4.72.1` and clarified unsupported versions `< 4.72.1`.
- Adjusted the latest patch version and end-of-support date for unsupported MSAL.NET 4.x versions to `4.72.0` with an end-of-support date of July …

Fix support versions

---

docs/msi_v2/guidance_for_sdks_consuming_msal.md

Fixes - design doc
This pull request updates the documentation for MSI V2 authentication in the Azure SDK to reflect changes in endpoint naming and improves formatting for clarity. The most important changes include updating the endpoint name to `/issuecredential` and enhancing section headings for better readability.
This pull request updates the documentation for MSI V2 authentication in the Azure SDK to reflect changes in the `/issuecredential` endpoint and simplifies the explanation of certificate handling. The most important changes include updating endpoint references, clarifying the role of the `IMtlsHttpClientFactory` interface, and revising certificate management details.
* Updated references to the `/credential` endpoint, replacing it with …

Update MSI V2 SDK Guidance 

---

src/client/Microsoft.Identity.Client/AuthenticationResult.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationResultTests.cs

Fixes #5392
This pull request focuses on cleaning up deprecated code and improving test coverage for the `AuthenticationResult` class in the Microsoft Identity Client library. The most notable changes include the removal of `[Obsolete]` attributes from certain constructors and the addition of a comprehensive unit test to validate the consistency of the "for-test" constructor.
* Removed `[Obsolete]` and `[EditorBrowsable(EditorBrowsableState.Never)]` attributes from two constructors in the `AuthenticationResult` class to make them publicly accessible again. These constructors were previously marked as deprecated but are now intended for continued use. (`src/client/Microsoft.Identity.Client/AuthenticationResult.cs`, …

Restore public AuthenticationResult constructor

---

tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsMtlsPopTests.cs

Fixes - Test SNI against PROD 
This pull request includes a minor change to the `public async Task Sni_Gets_Pop_Token_Successfully_TestAsync()` test method. The change removes an extra query parameter that was previously used for testing purposes.
* [`tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsMtlsPopTests.cs`](diffhunk://#diff-99c80006e86a371e433178287365a7fef77cf82ef0187aaaa37ec37cfe4d9ffcL50): Removed the `.WithExtraQueryParameters("dc=ESTSR-PUB-WUS3-AZ1-TEST1&slice=TestSlice")` line, which was used to specify a test slice in the query parameters.
**Testing**
unit, integration
none

Run Client Credentials Mtls Pop Sni Tests against PROD

---

src/client/Microsoft.Identity.Client/Http/Retry/CsrMetadataProbeRetryPolicy.cs
src/client/Microsoft.Identity.Client/Http/Retry/HttpRetryCondition.cs
src/client/Microsoft.Identity.Client/Http/Retry/ImdsRetryPolicy.cs
src/client/Microsoft.Identity.Client/Http/Retry/RetryPolicyFactory.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsV2ManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/RequestType.cs
tests/Microsoft.Identity.Test.Unit/Helpers/TestRetryPolicies.cs
tests/Microsoft.Identity.Test.Unit/Helpers/TestRetryPolicyFactory.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs

This new retry policy is almost the exact same as the IMDS retry policy, except it doesn't retry on 404.

IMDSv2: Created a retry policy for the CSR Metadata Probe

---

src/client/Microsoft.Identity.Client/TokenCache.cs
tests/Directory.Build.props
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.NetFwk.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/OnBehalfOfTests.cs
tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/UsernamePasswordIntegrationTests.NetFwk.cs
tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/IgnoreFederatedTests.cs
tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/DeviceCodeFlowIntegrationTest.cs
tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/InteractiveFlowTests.NetFwk.cs

Fixes #5416
This pull request introduces a mechanism to conditionally ignore federated tests in the test suite when a specific pipeline configuration is set. The main changes include adding a new property to define the condition, modifying test methods to support conditional ignoring, and creating a custom attribute for handling ignored tests.
* **New property for conditional test ignoring**:
- Added a property group in `tests/Directory.Build.props` to define the `IGNORE_FEDERATED` constant when the `MSAL_SKIP_FEDERATED_TESTS` environment variable is set to `True`. (`[tests/Directory.Build.propsR9-R11](diffhunk://#diff-ab383adf9c3ae4ff1108d67217eb0fed97889109451be090a231e1091fba8d17R9-R11)`)
* **Custom attribute for ignoring tests**:
- Introduced a new …

Implement DoNotRunFederatedTestsAttribute to gate federated tests

---

build/template-build-and-run-all-tests.yaml

Fixes - Build 
```
Downloading task: BuildQualityChecks (9.2.2)
##[warning]Task 'Build Quality Checks' version 9 (BuildQualityChecks@9) is dependent on a Node version (16) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
```
This pull request makes a minor update to the build pipeline configuration, specifically upgrading the `BuildQualityChecks` task to a newer version in the `build/template-build-and-run-all-tests.yaml` file.
* Upgraded the `BuildQualityChecks` task from version 9 to version 10 to ensure the build uses the latest features and fixes.
**Testing**
builds
n/a

Upgrade Build Quality Checks task to v10 to remove Node 16 EOL warning

---

src/client/Microsoft.Identity.Client/Extensibility/AcquireTokenParameterBuilderExtensions.cs
src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ExtraHttpHeadersTests.cs

Fixes #5439
This pull request adds a comprehensive new unit test class, `ExtraHttpHeadersTests`, to verify the behavior of the `WithExtraHttpHeaders` API in the token acquisition flow. The tests ensure that custom HTTP headers are correctly sent, default headers remain unaffected by null input, user headers can override defaults, and repeated calls to set headers behave as expected.
* Added `ExtraHttpHeadersTests` class to validate `WithExtraHttpHeaders` functionality in `AcquireTokenForClient`, including scenarios for sending custom headers, listing all headers, handling null values, overriding defaults, and ensuring last call precedence.
* Implemented helper methods (`TryGetHeader`, `EnumerateAllHeaders`, and `AssertHeaderExists`) to facilitate …

Introduces the extensibility API to allow users to add custom HTTP headers to token acquisition requests (under extensibility)

---

src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs

Fixes #5451 
Exclude passing the x-client-os param from GetAuthorizationUri 
**Testing**
Update unit tests to validate that the query param is not passed

Remove passing x-client-os as query param in authorization uri

---

src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs

The text that is removed only applies to one of many possible causes of ApiContractViolation or IncorrectConfigiration.
This causes confusion with developers. 
The recommendation would be to enable PII during development to see the WAM error message which will contain the correct reason for the error. 
A long-term change may be considered, and that will require proper classification of all cases where ApiContractViolation or IncorrectConfigiration may occur.
**Testing**
No new tests are needed
No perf impact

Remove confusing error text as it only applies to one of many possible causes

---

src/client/Microsoft.Identity.Client/ManagedIdentity/V2/ImdsV2ManagedIdentitySource.cs
src/client/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
tests/Microsoft.Identity.Test.Common/TestConstants.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs

The entra token request happens over STS instead of Imds. The appropriate STS headers have now been added to the request.

ImdsV2: Added Additional Headers to the Entra Token Request

---

tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/DeviceCodeFlowIntegrationTest.cs

Fixes [#5485](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5485)
This pull request removes several integration tests related to device code flow scenarios from the `DeviceCodeFlowIntegrationTest.cs` file. The primary changes involve deleting tests for Arlington users, MSA users, and Azure AD Kerberos features, which streamlines the test suite in response to test failures.
**Test removals:**
* Removed Arlington device code flow tests, including both standard and ADFS user scenarios.
* Removed device code flow test for MSA users, which was previously marked as failing due to environment issues.
**Kerberos feature test removal:**
* Removed the entire Azure AD Kerberos device code flow test region, including the main test …

Remove some flaky tests that were just an overkill

---

src/client/Microsoft.Identity.Client/Http/HttpManager.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/HttpSnifferClientFactory.cs
tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs

Fixes #5460 
PR to try revert changes for Http2
**Testing**

Revert changes made for Http2

---

src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForManagedIdentityParameterBuilder.cs
src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenForManagedIdentityParameters.cs
src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
src/client/Microsoft.Identity.Client/AppConfig/ManagedIdentityApplicationBuilder.cs
src/client/Microsoft.Identity.Client/Internal/RequestContext.cs
src/client/Microsoft.Identity.Client/Internal/Requests/ManagedIdentityAuthRequest.cs
src/client/Microsoft.Identity.Client/ManagedIdentity/V2/ImdsV2ManagedIdentitySource.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/TestKeyGuardManagedIdentityKeyProvider.cs
tests/devapps/Managed Identity apps/ManagedIdentityAppVM/ManagedIdentityAppVM.csproj
tests/devapps/Managed Identity apps/ManagedIdentityAppVM/Program.cs

[MSI v2] - Enable attestation in pop flows

[MSI v2] - Enable attestation in pop flows

---

src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsManagedIdentitySource.cs
tests/Microsoft.Identity.Test.Common/Core/Helpers/ManagedIdentityTestUtil.cs
tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs

- Added caching so the method that builds a URI for IMDSv1 and IMDSv2 only checks the environment variable once, the first time
- this removes redundant logs
- Improved IMDSv2 unit tests so that the IMDS test environment variable is now used for IMDSv2

ImdsV2: Added Caching for the IMDS Endpoint Env Variable + Improved Unit Tests
