- src/MSAL.PCL.Android/BrokerHelper.cs
- src/MSAL.PCL.Android/MSAL.PCL.Android.csproj
- src/MSAL.PCL.CoreCLR/MSAL.PCL.CoreCLR.csproj
- src/MSAL.PCL.Desktop/DeviceAuthHelper.cs
- src/MSAL.PCL.Desktop/MSAL.PCL.Desktop.csproj
- src/MSAL.PCL.WinRT/DeviceAuthHelper.cs
- src/MSAL.PCL.WinRT/MSAL.PCL.WinRT.csproj
- src/MSAL.PCL.iOS/BrokerHelper.cs
- src/MSAL.PCL.iOS/MSAL.PCL.iOS.csproj
- src/MSAL.PCL/Handlers/AcquireTokenSilentHandler.cs
- src/MSAL.PCL/MSAL.PCL.csproj
- tests/Test.MSAL.NET.Unit/Test.MSAL.NET.Unit.csproj
- tests/TestApp/AndroidTestApp/AndroidTestApp.csproj
- tests/TestApp/AndroidTestApp/MainActivity.cs
- tests/TestApp/DesktopTestApp/DesktopTestApp.csproj
- tests/TestApp/TestApp.PCL/TestApp.PCL.csproj
- tests/TestApp/TestApp.PCL/TokenBroker.cs
- tests/TestApp/UniversalTestApp/UniversalTestApp.Windows/MainPage.xaml.cs
- tests/TestApp/UniversalTestApp/UniversalTestApp.Windows/UniversalTestApp.Windows.csproj
- tests/TestApp/XFormsApp.Droid/XFormsApp.Droid.csproj
- tests/TestApp/XFormsApp.iOS/XFormsApp.iOS.csproj
- tests/TestApp/XFormsApp/SecondPage.cs
- tests/TestApp/XFormsApp/XFormsApp.csproj
- tests/TestApp/iOSTestApp/MsaliOSTestAppViewController.cs
- tests/TestApp/iOSTestApp/iOSTestApp.csproj
Code Cleaning :- Removing warnings tagged as Errors #19
> Code Cleaning :- Removing warnings tagged as Errors #19

- src/MSAL.PCL/AbstractClientApplication.cs
- src/MSAL.PCL/ClientCredential.cs
- src/MSAL.PCL/ConfidentialClientApplication.cs
- src/MSAL.PCL/IClientAssertionCertificate.cs
- src/MSAL.PCL/IPlatformParameters.cs
- src/MSAL.PCL/LoggerCallbackHandler.cs
- src/MSAL.PCL/MsalException.cs
- src/MSAL.PCL/PublicClientApplication.cs
- src/MSAL.PCL/UIOptions.cs
Jenkins Build  :- adding appropriate XML tags
> Jenkins Build  :- adding appropriate XML tags

- src/MSAL.Common/ClientAssertionCertificate.cs
- src/MSAL.Common/PublicClientApplicationExtensions.cs
- src/MSAL.PCL.Android/AuthenticationAgentActivity.cs
- src/MSAL.PCL.Android/AuthenticationAgentContinuationHelper.cs
- src/MSAL.PCL.Android/BrokerConstants.cs
- src/MSAL.PCL.Android/PlatformParameters.cs
- src/MSAL.PCL.Desktop/CustomWebBrowser.cs
- src/MSAL.PCL.Desktop/PlatformParameters.cs
- src/MSAL.PCL.Desktop/SilentWindowsFormsAuthenticationDialog.cs
- src/MSAL.PCL.Desktop/WebBrowserNavigateErrorEventArgs.cs
- src/MSAL.PCL.Desktop/WinFormWebAuthenticationDialog.cs
- src/MSAL.PCL.Desktop/WindowsFormsWebAuthenticationDialogBase.cs
- src/MSAL.PCL.iOS/AuthenticationAgentUINavigationController.cs
- src/MSAL.PCL.iOS/PlatformParameters.cs
- src/MSAL.PCL/MsalOption.cs
- src/MSAL.PCL/TokenCache.cs
Jenkins Build :- adding appropriate XML tags
> Jenkins Build :- adding appropriate XML tags

- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
> MSAL :- CredScan Clean up

- src/MSAL.PCL/Internal/AuthenticationRequestParameters.cs
- src/MSAL.PCL/MSAL.PCL.csproj
> push files

- src/MSAL.PCL/Internal/AuthorizationResult.cs
- src/MSAL.PCL/Internal/OAuth2/OAuthConstants.cs
- src/MSAL.PCL/Internal/OAuth2/TokenResponse.cs
- src/MSAL.PCL/Internal/Requests/InteractiveRequest.cs
- tests/Test.MSAL.NET.Unit/Mocks/MockWebUI.cs
- tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
Add state QP to authorize requests and update the authorizationResult validation to ensure that the same state is returned back to the user. #114
> Add state QP to authorize requests

- src/MSAL.Common/Logger.cs
- src/MSAL.PCL.Android/Logger.cs
- src/MSAL.PCL.Android/WebUI.cs
- src/MSAL.PCL.Desktop/PlatformInformation.cs
- src/MSAL.PCL.Desktop/WebUI.cs
- src/MSAL.PCL.WinRT/PlatformInformation.cs
- src/MSAL.PCL.WinRT/WebUI.cs
- src/MSAL.PCL.iOS/GlobalSuppressions.cs
- src/MSAL.PCL.iOS/Logger.cs
- src/MSAL.PCL.iOS/WebUI.cs
- src/MSAL.PCL/ClientApplicationBase.cs
- src/MSAL.PCL/Internal/Http/HttpRequest.cs
- src/MSAL.PCL/Internal/Instance/AadAuthority.cs
- src/MSAL.PCL/Internal/Instance/AdfsAuthority.cs
- src/MSAL.PCL/Internal/Instance/Authority.cs
- src/MSAL.PCL/Internal/Interfaces/IWebUI.cs
- src/MSAL.PCL/Internal/LoggerBase.cs
- src/MSAL.PCL/Internal/MsalHelpers.cs
- src/MSAL.PCL/Internal/OAuth2/OAuth2Client.cs
- src/MSAL.PCL/Internal/PlatformInformationBase.cs
- src/MSAL.PCL/Internal/RequestContext.cs
- src/MSAL.PCL/Internal/Requests/AuthenticationRequestParameters.cs
- src/MSAL.PCL/Internal/Requests/AuthorizationCodeRequest.cs
- src/MSAL.PCL/Internal/Requests/BaseRequest.cs
- src/MSAL.PCL/Internal/Requests/InteractiveRequest.cs
- src/MSAL.PCL/Internal/Requests/SilentRequest.cs
- src/MSAL.PCL/MSAL.PCL.csproj
- tests/Test.MSAL.NET.Unit/InstanceTests/AuthorityTests.cs
- tests/Test.MSAL.NET.Unit/LoggerCallbackTests.cs
- tests/Test.MSAL.NET.Unit/Mocks/MockWebUI.cs
Code change to rename CallState class to RequestContext. Issue #163
> Rename CallState class to RequestContext. Issue #163

- README.md
Update README.md to add a build badge for the dev branch
> Update README.md to add a build badge

- src/Microsoft.Identity.Client/Platforms/Android/WebUI.cs
ensure android activity is called on UI thread. #189
> ensure android activity is called on UI thread.

- samples/DesktopTestApp/Program.cs
- src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/Features/UIBehavior.cs
- src/Microsoft.Identity.Client/Internal/Constants.cs
- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/Microsoft.Identity.Client/PublicClientApplication.cs
- src/Microsoft.Identity.Client/UIBehavior.cs
- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
rename UIOptions to UIBehavior per #207
> rename UIOptions to UIBehavior per #207

- src/Microsoft.Identity.Client/Internal/Http/HttpRequest.cs
- tests/Test.MSAL.NET.Unit/Mocks/MockHelpers.cs
- Include all 500-599 server errors
- Update MockHelper
- Issue #159
> Add additional HTTP error codes to resiliency #159

- src/Microsoft.Identity.Client/Features/ConfidentialClient/ClientAssertionCertificate.cs
- src/Microsoft.Identity.Client/Features/ConfidentialClient/ClientCredential.cs
- src/Microsoft.Identity.Client/Internal/Base64UrlEncoder.cs
- src/Microsoft.Identity.Client/Internal/Instance/Authority.cs
- src/Microsoft.Identity.Client/Internal/PlatformInformationBase.cs
- src/Microsoft.Identity.Client/Internal/Requests/AuthorizationCodeRequest.cs
- src/Microsoft.Identity.Client/Internal/Requests/BaseRequest.cs
- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/Microsoft.Identity.Client/Platforms/Android/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/iOS/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/StaTaskScheduler.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/winrt/WebUI.cs
- src/Microsoft.Identity.Client/TokenCache.cs
- src/Microsoft.Identity.Client/UserAssertion.cs
Use nameof(...) instead of "..." whenever possible and relevant.
- https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
> Use 'nameof' expression to reference parameter name.

- src/Microsoft.Identity.Client/AuthenticationResult.cs
- src/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/Microsoft.Identity.Client/Internal/Cache/AccessTokenCacheItem.cs
- src/Microsoft.Identity.Client/Internal/Cache/BaseTokenCacheItem.cs
- src/Microsoft.Identity.Client/Internal/Requests/BaseRequest.cs
- src/Microsoft.Identity.Client/TokenCache.cs
- src/Microsoft.Identity.Client/User.cs
- tests/Test.MSAL.NET.Unit/Mocks/TokenCacheHelper.cs
- tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/SilentRequestTests.cs
- tests/Test.MSAL.NET.Unit/TestConstants.cs
- tests/Test.MSAL.NET.Unit/TokenCacheKeyTests.cs
- tests/Test.MSAL.NET.Unit/TokenCacheTests.cs
Rename Signout to Remove and move it to app class, per#210
Store tenant id only in AccessTokenCacheItem #217
> Rename Signout to Remove and move it to app class

- GitVersion.yml
- README.md
- src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
cleanup for gitversion, nuget project description and readme
> cleanup for gitversion, nuget project description and readme

- src/Microsoft.Identity.Client/Internal/RequestContext.cs
- src/Microsoft.Identity.Client/Internal/Requests/BaseRequest.cs
- src/Microsoft.Identity.Client/Platforms/Android/AuthenticationActivity.cs
- src/Microsoft.Identity.Client/Platforms/net45/InteractiveWebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWindowsFormsAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/net45/WinFormWebAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
Clean up RequestContext Issue #259
> Jennyf/correlation id request context fixes 

- dev apps/DesktopTestApp/DesktopTestApp.csproj
- dev apps/DesktopTestApp/LoggerCallback.cs
- dev apps/DesktopTestApp/MainForm.Designer.cs
- dev apps/DesktopTestApp/MainForm.cs
- src/Microsoft.Identity.Client/Internal/RequestContext.cs
- src/Microsoft.Identity.Client/Logger.cs
- src/Microsoft.Identity.Client/Platforms/Android/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/iOS/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/InteractiveWebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWindowsFormsAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/net45/WinFormWebAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
- src/Microsoft.Identity.Client/Platforms/winrt/WebUI.cs
- src/Microsoft.Identity.Client/TokenCache.cs
- tests/Test.MSAL.NET.Unit/LoggerCallbackTests.cs
- tests/Test.MSAL.NET.Unit/Mocks/MockWebUI.cs
update sample app and fix context
> update sample app and fix context

- dev apps/XForms/XForms/AcquirePage.xaml
- dev apps/XForms/XForms/AcquirePage.xaml.cs
- dev apps/XForms/XForms/App.xaml.cs
- dev apps/XForms/XForms/SettingsPage.xaml
- dev apps/XForms/XForms/SettingsPage.xaml.cs
adding Authority editor and validation switch to Xamarin Forms test application https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/183
> xapp adding Authority editor and validation switch

- src/Microsoft.Identity.Client/ApiEvent.cs
- src/Microsoft.Identity.Client/CacheEvent.cs
- src/Microsoft.Identity.Client/Event.cs
- src/Microsoft.Identity.Client/HttpEvent.cs
- src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
- src/Microsoft.Identity.Client/UiEvent.cs
This PR allows a peek into the event family. Their definition (as a subclass of `Dictionary<string, string>`) and their behaviors (i.e. the `Stop()` method etc.), were influenced by their actual usage pattern, which is currently under construction. So this PR is subject to future change.
> A preview of upcoming event family

- src/Microsoft.Identity.Client/IPublicClientApplication.cs
- src/Microsoft.Identity.Client/PublicClientApplication.cs
Expose UiParent to all platforms for Xamarin Forms (PCL) workaround.
> Expose UiParent to all platforms for Xamarin Forms (PCL) workaround.

- src/Microsoft.Identity.Client/Platforms/winrt/DispatcherTaskExtensions.cs
- src/Microsoft.Identity.Client/Platforms/winrt/WebUI.cs
fixing first attempt to open web UI issue
> running winRT WebUi on UI thread

- src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/Internal/Instance/Authority.cs
- src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
- src/Microsoft.Identity.Client/TokenCache.cs
- tests/Test.MSAL.NET.Unit/CacheTests/TokenCacheTests.cs
> More logs in the API

- src/Microsoft.Identity.Client/ApiEvent.cs
- src/Microsoft.Identity.Client/CacheEvent.cs
- src/Microsoft.Identity.Client/DefaultEvent.cs
- src/Microsoft.Identity.Client/Event.cs
- src/Microsoft.Identity.Client/HttpEvent.cs
- src/Microsoft.Identity.Client/Telemetry.cs
- src/Microsoft.Identity.Client/UiEvent.cs
- tests/Test.MSAL.NET.Unit/TelemetryTests.cs
I'll still need to port code from previous ADAL dotnet PR for grabbing ApplicationName, ApplicationVersion, ClientId, and DeviceId. But the PR is structure-wise completed.
> Telemetry main logic

- src/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/Microsoft.Identity.Client/IClientApplicationBase.cs
- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
make client_id and authority getters public, per #344
> make client_id and authority getters public

- tests/Test.MSAL.NET.Unit/TelemetryTests.cs
replace edge with random string
> replace edge with random string

- build/build.ps1
- dev apps/XForms/XForms.Android/MainActivity.cs
- src/Microsoft.Identity.Client/Telemetry.cs
address warnings in the code and update build script to fail on warnings
> address warnings in the code

- src/Microsoft.Identity.Client/Internal/RequestContext.cs
- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
This is PR is functionally completed and ready for review. But please DO NOT attempt to merge it to or from dev, because it is relied on the existing [Telemetry main logic PR #314](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/314) . Once that one got merged in, I would handle the rebasing on this one.
> Telemetry UiEvent

- dev apps/XForms/XForms/AcquirePage.xaml
- dev apps/XForms/XForms/AcquirePage.xaml.cs
- dev apps/XForms/XForms/App.xaml.cs
- dev apps/XForms/XForms/SettingsPage.xaml
- dev apps/XForms/XForms/SettingsPage.xaml.cs
- Adding b2c switch ( ClientId, Authority, Scopes)
- showing redirect URI
- adding authority pass switch (silent flow)
> adding pass Auth switch, b2c switch, clientId edit, redUri display

- src/Microsoft.Identity.Client/Event.cs
- src/Microsoft.Identity.Client/HttpEvent.cs
- src/Microsoft.Identity.Client/Internal/Http/HttpRequest.cs
- src/Microsoft.Identity.Client/Internal/Http/HttpResponse.cs
- src/Microsoft.Identity.Client/Internal/Instance/AadAuthority.cs
- src/Microsoft.Identity.Client/Internal/Instance/Authority.cs
- src/Microsoft.Identity.Client/Internal/Instance/B2CAuthority.cs
- src/Microsoft.Identity.Client/Internal/OAuth2/OAuth2Client.cs
- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/TelemetryTests.cs
This is PR is functionally completed and ready for review. But please DO NOT attempt to merge it to or from dev, ~because it relies on the existing [Telemetry main logic PR #314](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/314) . Once that one got merged in,~ I would handle the rebasing on this one.
> Telemetry HttpEvent

- src/Microsoft.Identity.Client/ApiEvent.cs
- src/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/Microsoft.Identity.Client/PublicClientApplication.cs
- tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
- tests/Test.MSAL.NET.Unit/TelemetryTests.cs
This is PR is ready for review. But please DO NOT attempt to merge it to or from dev, ~because it relies on the existing Telemetry HttpEvent PR #326 . Once that one got merged in~, I would handle the rebasing on this one.
This PR contains multiple independent commits. The easiest way to review this PR is to review those individual commits one by one.
> Telemetry ApiEvent

- dev apps/XForms/XForms/CachePage.xaml.cs
- src/Microsoft.Identity.Client/Internal/Requests/SilentRequest.cs
- src/Microsoft.Identity.Client/MsalUiRequiredException.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/SilentRequestTests.cs
throw MsalUiRequiredException if null user is passed in ATS, #372
> throw MsalUiRequiredException if null user is passed in ATS

- src/Microsoft.Identity.Client/Platforms/Android/PlatformInformation.cs
- src/Microsoft.Identity.Client/Platforms/iOS/PlatformInformation.cs
- src/Microsoft.Identity.Client/Platforms/netstandard1.3/PlatformInformation.cs
Ensure relevant x-client values are correctly returned, #366
> Ensure relevant x-client values are correctly returned

- src/Microsoft.Identity.Client/Internal/Cache/AccessTokenCacheItem.cs
- src/Microsoft.Identity.Client/Internal/Cache/RefreshTokenCacheItem.cs
- src/Microsoft.Identity.Client/Internal/ClientInfo.cs
- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/Microsoft.Identity.Client/MsalClientException.cs
- tests/Test.MSAL.NET.Unit/CacheTests/TokenCacheTests.cs
- tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
Fail if client_info is not returned from the server, #354
> Fail if client_info is not returned from the server

- src/Microsoft.Identity.Client/TelemetryTokenCacheAccessor.cs
- src/Microsoft.Identity.Client/TokenCache.cs
- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
This is PR is ready for review and discussion. This PR contains cache_lookup and cache_write events. We will discuss plan for the remaining events.
This is part of the solution to #162
> Telemetry CacheEvent

- src/Microsoft.Identity.Client/ApiEvent.cs
- src/Microsoft.Identity.Client/DefaultEvent.cs
- src/Microsoft.Identity.Client/Event.cs
- src/Microsoft.Identity.Client/HttpEvent.cs
- src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
- src/Microsoft.Identity.Client/UiEvent.cs
address fx-cop violations, #377
> address fx-cop violations

- AutomationApp/AutomationUI.cs
- dev apps/XForms/XForms/AcquirePage.xaml.cs
- src/Microsoft.Identity.Client/AuthenticationResult.cs
- src/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/Microsoft.Identity.Client/Features/ConfidentialClient/ConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/Features/ConfidentialClient/IConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/IClientApplicationBase.cs
- src/Microsoft.Identity.Client/IPublicClientApplication.cs
- src/Microsoft.Identity.Client/Internal/Cache/AccessTokenCacheKey.cs
- src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/Microsoft.Identity.Client/PublicClientApplication.cs
- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/SilentRequestTests.cs
Rename additionalScope and make scope plural #381
> Rename additionalScope and make scope plural

- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
> update error message

- src/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/Microsoft.Identity.Client/IClientApplicationBase.cs
- src/Microsoft.Identity.Client/Internal/MsalHelpers.cs
- src/Microsoft.Identity.Client/Internal/OAuth2/OAuth2Client.cs
- src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/Microsoft.Identity.Client/Internal/Telemetry/Event.cs
- src/Microsoft.Identity.Client/Telemetry.cs
- tests/Test.MSAL.NET.Unit/ConfidentialClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/InstanceTests/AadAuthorityTests.cs
- tests/Test.MSAL.NET.Unit/Mocks/MockHttpMessageHandler.cs
- tests/Test.MSAL.NET.Unit/PublicClientApplicationTests.cs
- tests/Test.MSAL.NET.Unit/RequestsTests/InteractiveRequestTests.cs
- tests/Test.MSAL.NET.Unit/TelemetryTests.cs
Add support for SliceParameters, per #389
> Add support for SliceParameters, per #389

- README.md
update readme, per the template. #77
> update readme, per the template

- dev apps/XForms/XForms.iOS/AppDelegate.cs
- src/Microsoft.Identity.Client/Platforms/iOS/AuthenticationContinuationHelper.cs
> removed unused param

- src/Microsoft.Identity.Client/Logger.cs
make DefaultLoggingEnabled internal. It will be removed later, #412
> make DefaultLoggingEnabled internal

- src/Microsoft.Identity.Client/Internal/MsalError.cs
Made MsalError class internal and tested using end to end, everything looks good.
> made MsalError class internal #445

- build/credscan-exclusion.json
I don't think that the json file is correct as is.
> Fix a missing coma between the 2 supressions.

- src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
moving to latest extra package as we can remove wordaround parameter
> moving to latest extra package

- build/inject-signed-binaries.cmd
Fix build to create separate nuget files
> Fix build to create separate nuget files

- src/Microsoft.Identity.Client/Internal/Instance/AadAuthority.cs
> Add Arlington URL to list of trusted authorities

- tests/dev apps/XForms/XForms.Android/Resources/Resource.Designer.cs
- tests/dev apps/XForms/XForms.Android/XForms.Android.csproj
- tests/dev apps/XForms/XForms/XForms.csproj
Msal.net does not build with recent versions of Visual Studio 2017 per #501 
This PR includes - 
- Clean up of Xamarin forms projects
- Update to monodroid 8.0
- Update to Xamarin.Forms version
> Msal.net does not build with recent versions of Visual Studio 2017

- .gitignore
- src/Microsoft.Identity.Client/Features/ConfidentialClient/JsonWebToken.cs
- src/Microsoft.Identity.Client/Features/EventSource/MsalEventSource.cs
- src/Microsoft.Identity.Client/Features/EventSource/PlatformLogger.cs
- src/Microsoft.Identity.Client/Internal/PlatformPlugin.cs
- src/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/Microsoft.Identity.Client/Internal/Telemetry/TelemetryTokenCacheAccessor.cs
- src/Microsoft.Identity.Client/Platforms/Android/PlatformLogger.cs
- src/Microsoft.Identity.Client/Platforms/Android/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/iOS/PlatformLogger.cs
- src/Microsoft.Identity.Client/Platforms/iOS/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/net45/CustomWebBrowser.CustomWebBrowserEvent.cs
- src/Microsoft.Identity.Client/Platforms/net45/CustomWebBrowser.cs
- src/Microsoft.Identity.Client/Platforms/net45/InteractiveWebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWebUIDoneEventArgs.cs
- src/Microsoft.Identity.Client/Platforms/net45/SilentWindowsFormsAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebBrowserInterfaces.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebBrowserNavigateErrorEventArgs.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/net45/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/net45/WinFormWebAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
- src/Microsoft.Identity.Client/Platforms/netstandard1.3/WebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/winrt/WebUI.cs
- src/Microsoft.Identity.Client/Platforms/winrt/WebUIFactory.cs
Update namespace in source files to match the folders (See #500)
> Align namespaces with folders in MSAL#500

- changelog.txt
Please review and add comments for improving the change log. Thanks.
> Draft of changelog for 1.1.1-preview release

- GitVersion.yml
- changelog.txt
- src/Microsoft.Identity.Client/Platforms/iOS/TokenCacheAccessor.cs
> Remove logging from iOS TokenCacheAccesssor as requestContext is null

- changelog.txt
there is quite a bit for the release...
@jmprieur work your magic, but here is a start. Please note the last two...not sure how to word those, so relying on your PM skills. 
All comments/suggestions welcome. And thanks @bgavrilMS  for including issue #'s with your PRs 👍
> start of changelog for 2.6

- LibsNoSamples.sln
- tests/Microsoft.Identity.Test.Common/TestCategories.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabUser.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabUserHelper.cs
- tests/Microsoft.Identity.Test.Unit.net45/AuthorityAliasesTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/Integration/DeviceCodeFlowIntegrationTest.cs
- tests/Microsoft.Identity.Test.Unit.net45/Microsoft.Identity.Test.Unit.net45.csproj
- tests/Microsoft.Identity.Test.Unit.net45/SeleniumWrapper.cs
- tests/Microsoft.Identity.Test.Unit.netcore/Microsoft.Identity.Test.Unit.netcore.csproj
> Device Code Flow tests

- src/Microsoft.Identity.Client/AppConfig/AadAuthorityAudience.cs
- src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/Microsoft.Identity.Client/AppConfig/ApplicationOptions.cs
@jmprieur here are the fixes. i closed the items that were open to make it easier for you.
> fixes for JM

- src/Microsoft.Identity.Client/Cache/ITokenCacheAccessor.cs
- src/Microsoft.Identity.Client/IPublicClientApplication.cs
- src/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs
- src/Microsoft.Identity.Client/PublicClientApplication.cs
- src/Microsoft.Identity.Client/TelemetryCore/TelemetryTokenCacheAccessor.cs
- src/Microsoft.Identity.Client/TokenCacheAccessor.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/AccountTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/UIParentTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
- ITokenCacheAccessor
- TokenCacheAccessor
- IPublicClientApp
- iOSTokenCacheAccessor
- PublicClientApp
- TelemetryTokenCacheAccessor
fix spelling
> remove SetKeychainSecurityGroup

- src/Microsoft.Identity.Client/Cache/Keys/MsalAccessTokenCacheKey.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/CacheTests/MsalTokenCacheKeysTests.cs
- tests/devapps/UWP/MainPage.xaml
- tests/devapps/UWP/MainPage.xaml.cs
- tests/devapps/UWP/UWP.csproj
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/737
> Fix UWP cache

- contributing.md
Point to the new MSAL specific Contributor Overview and build / test setup. This should help contributors to MSAL.NET be more successful setting up the project for the first time. It should also help to delineate the MSAL repo from the ADAL repo.
Please review the contributor overview and build / test guidance wiki pages to ensure validity.
/cc @jmprieur
> create an MSAL specific contributor wiki entry

- src/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- tests/devapps/DesktopTestApp/MainForm.cs
Increase entropy for the state parameter as agreed across libraries
> Increase entropy for the state parameter as agreed across libraries

- src/Microsoft.Identity.Client/Exceptions/CoreErrorMessages.cs
- src/Microsoft.Identity.Client/LogMessages.cs
- src/Microsoft.Identity.Client/UI/CustomWebUiHandler.cs
closed the PR before pushing my PR changes
> pr feedback from previous review

- src/Microsoft.Identity.Client/Instance/B2CAuthority.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/CoreTestConstants.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
> add henry's changes from v3 branch for b2clogin.cn

- src/Microsoft.Identity.Client/Exceptions/CoreErrorCodes.cs
- src/Microsoft.Identity.Client/Exceptions/MsalExceptionFactory.cs
- src/Microsoft.Identity.Client/Http/HttpManager.cs
- src/Microsoft.Identity.Client/Instance/B2CAuthority.cs
- src/Microsoft.Identity.Client/MsalError.cs
- src/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Common/MsalTestConstants.cs
- tests/Microsoft.Identity.Test.Unit.net45/ExceptionTests/ErrorCodesTest.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
- tests/devapps/XForms/XForms/SettingsPage.xaml.cs
v3 update: Refactor OAuth2Client error handling and expand b2clogin allow list
> v3 update: Refactor OAuth2Client error handling and expand b2clogin allow list

- src/Microsoft.Identity.Client/Exceptions/CoreErrorCodes.cs
- src/Microsoft.Identity.Client/Exceptions/CoreErrorMessages.cs
- src/Microsoft.Identity.Client/Exceptions/MsalExceptionFactory.cs
- src/Microsoft.Identity.Client/Http/HttpManager.cs
- src/Microsoft.Identity.Client/Instance/B2CAuthority.cs
- src/Microsoft.Identity.Client/MsalError.cs
- src/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/CoreTestConstants.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManager.cs
- tests/Microsoft.Identity.Test.Unit.net45/ExceptionTests/ErrorCodesTest.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
- tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs
Better error handling for OAuth2Client and add support for B2Clogin.cn
> v2: Improve OAuth2Client error handling and add expand b2clogin allow list

- src/MSAL.Common.props
> Fixing #909

- msal-3x-blog.md
taking bogdan's idea a step further
> moving things around

- src/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AbstractClientAppBaseAcquireTokenParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenByRefreshTokenParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenByUsernamePasswordParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenWithDeviceCodeParameterBuilder.cs
- src/Microsoft.Identity.Client/AppConfig/IAppConfig.cs
- src/Microsoft.Identity.Client/AppConfig/IMsalHttpClientFactory.cs
- src/Microsoft.Identity.Client/AuthenticationResult.cs
- src/Microsoft.Identity.Client/ConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/Extensibility/ICustomWebUI.cs
- src/Microsoft.Identity.Client/ITokenCache.cs
- src/Microsoft.Identity.Client/LogCallback.cs
- src/Microsoft.Identity.Client/Platforms/iOS/UIParent.cs
- src/Microsoft.Identity.Client/Prompt.cs
- src/Microsoft.Identity.Client/TokenCache.cs
> Proposing fixes to XML comments to improve the reference documentation

- src/Microsoft.Identity.Client/Platforms/net45/SilentWebUI.cs
increasing the timeout for SilentWebUI from 2 seconds to 10 seconds
> SilentWebUI requires a significantly longer timeout

- src/Microsoft.Identity.Client/TokenCache.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/959
> Guarantee onafteraccess after onbeforeaccess for tokencache [959]

- src/Microsoft.Identity.Client/Exceptions/MsalErrorMessage.cs
- src/Microsoft.Identity.Client/UI/AuthorizationResult.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/982
> Update OperationCanceled message for android [982]

- src/Microsoft.Identity.Client/Internal/DeviceCodeResponse.cs
- tests/Microsoft.Identity.Test.Unit.net45/DeviceCodeResponseTests.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/984
> [984] DeviceCode should support verification_uri and verification_url

- src/Microsoft.Identity.Client/Platforms/net45/WebBrowserNavigateErrorEventArgs.cs
- src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialog.cs
- src/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
Caught during release validation.
> net desktop winforms browser classes must be public

- src/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
- tests/devapps/XForms/XForms/AcquirePage.xaml.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/993
> validate parameters to acquiretoken for authority values

- src/Microsoft.Identity.Client/TokenCache.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/993
> fix nullref in keychain setter on ios [993]

- tests/Microsoft.Identity.Test.Integration/Infrastructure/SeleniumExtensions.cs
Updating selenium tests to use file path to initialize chromedriver.exe
> Updating selenium tests to use file path.

- src/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
- src/Microsoft.Identity.Client/AppConfig/ApplicationOptions.cs
- src/Microsoft.Identity.Client/AppConfig/IAppConfig.cs
- src/Microsoft.Identity.Client/AppConfig/IMatsConfig.cs
- src/Microsoft.Identity.Client/AppConfig/MatsConfig.cs
- src/Microsoft.Identity.Client/Core/ICoreLogger.cs
- src/Microsoft.Identity.Client/Core/ServiceBundle.cs
- src/Microsoft.Identity.Client/Internal/MsalLogger.cs
- src/Microsoft.Identity.Client/Internal/NullLogger.cs
- src/Microsoft.Identity.Client/Mats/MatsTelemetryClient.cs
- src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- src/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
- src/Microsoft.Identity.Client/TokenCache.cs
- tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/PublicClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/MatsTests/MatsPublicClientTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/LoggerTests.cs
- tests/devapps/DesktopTestApp/PublicClientHandler.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/978
> Add x-client-app and x-client-ver infrastructure [978]

- src/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalAccountCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalAppMetadataCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalIdTokenCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalRefreshTokenCacheItem.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheItemTests.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1052
> fix for cache item fromjsonstring with null value [1052]

- src/Microsoft.Identity.Client/Internal/Requests/UsernamePasswordRequest.cs
- tests/Microsoft.Identity.Test.Core.UIAutomation/CoreUiTestConstants.cs
- tests/Microsoft.Identity.Test.Core.UIAutomation/MobileTestHelper.cs
- tests/Microsoft.Identity.Test.Integration/HeadlessTests/B2CUsernamePasswordIntegrationTests.cs
- tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs
- tests/devapps/XForms/XForms/AcquirePage.xaml
- tests/devapps/XForms/XForms/AcquirePage.xaml.cs
- tests/devapps/XForms/XForms/App.xaml.cs
- tests/devapps/XForms/XForms/SettingsPage.xaml
- tests/devapps/XForms/XForms/SettingsPage.xaml.cs
add automation testing for ROPC for Android and iOS
> fix ROPC for b2c

- src/Microsoft.Identity.Client/AuthenticationResult.cs
- src/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/Microsoft.Identity.Client/ConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/DeviceCodeResult.cs
- src/Microsoft.Identity.Client/IAccount.cs
- src/Microsoft.Identity.Client/IByRefreshToken.cs
- src/Microsoft.Identity.Client/IClientApplicationBase.cs
- src/Microsoft.Identity.Client/IConfidentialClientApplication.cs
- src/Microsoft.Identity.Client/MsalError.cs
- src/Microsoft.Identity.Client/MsalServiceException.cs
- src/Microsoft.Identity.Client/MsalUiRequiredException.cs
- src/Microsoft.Identity.Client/Prompt.cs
- src/Microsoft.Identity.Client/UserAssertion.cs
Fixes XML comments which were still referencing AcquireTokenXXAsync methods.
> Fix obsolete XML comments

- src/Directory.Build.props
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/921
> Replace packagelicenseurl with packagelicenseexpression [921]

- src/Microsoft.Identity.Client/Internal/JsonWebToken.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/CacheSerializationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ClientCredentialWithCertTest.cs
> add fallback for netstandard/netcore

- src/Microsoft.Identity.Client/MsalErrorMessage.cs
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/84
> update ios error message for #supportability

- src/Microsoft.Identity.Client/ApiConfig/GetAuthorizationRequestUrlParameterBuilder.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/CoreAssert.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1193
> Fix GetAuthorizationRequestUrl #1193

- src/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
- src/Microsoft.Identity.Client/ApiConfig/Executors/PublicClientExecutor.cs
- src/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenInteractiveParameters.cs
- src/Microsoft.Identity.Client/ApiConfig/SystemWebViewOptions.cs
- src/Microsoft.Identity.Client/IPublicClientApplication.cs
- src/Microsoft.Identity.Client/MsalError.cs
- src/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/Microsoft.Identity.Client/Platforms/Shared/Desktop/OsBrowser/DefaultOsBrowserWebUi.cs
- src/Microsoft.Identity.Client/Platforms/Shared/Desktop/OsBrowser/TcpInterceptor.cs
- src/Microsoft.Identity.Client/Platforms/Shared/NetStdCore/NetStandardWebUIFactory.cs
- src/Microsoft.Identity.Client/Platforms/net45/NetDesktopWebUIFactory.cs
- src/Microsoft.Identity.Client/PublicClientApplication.cs
- src/Microsoft.Identity.Client/TelemetryCore/Internal/Events/ApiTelemetryFeature.cs
- src/Microsoft.Identity.Client/UI/CoreUIParent.cs
- tests/Microsoft.Identity.Test.Unit.net45/ApiConfigTests/AcquireTokenInteractiveBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/ApiConfigTests/Harnesses/AcquireTokenInteractiveBuilderHarness.cs
- tests/Microsoft.Identity.Test.Unit.net45/WebUITests/DefaultOsBrowserWebUiTests.cs
- tests/devapps/NetCoreTestApp/Program.cs
Contains a lot of new public API and associated XML comments. Please review carefully. 
Not currently done: configuration of cmd line
> User configuration for system default browser

- src/Microsoft.Identity.Client/Cache/Items/CacheSerializationContract.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalAccountCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalAppMetadataCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalCacheItemBase.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalCredentialCacheItemBase.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalIdTokenCacheItem.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalItemWithAdditionalFields.cs
- src/Microsoft.Identity.Client/Cache/Items/MsalRefreshTokenCacheItem.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/CacheSerializationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/Resources/CacheFromTheFuture.json
- tests/Microsoft.Identity.Test.Unit.net45/Resources/ExpectedTokenCache.json
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1189
> Change json serialization behavior to ignore null [1189]

- src/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
- src/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
- src/Microsoft.Identity.Client/Internal/ClientCredentialWrapper.cs
- src/Microsoft.Identity.Client/Internal/JsonWebToken.cs
- src/Microsoft.Identity.Client/MsalErrorMessage.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
addressing follow up comments for the WithClientClaims api
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1188
> Updating client WithClaintClaims api.

- tests/devapps/XForms/XForms/TestPage.xaml
- tests/devapps/XForms/XForms/TestPage.xaml.cs
@bgavrilMS forgot to remove this test from the UIautomation tests, as it's covered in the desktop scenario.
> remove consent test from ui automation app...scenario covered in desktop

- src/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1095
> Fix exposure of withparentactivityorwindow for multiplat [1095]

- src/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs
> android webview orientation fix

- src/Microsoft.Identity.Client/Platforms/Android/AndroidPlatformProxy.cs
> Fix #1334 - IsChromeEnabled throws NameNotFoundException

- src/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
- src/Microsoft.Identity.Client/Instance/Discovery/NetworkMetadataProvider.cs
- src/Microsoft.Identity.Client/Utils/UriBuilderExtensions.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AadAuthorityTests.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1292
> Custom Port Authority

- src/Microsoft.Identity.Client/Instance/AuthorityEndpointResolutionManager.cs
- src/Microsoft.Identity.Client/Internal/Requests/ClientCredentialHelper.cs
- src/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/Microsoft.Identity.Client/Utils/StringExtensions.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/InMemoryTokenCache.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/AuthorityTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/OboTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/Infrastructure/SeleniumExtensions.cs
- tests/Microsoft.Identity.Test.Integration.net45/Infrastructure/SeleniumWebUI.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/ConfidentialClientAuthorizationTests.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/KeyVaultSecretsProvider.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/Microsoft.Identity.Test.LabInfrastructure.csproj
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/AadAuthorityTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/StringExtensionTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/RequestValidationHelperTests.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/891
Includes a regression test
> Fix for #891 - JWT audience = tenanted oauth endpoint

- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
- tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs
All tests have associated bugs.
> Disable failing tests

- LibsAndSamples.sln
- build/template-restore-build-libsandsamples.yaml
- src/client/Directory.Build.props
- tests/CacheCompat/CommonCache.Test.MsalJava/pom.xml
1. integrate CG in all builds
2. Update some dependencies that have security issues
> Component governance updates and build integration

- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/TokenCache.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/RefreshInTests.cs
> Fix #1382 - filter by tenantid in client creds

- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
- src/client/Microsoft.Identity.Client/SSHCertificates/SSHCertAuthenticationScheme.cs
- src/client/Microsoft.Identity.Client/SSHCertificates/SSHExtenions.cs
- src/client/Microsoft.Identity.Client/SSHCertificates/SSHExtensions.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Events/ApiTelemetryFeature.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/InteractiveFlowTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/SSHCertificateTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/AuthScheme/SSHCertTests.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
> SSH Cert support

- changelog.txt
> 4.4.0 changelog

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenCommonParameters.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/ITelemetryManager.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Constants/MsalTelemetryBlobEventNames.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/HttpTelemetryContent.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/MatsConverter.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryConstants.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryManager.cs
- src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/HttpTests/HttpManagerTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/AcquireTokenSilentTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/HttpTelemetryTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/TelemetryTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
> [WIP] server side http telemetry

- src/client/Directory.Build.props
upgrade affected package only on affected platforms
> Component governance on net core / net standard

- global.json
thanks @bgavrilMS  for finding this quick and easy fix to my 72 build errors. #guru
> update msbuild sdk

- src/client/Microsoft.Identity.Client/Platforms/uap/UapTokenCacheBlobStorage.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1064
> UWP - delete token cache file if it cannot be read

- src/client/Microsoft.Identity.Client/Internal/Requests/InteractiveRequest.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/MsalException.cs
- src/client/Microsoft.Identity.Client/Platforms/net45/WindowsFormsWebAuthenticationDialogBase.cs
- src/client/Microsoft.Identity.Client/Platforms/uap/WebUI.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
> Fix #1418 by hardening authorization result parsing

- src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
- tests/Microsoft.Identity.Test.Integration.net45/Infrastructure/SeleniumExtensions.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
- tests/devapps/NetCoreTestApp/Program.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
> Fix #1422 - handle protected scopes better

- build/pipeline-ci.yaml
- build/pipeline-pullrequest.yaml
- build/pipeline-releasebuild.yaml
- build/pipeline-uiautomation.yaml
- src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/ASWebAuthenticationPresentationContextProviderWindow.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/SystemWebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/WebviewBase.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBroker.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
If you're testing this w/iOS, remember to switch out the values in the dev test app w/the system browser ones and removed .WithUseEmbeddedWebview(true)
> implement the presentation context for iOS

- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/B2CUsernamePasswordIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/UsernamePasswordIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/DeviceCodeFlowIntegrationTest.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/InteractiveFlowTests.cs
Fixes #1427  and partially fixes #1426
> Re-enable some tests

- build/pipeline-releasebuild.yaml
- build/template-postbuild-code-analysis.yaml
Update template-postbuild-code-analysis.yaml
> Update Roslyn analyzer to latest

- src/client/Directory.Build.props
> Add PackageReleaseNotes to MSAL

- src/client/Microsoft.Identity.Client/Internal/Requests/DeviceCodeRequest.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/DeviceCodeRequestTests.cs
> Fix #1407 - /devicecode endpoint sends errors with 200 OK status

- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabApiConstants.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabResponse.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabServiceApi.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabUser.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabUserHelper.cs
- tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs
Fixing broken tests by updating lab api implementation.
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1460
> Updating lab api implementation to work with new changes

- src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
- src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
- src/client/Microsoft.Identity.Client/ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/TokenCache.cs
- src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
- tests/Microsoft.Identity.Client.Extensions.Msal.UnitTests/MsalCacheHelperTests.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/TokenCacheAccessRecorder.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/DeviceCodeFlowIntegrationTest.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/InteractiveFlowTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/BrokerParametersTest.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/CacheSerializationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/LoadingProjectsTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheV2Tests/TokenCacheV2Tests.cs
- tests/Microsoft.Identity.Test.Unit.net45/OAuthClientTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/BrokerRequestTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/DeviceCodeRequestTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/InteractiveRequestWithCustomWebUiTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/SilentRequestTests.cs
- tests/devapps/DesktopTestApp/TokenCacheHelper.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
This will simplify extension libraries such as Microsoft.Identity.Web
> Expose IsApplicationTokenCache

- build/pipeline-uiautomation.yaml
- src/client/Microsoft.Identity.Client/Platforms/Android/AuthenticationContinuationHelper.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/OboTests.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabUserHelper.cs
> Resolving test issues

- src/client/Microsoft.Identity.Client/Core/Constants.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/devapps/XamarinDev/XamarinDev.Android/Properties/AndroidManifest.xml
- tests/devapps/XamarinDev/XamarinDev/AcquirePage.xaml.cs
- tests/devapps/XamarinDev/XamarinDev/App.xaml.cs
- tests/devapps/XamarinDev/XamarinDev/SettingsPage.xaml.cs
related to this [issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1532)
> fix android activity

- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/OboTests.cs
Do not review, I just want the PR build to run.
> Enable test

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Cache/AdalResult.cs
- src/client/Microsoft.Identity.Client/Cache/AdalResultWrapper.cs
- src/client/Microsoft.Identity.Client/Cache/AdalUserInfo.cs
- src/client/Microsoft.Identity.Client/Cache/CacheFallbackOperations.cs
- src/client/Microsoft.Identity.Client/Cache/Items/MsalAccountCacheItem.cs
- src/client/Microsoft.Identity.Client/Cache/TokenCacheDictionarySerializer.cs
- src/client/Microsoft.Identity.Client/Core/ClientInfo.cs
- src/client/Microsoft.Identity.Client/Core/IdToken.cs
- src/client/Microsoft.Identity.Client/Instance/AdfsWebFingerResponse.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryMetadataEntry.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryResponse.cs
- src/client/Microsoft.Identity.Client/Instance/DrsMetadataResponse.cs
- src/client/Microsoft.Identity.Client/Instance/TenantDiscoveryResponse.cs
- src/client/Microsoft.Identity.Client/Internal/DeviceCodeResponse.cs
- src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs
- src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2ResponseBase.cs
- src/client/Microsoft.Identity.Client/UI/AuthorizationResult.cs
- src/client/Microsoft.Identity.Client/Utils/JsonHelper.cs
- src/client/Microsoft.Identity.Client/WsTrust/UserRealmDiscoveryResponse.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/JsonUtils.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/PerformanceValidator.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/OAuthClientTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/UtilTests/JsonHelperTests.cs
Should fix #1468 and improve MSAL general performance.
> Migrate from DataContractSerializer to Newtonsoft.Json #1468

- src/client/Microsoft.Identity.Client/Platforms/iOS/EmbeddedWebview/MsalAuthenticationAgentUIViewController.cs
> fix for wkwebview on ipad

- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AuthenticationContinuationHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/BrokerResponseCode.cs
I made a few changes to how MSAL processes responses on android to avoid running broker code unnecessarily.
> [Do not merge yet] Broker refactoring proposal

- src/client/Microsoft.Identity.Client/Cache/AdalResult.cs
- src/client/Microsoft.Identity.Client/Cache/AdalResultWrapper.cs
- src/client/Microsoft.Identity.Client/Cache/AdalUserInfo.cs
- src/client/Microsoft.Identity.Client/Core/ClientInfo.cs
- src/client/Microsoft.Identity.Client/Core/IdToken.cs
- src/client/Microsoft.Identity.Client/Instance/AdfsWebFingerResponse.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryMetadataEntry.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryResponse.cs
- src/client/Microsoft.Identity.Client/Instance/DrsMetadataResponse.cs
- src/client/Microsoft.Identity.Client/Instance/TenantDiscoveryResponse.cs
- src/client/Microsoft.Identity.Client/Internal/DeviceCodeResponse.cs
- src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs
- src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2ResponseBase.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/BrokerRequest.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/BrowserTabActivity.cs
- src/client/Microsoft.Identity.Client/PreserveAttribute.cs
- src/client/Microsoft.Identity.Client/UI/AuthorizationResult.cs
- src/client/Microsoft.Identity.Client/WsTrust/UserRealmDiscoveryResponse.cs
- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
- tests/Microsoft.Identity.Test.Common/TestCommon.cs
- tests/Microsoft.Identity.Test.Core.UIAutomation/MobileTestHelper.cs
- tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs
- tests/devapps/XForms/XForms/TestPage.xaml.cs
This replaces jennyf/linker as that branch got too busy :)
> Add [Preserve] attributes for linking and more logging for test

- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AuthenticationContinuationHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/BrokerResponseCode.cs
Fixing exception issue where broker exceptions gets lost.
Removing unneeded calls to broker code when it is not enabled.
Updating error message
> Enabling Android broker.

- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs
Fixing threading issue in interactive broker flow on android.
Fixing null ref during silent broker flow on android.
> Android Broker Fixes

- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
> Disabling android broker

- tests/Microsoft.Identity.Test.Unit.net45/BrokerParametersTest.cs
> fixing test

- src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
- src/client/Microsoft.Identity.Client/Instance/Authority.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- tests/Microsoft.Identity.Test.Unit.net45/ApiConfigTests/AuthorityTests.cs
> Fix for #1606 - use request authority is app authority is not set

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/Internal/Broker/BrokerResponseConst.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AuthenticationContinuationHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/BrokerConstants.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/iOSBroker.cs
Fixing broker cancellation error code.
Broker error codes are now properly added to exceptions
> Fixing broker cancellation error code.

- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBrokerHelper.cs
Changes that did not make it into https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/1668 becuse of git client issues
> Uncommited changes for broker PR

- tests/Microsoft.Identity.Test.LabInfrastructure/LabApiConstants.cs
> Update lab endpoint for test infrastructure.

- src/client/Microsoft.Identity.Client/Internal/Broker/BrokerResponseConst.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/BrokerConstants.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1696
> Broker error message fix

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
- src/client/Microsoft.Identity.Client/Core/ServiceBundle.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryManager.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/NetworkMetadataProvider.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- tests/CacheCompat/CommonCache.Test.Unit/CommonCache.Test.Unit.csproj
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Common/Microsoft.Identity.Test.Common.csproj
- tests/Microsoft.Identity.Test.Common/TestCommon.cs
- tests/Microsoft.Identity.Test.Integration.net45/Microsoft.Identity.Test.Integration.net45.csproj
- tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.netcore.csproj
- tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/PublicClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/InstanceDiscoveryManagerTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/PublicApiInstanceMetadataTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/Microsoft.Identity.Test.Unit.net45.csproj
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/PublicClientApplicationTestsWithB2C.cs
- tests/Microsoft.Identity.Test.Unit.netcore/Microsoft.Identity.Test.Unit.netcore.csproj
> WithInstanceDicoveryMetadata(Uri instanceDiscoveryUri)

- src/client/Microsoft.Identity.Client/Internal/Requests/SilentRequest.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/AcquireTokenSilentTests.cs
> Remove account from cache for bad token error

- src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/Platforms/net45/NetDesktopCryptographyManager.cs
- tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
> 'nebharg/cert exception'

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryManager.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/AppConfigTests/PublicClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/InstanceTests/PublicApiInstanceMetadataTests.cs
> Update method name

- Directory.Build.props
- LibsAndSamples.sln
- build/template-restore-build-libsandsamples.yaml
- src/client/Directory.Build.props
- tests/devapps/NetCoreTestApp/Program.cs
Fixes some minor  warnings reported by NuGet Explorer tool
> Improve  package metadata

- changelog.txt
> Changelog for 4.13.0

- src/client/Microsoft.Identity.Client/Cache/AdalCacheOperations.cs
- src/client/Microsoft.Identity.Client/Cache/AdalTokenCacheKey.cs
- tests/Microsoft.Identity.Test.Common/TestCategories.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/ConfidentialClientAuthorizationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/CacheFallbackOperationsTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/MsalTokenCacheKeysTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/UnifiedCacheTests.cs
> Fix for #1851 - ignore ADAL resource string when fetching RTs

- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/ConfidentialClientAuthorizationTests.cs
> Use tenant id from lab response

- tests/devapps/DesktopTestApp/MainForm.Designer.cs
Remove Acquire silent token authority override button as it do not have a handler.
> Remove Button Acquire silent token with authority override

- src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs
- tests/Microsoft.Identity.Test.Unit.net45/WebUITests/AuthorizationResultTests.cs
Will help with https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1264
> Improve error message for embedded webview http redirect failure

- build/pipeline-uiautomation.yaml
- src/client/Microsoft.Identity.Client/Platforms/iOS/EmbeddedWebview/MsalAuthenticationAgentUIViewController.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/ASWebAuthenticationPresentationContextProviderWindow.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/SystemWebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/WebviewBase.cs
- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
Removing dependency on IsAppcenterBuild.
Updating mac os image
> UI Automation Updates.

- build/template-publish-packages-and-symbols.yaml
> fix build label

- src/client/Microsoft.Identity.Client/Platforms/Android/AuthenticationContinuationHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/EmbeddedWebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/SystemWebview/SystemWebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/WebviewBase.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/AuthenticationContinuationHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/iOSBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/EmbeddedWebview/EmbeddedWebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/SystemWebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/WebviewBase.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1620 plus add more logging
> Fail if redirect uri is not correct on iOS + broker

- src/client/Microsoft.Identity.Client/Internal/Broker/BrokerInteractiveRequestComponent.cs
- src/client/Microsoft.Identity.Client/Internal/Broker/BrokerResponseConst.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentBrokerAuthStrategy.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/MsalServiceExceptionFactory.cs
- src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/BrokerRequestTests.cs
fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1938
> Adding better handling of broker service exceptions and additional logging

- src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/OboTests.cs
> Pull id token along AT when looking in the cache for OBO

- Libs.sln
- src/client/Microsoft.Identity.Client/Http/RedirectUriHelper.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/Broker/iOSBroker.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/HttpTests/RedirectUriHelperTests.cs
> Fix for #1995 - bad redirect uri validation ios broker

- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryTokenCacheAccessor.cs
> Improve perf around token cache ConcurrentDictionary operations

- LibsAndSamples.sln
- src/client/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuthConstants.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryTokenCacheAccessor.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/TokenCache.cs
- src/client/Microsoft.Identity.Client/Utils/ScopeHelper.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/CoreAssert.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/AuthorityTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/Infrastructure/SeleniumExtensions.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/DeviceCodeFlowIntegrationTest.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/FociTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/InteractiveFlowTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/SeleniumTests/SSHCertificateTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/CacheSerializationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CacheTests/TokenCacheTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/RequestsTests/SilentRequestTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/UtilTests/ScopeHelperTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/pop/PopAuthenticationSchemeTests.cs
- tests/devapps/DesktopTestApp/MsalUserAccessTokenControl.cs
- tests/devapps/XamarinDev/XamarinDev/AccessTokenCacheItemDetails.xaml.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1980
> Replace SortedSet with HashSet to improve perf

- src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs
- tests/devapps/XamarinDev/XamarinDev.Android/Properties/AndroidManifest.xml
> remove "sign-in" hard-coded in android embedded webview

- changelog.txt
Update the changelog for 4.18 to include the fix done for DefaultConnectionLimit.
> Update 4.18 changelog

- tests/Microsoft.Identity.Test.Common/TestConstants.cs
> Updating thumbprint for tests

- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2045
> Improving the error details for hand shake issues during brokered authentication on android.

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
- src/client/Microsoft.Identity.Client/Instance/Discovery/InstanceDiscoveryManager.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Http/HttpTelemetryManager.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Constants/MsalTelemetryBlobEventNames.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Events/ApiEvent.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/ConfidentialClientIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.net45/HeadlessTests/RegionalAuthIntegrationTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/CoreTests/RegionDiscoveryProviderTests.cs
- tests/Microsoft.Identity.Test.Unit.net45/TelemetryTests/RegionalTelemetryTests.cs
> Add telemetry data for msal

- src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreHttpClientFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/netdesktop/Http/NetDesktopHttpClientFactory.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/SimpleHttpClientFactory.cs
fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2034
> Adding thread safety to the HttpClient

- changelog.txt
> Updating changelog for 4.19.0

- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBroker.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2062
> Resolving parsing issue with broker error

- src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
> Expose the certificate on CCA objects

- src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
> Add link for details for state mismatch exception

- src/client/Microsoft.Identity.Client/AuthenticationResult.cs
- src/client/Microsoft.Identity.Client/Internal/Broker/BrokerResponseConst.cs
- src/client/Microsoft.Identity.Client/Internal/IServiceBundle.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentBrokerAuthStrategy.cs
- src/client/Microsoft.Identity.Client/Internal/ServiceBundle.cs
- tests/Microsoft.Identity.Test.Common/TestCommon.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
- tests/Microsoft.Identity.Test.Unit/RequestsTests/BrokerRequestTests.cs
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2078
Tested
> Broker UI required fix when no tokens are in the broker

- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
potential fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/1914
> WIP Handling java error in broker operations

- src/client/Directory.Build.props
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopPlatformProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/uap/UapPlatformProxy.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamGetAccountsTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
This is the easiest way to disable WAM. I had to comment a bit of code, but this should not impact productivity when looking at WAM again.
> Disable WAM integration

- changelog.txt
For some reason, I created the branch, but not the PR ?
> Update the changelog to 4.20.1

- src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
Fixes #1883 
@henrik-me, is it what you expected, or would you want more?
> Add explanations on how to use .WithClaims

- src/client/Microsoft.Identity.Client/Platforms/iOS/IosHttpClientFactory.cs
#2164 
@bgavrilMS i couldn't test this as my provisioning profile is no longer working :( that lasted like 1 week.
> fix ios http stack bug

- build/pipeline-ci.yaml
Ci build should also run nightly
> Updating schedule for CI build

- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
@bgavrilMS not sure if this is what you meant
#2151
> add more logs for android broker request

- src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
> fix spelling + spacing xml .withbuilder

- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
> spelling + spacing fixes to msal error messages

- src/client/Microsoft.Identity.Client/TelemetryCore/Http/HttpHeaderSantizer.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Http/HttpTelemetryManager.cs
- tests/Microsoft.Identity.Test.Unit/UtilTests/HttpHeaderSantizerTests.cs
> Fix for 1881 - sanitize error codes for http header transport

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/IAppConfig.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/MigrationAid/MigrationAid.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
@jmprieur when do we want to remove the migration aid?
> few more spelling changes

- build/pipeline-releasebuild.yaml
release building running [here](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=668063&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1876155b-e1ef-55fc-d177-9285fc268cbf)
> add net 5 build task

- src/client/Microsoft.Identity.Client/Platforms/Android/SystemWebview/AuthenticationActivity.cs
> uncomment commented code for custom tabs on AndroidX

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
> fix nuget description

- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
> [WAM] Don't force prompt when logging in user with the account picker

- src/client/Microsoft.Identity.Client/Internal/Constants.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/WsTrust/CommonNonInteractiveHandler.cs
- src/client/Microsoft.Identity.Client/WsTrust/UserRealmDiscoveryResponse.cs
- src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/UsernamePasswordIntegrationTests.cs
- tests/Microsoft.Identity.Test.Unit/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
going to sync w/ests on suggestions for #2169
> throw better error message for ropc w/msa

- src/client/Microsoft.Identity.Client/MigrationAid/MigrationAid.cs
> fix intellisense for oboasync

- LibsAndSamples.sln
- tests/CacheCompat/CommonCache.Test.MsalNode/CommonCache.Test.MsalNode.csproj
- tests/CacheCompat/CommonCache.Test.MsalNode/NodeLanguageExecutor.cs
- tests/CacheCompat/CommonCache.Test.MsalNode/NodeScript/index.js
- tests/CacheCompat/CommonCache.Test.MsalNode/NodeScript/package-lock.json
- tests/CacheCompat/CommonCache.Test.MsalNode/NodeScript/package.json
- tests/CacheCompat/CommonCache.Test.MsalNode/Program.cs
- tests/CacheCompat/CommonCache.Test.Unit/CacheExecutionTests.cs
- tests/CacheCompat/CommonCache.Test.Unit/CommonCache.Test.Unit.csproj
- tests/CacheCompat/CommonCache.Test.Unit/Utils/CacheProgramFactory.cs
- tests/CacheCompat/CommonCache.Test.Unit/Utils/CacheProgramType.cs
> Cache compat with MSAL.node tests

- src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsWebUi/CustomWebBrowser.cs
https://identitydivision.visualstudio.com/IDDP/_queries/edit/1234429
> Fixing TSA issue 1234429 

- build/pipeline-ci.yaml
> Disabling tests

- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentClientAuthStrategy.cs
- tests/Microsoft.Identity.Test.Unit.net45/PublicApiTests/AcquireTokenSilentTests.cs
#2294 revert bad_token error fix for 4.17.1
This will merge to the branch that was last committed for the tag and then we will release it as 4.17.2
> Revert bad_token error fix

- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/CacheSilentStrategy.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/AcquireTokenSilentTests.cs
#2294 PR to revert Bad_token fix for master branch
> Revert fix for bad_token error

- src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
- src/client/Microsoft.Identity.Client.Desktop/WamExtension.cs
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AccountPicker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/win32/Splash.Designer.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/win32/Splash.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/win32/Splash.resx
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/win32/Win32Window.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/WindowsNativeMethods.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/devapps/NetCoreTestApp/NetCoreTestApp.csproj
- tests/devapps/NetCoreTestApp/Program.cs
- tests/devapps/NetFxConsoleTestApp/NetFxConsoleApp.csproj
- tests/devapps/NetFxConsoleTestApp/Program.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
- tests/devapps/WAM/NetCoreWinFormsWam/NetCoreWinFormsWAM.csproj
- tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml.cs
- tests/devapps/WAM/NetDesktopWpf/NetDesktopWpfWAM.csproj
- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Experience (see the grey splash screen..). I could add a progress bar ... thoughts?
Implication of the splash screen - the splash screen means Win.Forms is used. So we cannot offer WAM from pure NetStandard.
**Tested**: 
  |   | ui thread | non ui thread
-- | -- | -- | --
net classic | wpf | x | x
  | win forms | x | x
  | console | x | x
net core 3 | win forms | x | x
  | console | x | x
net 5 | win forms | x | x
  | console | x | x
uwp |   | x | x
> Fix for WAM + console apps

- build/pipeline-ci.yaml
- build/pipeline-pullrequest.yaml
- build/template-run-device-auth-tests.yaml
- tests/Microsoft.Identity.Test.Integration.Win8/DeviceAuthenticationTests.cs
- tests/Microsoft.Identity.Test.Integration.Win8/Microsoft.Identity.Test.Integration.Win8.csproj
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2207
Tests are working
> Fix for device auth tests

- src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/client/Microsoft.Identity.Client/Extensibility/MsaPassthroughConfig.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AadPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AccountPicker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IMsaPassthroughHandler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IWamPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IWebAccountProviderFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPassthroughHandler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamAdapters.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamExtensions.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WebAccountProviderFactory.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/DedicatedThreadSynchronisationContext.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamMsaPassthroughTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.Designer.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Remaining work for MSA-PT scenario: 
- a better way for apps to tell MSAL they are MSA-PT
- better discovery of AAD guest accounts (AAD plugin does not correctly report guest accounts, so there is some advanced logic there).
> [WAM] MSA-PT support via SAML transfer token

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreCryptographyManager.cs
- src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopCryptographyManager.cs
- src/client/Microsoft.Identity.Client/Platforms/netstandard13/NetStandard13CryptographyManager.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CryptographyManager.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManager.cs
- tests/Microsoft.Identity.Test.Performance/CryptoManagerTests.cs
- tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
> Add RSA mapping to NetStandard and NetCore crypto managers.

- src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
- src/client/Microsoft.Identity.Client/Internal/ServiceBundle.cs
- src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/DeviceAuthHelper.cs
- tests/Microsoft.Identity.Test.Unit/OAuthClientTests.cs
Waiting for customer validation before pushing.
> Fix for #2359

- src/client/Microsoft.Identity.Client/Http/HttpManager.cs
- src/client/Microsoft.Identity.Client/Region/RegionDiscoveryProvider.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs
Add logging in HttpManager plus minor logging updates in RegionDiscoveryProvider.
> Add logging in HttpManager plus minor logging updates in RegionDiscoveryProvider.

- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidAccountManagerBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidBrokerStaticHelper.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/Broker/AndroidContentProviderBroker.cs
> updates to content provider

- tests/devapps/WAM/NetCoreWinFormsWam/Form1.Designer.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
- tests/devapps/WAM/UWPWam/MainPage.xaml.cs
Added extra logging, enlarged control sizing to make the whole value visible.
> Minor improvements to WAM dev apps to help with testing.

- changelog.txt
Updating changelog to include 4.26.0
> 4.26.0 Change log

- src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/RefreshInTests.cs
Refresh in logic for OBO
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2389
> Adding refresh_in logic for OBO flow

- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/Platforms/Features/DesktopOS/StaTaskScheduler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AadPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AccountPicker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IAccountPickerFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPassthroughHandler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamAdapters.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamExtensions.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WebAccountProviderFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WebTokenRequestResultWrapper.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WebView2WebUi/WebView2WebUi.cs
- src/client/Microsoft.Identity.Client/Platforms/net5win/Net5WamInterop.cs
- src/client/Microsoft.Identity.Client/Platforms/net5win/Net5WebUiFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/net5win/Net5WinPlatformProxy.cs
Please see https://docs.microsoft.com/en-us/dotnet/standard/analyzers/platform-compat-analyzer and 
https://github.com/dotnet/designs/blob/main/accepted/2020/platform-checks/platform-checks.md
> Add support for Win 7, 8 10 (<17663) to NET5

- src/client/Microsoft.Identity.Client/Prompt.cs
- tests/devapps/DesktopTestApp/DesktopTestApp.csproj
- tests/devapps/DesktopTestApp/MainForm.Designer.cs
- tests/devapps/DesktopTestApp/MainForm.cs
- tests/devapps/XamarinDev/XamarinDev/AcquirePage.xaml.cs
Issue #2463
Also updates Xamarin Dev App and DesktopTestApp
> Add Prompt.Create option

- build/platform_and_feature_flags.props
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/SystemWebViewOptions.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/IosWebUIFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/SystemWebview/SystemWebUI.cs
Added option to hide prompt in iOS. Disposed SemaphoreSlim after use to release resource.
#2131
> Option to hide prompt in iOS + disposed semaphore.

- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AccountPicker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
For issues #2566 and #2608 + nits.
Tested with NetFx, NetCore, Net5 and console and win forms apps.
> Update account picker splash screen

- src/client/Microsoft.Identity.Client/AuthenticationResult.cs
- src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
- src/client/Microsoft.Identity.Client/Cache/Items/CacheSerializationContract.cs
- src/client/Microsoft.Identity.Client/Http/HttpManager.cs
- src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
- src/client/Microsoft.Identity.Client/Internal/Logger/DurationLogHelper.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/Utils/Base64UrlHelpers.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationResultTests.cs
- make tokenType public.
- remove un-needed string.format
- spelling fixes
- stopwatch.startnew()
#2637
> - small updates, see below.

- build/template-build-and-prep-automation.yaml
Fixes # .
Fixing release build
additional file copying
**Testing**
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=778722&view=results
none
> Fix for release build

- build/template-desktop-unit-and-automation.yaml
- build/template-run-unit-tests.yaml
> Run tests on NET5 as well

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Unit/AppConfigTests/PublicClientApplicationBuilderTests.cs
Fixes #2543  .
**Testing**
unit
Extra logic added only in corner-case scenario.
> Fix for #2543 - take into account WithTenant()

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByIntegratedWindowsAuthParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByUsernamePasswordParameterBuilder.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
> Fix some warnings

- src/client/Microsoft.Identity.Client/IClientApplicationBase.cs
See also https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/troubleshooting#getaccountasync-doesnt-return-any-account-in-clouds-scenarios
> improving the XML comment for GetAccountAsync

- README.md
Updated README.md with new loyalty survey link
New CustomerVoice survey link added to README file
**Testing**
None
None
> Updated README with new survey link

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
Adding a customer voice survey link to the NuGet package metadata.
> Adding a survey link to the NuGet package

- src/client/Microsoft.Identity.Client/Cache/CacheImpl/AbstractDistribuitedCacheSerializer.cs
- src/client/Microsoft.Identity.Client/Cache/CacheImpl/InMemoryPartitionedCacheSerializer.cs
- tests/devapps/WebApi/Controllers/OboController.cs
- tests/devapps/WebApi/Misc/DistributedCacheWithDelay.cs
- tests/devapps/WebApi/Misc/EventBasedLRUCache.cs
Remove the changes to implement cache delay for perf testing from MSAL code and add it to the perf tests.
> Remove the cache penalty delay from code

- src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
Fixes # .
- propagate cancellation token to `waitAynnc`
- remove app hash ID since it is not reliable.
**Testing**
> Propagate cancellation to cache semaphore and remove app id

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByAuthorizationCodeParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
- src/client/Microsoft.Identity.Client/ApiConfig/GetAuthorizationRequestUrlParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByAuthorizationCodeParameters.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenCommonParameters.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/GetAuthorizationRequestUrlParameters.cs
- src/client/Microsoft.Identity.Client/Internal/Broker/BrokerInteractiveRequestComponent.cs
- src/client/Microsoft.Identity.Client/Internal/Constants.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeExchangeComponent.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/AuthCodeRequestComponent.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/Utils/CoreHelpers.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/UsernamePasswordIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/InteractiveFlowTests.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit/RequestsTests/IntegratedWindowsAuthUsernamePasswordTests.cs
- tests/devapps/DesktopTestApp/PublicClientHandler.cs
Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2725
Adding CCS helper methods.
Adding CCS hint to OBO flow
**Testing**
Added tests
Evaluating
> Adding CCS helper methods.

- src/client/Microsoft.Identity.Client.Desktop/WamExtension.cs
- src/client/Microsoft.Identity.Client/ApiConfig/WindowsBrokerOptions.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- tests/Microsoft.Identity.Test.Integration.Win8/BrokerOnWin8Tests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
- tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
- tests/devapps/WAM/UWPWam/MainPage.xaml.cs
Issue #2700.
Will need to update https://aka.ms/msal-net-wam docs 
This just removes WithExperimentalFeatures
> Remove WithExperimentalAPI from WAM

- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
- tests/devapps/RegionalTestApp/Program.cs
Fixes # .
Build automation certificates
> Updating cert thumbprints

- src/client/Microsoft.Identity.Client/WwwAuthenticateParameters.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WwwAuthenticateParametersIntegrationTests.cs
- tests/Microsoft.Identity.Test.Unit/WwwAuthenticateParametersTests.cs
Fixes # .
#2679 
Produce the parameters from the WWW-Authenticate header
**Testing**
Yes. added unit tests + integration test + manual testing in separate app and with Id Web.
cc: @jmprieur to help w/testing 
n/a
> add WWW-Authenticate Params

- src/client/Microsoft.Identity.Client/ApiConfig/AbstractConfidentialClientAcquireTokenParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/OAuth2/Throttling/SingletonThrottlingManager.cs
- src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
- src/client/Microsoft.Identity.Client/UserAssertion.cs
Fixes https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2756
> Fix syntax in <list> XML comments

- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs
> Add a test for WithAzureRegion(null)

- src/client/Microsoft.Identity.Client/Cache/SuggestedWebCacheKeyFactory.cs
- tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/SuggestedWebCacheKeyTests.cs
Fixes # .
#2643 
Add suggested web cache key for remove accounts call.
**Testing**
Added unit test
None
> Add suggested web cache key for remove accounts

- src/client/Microsoft.Identity.Client/ApiConfig/Executors/AbstractExecutor.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Executors/ClientApplicationBaseExecutor.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Executors/PublicClientExecutor.cs
Fixes # .
Removed unused field and parameter
Cleanup
**Testing**
The existing should work.
NA
> Clean up internal class

- src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
> Add public ctor for TokenCacheNotificationArgs

- src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/RegionDiscoveryProviderTests.cs
Fixes #2772
validate region string to have uri valid chars (space is not one of them)
**Testing**
unit
region discovery is cached in memory (static), no perf impact
> Add region string validation

- src/client/Microsoft.Identity.Client/Internal/Requests/IntegratedWindowsAuthRequest.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/WsTrust/CommonNonInteractiveHandler.cs
Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2731
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2752
Adding better error message for IWA failures
**Testing**
Manual testing
Negligible
> Updating IWA error messages

- Directory.Build.props
- src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
> add deterministic to ci build

- changelog.txt
Updated readme for the release
**Testing**
NA
NA
> Updated Readme

- src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
- src/client/Microsoft.Identity.Client/MigrationAid/TokenCache.MigrationAid.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/Utils/OptionalSemaphoreSlim.cs
- tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
> Fix settting CacheSyncronization flag from options

- changelog.txt
> MSAL 4.35.1 changelog.

- src/client/Microsoft.Identity.Client/Internal/Constants.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/MsalServiceExceptionFactory.cs
- tests/Microsoft.Identity.Test.Unit/ExceptionTests/MsalExceptionTests.cs
Fixes #2808.
Filtered error for 50196 and updated the doc
**Testing**
NA. Could not repro.
None
> Error message filtering as per error

- src/client/Microsoft.Identity.Client/Instance/AadAuthority.cs
- src/client/Microsoft.Identity.Client/Instance/AdfsAuthority.cs
- src/client/Microsoft.Identity.Client/Instance/Authority.cs
- src/client/Microsoft.Identity.Client/Instance/B2CAuthority.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AadPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IWamPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPassthroughHandler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamMsaPassthroughTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/AadAuthorityTests.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Fixes #2822
- simplify the MSA-PT protocol by getting the transfer token directly from the MSA plugin
- fix silent acquisition of tokens by forcing /organization 
**Testing**
ut
> WAM + MSA-passthrough revamp

- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- tests/Microsoft.Identity.Test.Integration.Win8/DeviceAuthenticationTests.cs
Fixes # .
Fix for https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2821
Reenabling test
**Testing**
Automated test
none
> Win 8 test

- src/client/Microsoft.Identity.Client/AppConfig/PopAuthenticationConfiguration.cs
- src/client/Microsoft.Identity.Client/AuthScheme/PoP/PoPAuthenticationScheme.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSyncronizationTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PopAuthenticationSchemeTests.cs
> Add custom nonce support to POP

- src/client/Microsoft.Identity.Client/Cache/Items/MsalAccessTokenCacheItem.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/CoreAssert.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
Fixes # .
AccessToken_WithRefresh_FromMsalResponseJson test
> fix for AccessToken_WithRefresh_FromMsalResponseJson

- src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/OnBehalfOfRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/CacheSilentStrategy.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/SilentRequestHelper.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/RefreshInTests.cs
- tests/Microsoft.Identity.Test.Unit/TelemetryTests/HttpTelemetryTests.cs
Fixes # 2795.
Acquire Refresh token in the background thread.
**Testing**
Existing tests
Should improve perf
> Refresh token on background thread

- build/credscan-exclusion.json
- build/pipeline-releasebuild.yaml
- build/template-build-and-run-all-tests.yaml
- build/template-prebuild-code-analysis.yaml
Adding missing policheck to build
> Adding Policheck to build

- src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/SilentRequest.cs
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidPlatformProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/iOS/iOSPlatformProxy.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/AbstractPlatformProxy.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/PlatformProxyFactoryTests.cs
Fixes # 2897.
Fixes Silent flow for the broker
**Testing**
manual
NA
> Added back CanBrokerSupportSilentAuth

- build/template-build-and-run-all-tests.yaml
Fixes # .
Removes Android and iOS AppCenter tests from the build pipeline. This is only for the hotfix release.
**Testing**
> Remove Android and iOS AppCenter tests from build

- build/template-build-and-run-all-tests.yaml
> Re-add app center tests

- src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/RegionDiscoveryProviderTests.cs
Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2803#
Modifying region acquisition from env variable
**Testing**
> Modifying region acquisition from env variable

- src/client/Microsoft.Identity.Client/AuthScheme/PoP/PoPAuthenticationScheme.cs
- src/client/Microsoft.Identity.Client/AuthScheme/PoP/PoPProviderFactory.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PopAuthenticationSchemeTests.cs
Fixes # .
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2891
Adding additional check to pop token
**Testing**
Unit test
N/A
> Updating POP Token Test

- src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
- src/client/Microsoft.Identity.Client/UI/AuthorizationResult.cs
- tests/Microsoft.Identity.Test.Unit/WebUITests/AuthorizationResultTests.cs
Fixes 2991 .
URL parameters are analyzed to check if it is user cancelled and corresponding result is returned.
**Testing**
Unit Test
None
> Throws MSALClientException when back is pressed

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/EmbeddedWebViewOptions.cs
- src/client/Microsoft.Identity.Client/AppConfig/ApplicationOptions.cs
- src/client/Microsoft.Identity.Client/Cache/Adal/CacheData.cs
- src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs
- src/client/Microsoft.Identity.Client/ITokenCacheSerializer.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/TokenCache.cs
> Hide a few deprecated methods, so that they do not show up in IntelliSense

- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
Fixes #2990 
- reword the log error
- log warning instead of error
**Testing**
> Fix for #2990 - reword in-memory cache only warning for web apps

- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
> Fix sign out guest account in WAM

- src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
- src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/TokenCacheNotificationArgs.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/CacheSerializationTests.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheNotificationTests.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
- tests/devapps/WAM/UWPWam/MainPage.xaml.cs
Fixes #3008 
Add correlation id to the cache notification args
**Testing**
unit 
> Add correlation id to notification args

- build/template-install-keyvault-secrets.yaml
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.WithRegion.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests2.cs
- tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/ConfidentialAppSettings.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/CertificateHelper.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
> Remove unused cert

- changelog.txt
> Changelog 4.39.0.

- build/template-build-and-run-all-tests.yaml
> Disable on-prem tests

- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
Fixes # 
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3073
Modified cache logging to be more clear
> Modified cache logging to be more clear

- src/client/Microsoft.Identity.Client/Internal/Logger/MsalLogger.cs
This will make it easier to find logs in LogsMiner
> Output the date in Universal format in the logs

- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WebView2WebUi/WinFormsPanelWithWebView2.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/WindowsFormsWebAuthenticationDialogBase.cs
- src/client/Microsoft.Identity.Client/UI/EmbeddedUiCommon.cs
- tests/Microsoft.Identity.Test.Unit/WebUITests/EmbeddedUiTests.cs
> Allow res pages in embedded webview

- changelog.txt
Fixes # 
Updated Changelog
NA
**Testing**
NA
NA
> Updated for 4.40

- src/client/Microsoft.Identity.Client/ApiConfig/WindowsBrokerOptions.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AccountPicker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IAccountPickerFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Fixes #3125 
Add a new option to WAM - a header text.
**Testing**
> Add a new WAM option - header text (account picker only)

- tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.NetCore.csproj
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/Microsoft.Identity.Test.Integration.NetFx.csproj
Just a test to validate a proposed doc change
> Update a test to use System.Text.Json

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/Platforms/Features/DefaultOSBrowser/DefaultOsBrowserWebUi.cs
- src/client/Microsoft.Identity.Client/Platforms/Mac/MacPlatformProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/netcore/ApiConfig/SystemWebViewOptions.cs
- src/client/Microsoft.Identity.Client/Platforms/netcore/NetCorePlatformProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/netdesktop/NetDesktopPlatformProxy.cs
- src/client/Microsoft.Identity.Client/Platforms/netstandard13/ApiConfig/SystemWebViewOptions.cs
- src/client/Microsoft.Identity.Client/Platforms/netstandard13/NetStandard13PlatformProxy.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/AbstractPlatformProxy.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/CancellationTests.cs
- tests/Microsoft.Identity.Test.Unit/WebUITests/DefaultOsBrowserWebUiTests.cs
Fixes # 
#3051 
Open microsoft-edge from linux
**Testing**
Tested manually from linux
None
> Open edge from linux

- src/client/Microsoft.Identity.Client/AuthScheme/PoP/PoPProviderFactory.cs
- src/client/Microsoft.Identity.Client/Cache/CacheKeyFactory.cs
- src/client/Microsoft.Identity.Client/Internal/ServiceBundle.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedAppTokenCacheAccessor.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/TestTimeService.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/LegacyPopTest.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/InMemoryPartitionedTokenCacheAccessorTests.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/CryptoProviderTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PopAuthenticationSchemeTests.cs
- tests/devapps/NetCoreTestApp/NetCoreTestApp.csproj
> Add pop kid to client_credentials cache key

- src/client/Microsoft.Identity.Client.Desktop/WamExtension.cs
- src/client/Microsoft.Identity.Client/Platforms/net5win/Net5WinPlatformProxy.cs
Fixes # 
Adding/Updating logs for WAM. 
**Testing**
none
n/a
> Adding additional logs for WAM

- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AadPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IMsaPassthroughHandler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/Interfaces/IWebAccountProviderFactory.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPassthroughHandler.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/MsaPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamBroker.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WebAccountProviderFactory.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamMsaPassthroughTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Fixes #3157
- add the transfer token flow for MSA-PT + MSA silent scenarios
**Testing**
manual
some unit testing
initial request will be much slower, because it now involves to 2 AAD calls
access tokens are cached so subsequent requests should not be as slow
> Add the transfer token flow for MSA Passthrough + MSA silent scenarios

- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
> Add a few app coordinates to the WAM sample

- build/template-pack-and-sign-all-nugets.yaml
Fixes # 
Fix path variables in package sign yaml.
**Testing**
> Fix path variables in package sign yaml.

- tests/devapps/Intune-xamarin-Android/MainActivity.cs
- tests/devapps/Intune-xamarin-Android/PCAWrapper.cs
- tests/devapps/Intune-xamarin-Android/Properties/AndroidManifest.xml
Fixes # 
Sampel App ported to Lab4
Updated the Lab IDs
**Testing**
Manual
None
> App ported to Lab4

- changelog.txt
Notes for 4.43.0 plus minor changes to previous release notes.
> MSAL changelog 4.43.0

- src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
> Bump Source Link version (tool change)

- changelog.txt
> Update changelog for 4.43.2

- tests/devapps/Intune-xamarin-Android/PCAWrapper.cs
- tests/devapps/Intune-xamarin-ios/MainViewController.cs
Fixes # 
Broken Build
Fix the app
**Testing**
Manual test of bot Android and iOS dev Apps for Intune
None
> Fix the test app

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
Fixes # 
Fix the warning in release build.
**Testing**
> Remove the AppTokenProviderParameters from csproj

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/PopAuthenticationConfiguration.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
Fixes # 
ATS extra check for auth scheme
> ATS extra check for auth scheme

- README.md
Fixes # 
Update README.md to include Microsoft.Identity.Broker Nuget reference
**Testing**
n/a
doc update
> Update README.md to include Microsoft.Identity.Broker Nuget reference

- .github/ISSUE_TEMPLATE/documentation.md
Minor update to issue templates.
> Automatically add documentation label to doc issues

- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
Fixes # 
DevEx message when withBroker is called needs an update
updating message when withBroker is called (spacing issues)
**Testing**
n/a
none
> WithBroker() DevEx Message spacing issues

- src/client/Microsoft.Identity.Client/ApiConfig/AbstractConfidentialClientAcquireTokenParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/AuthScheme/PoP/PoPAuthenticationScheme.cs
- src/client/Microsoft.Identity.Client/AuthScheme/PoP/PopBrokerAuthenticationScheme.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/InteractiveRequest.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/AuthenticationSchemeTests.cs
- tests/Microsoft.Identity.Test.Unit/TestBase.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PopAuthenticationSchemeTests.cs
Fixes # 
Adding new AuthScheme for pop with broker
Adding new AuthScheme for pop with broker
**Testing**
Unit Testing
> Adding new AuthScheme for pop with broker

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
Demonstrates experimental API `OnBeforeTokenRequest`
> Add an integration test to demonstrate OnBeforeTokenRequest

- src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
Fixes #3354 
Fix Expires In on Runtime Broker WAM
**Testing**
manual testing
none
> Fix Expires In on Runtime Broker

- tests/devapps/WAM/NetCoreWinFormsWam/Form1.Designer.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Fixes # 
Add lab test info to WAM DevApps. This will help with release testing and minimize time taken with copy paste lab info. 
**Testing**
tested with DevApps
None : test setup update
> Add lab test info to WAM DevApps

- src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
> Ensure region configured by user is logged

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/LoggerTests.cs
> Mark new API as experimental

- src/client/Microsoft.Identity.Client/Platforms/netstandard13/NetStandard13WebUIFactory.cs
Update error message for net standard/UAP.
> Update error message for net standard/UAP.

- tests/CacheCompat/CommonCache.Test.Unit/CommonCache.Test.Unit.csproj
- tests/Microsoft.Identity.Test.Common/Microsoft.Identity.Test.Common.csproj
- tests/Microsoft.Identity.Test.Integration.Win8/Microsoft.Identity.Test.Integration.Win8.csproj
- tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.NetCore.csproj
- tests/Microsoft.Identity.Test.Integration.netfx/Microsoft.Identity.Test.Integration.NetFx.csproj
- tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
Fixes # 
Fix component governance warnings for Newtonsoft
Update versions for dependencies indicated here: https://identitydivision.visualstudio.com/IDDP/_componentGovernance/98561?_a=alerts&typeId=7241230&alerts-view-option=active
**Testing**
> Fix component governance warnings for Newtonsoft

- tests/devapps/WAM/NetCoreWinFormsWam/Form1.Designer.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
Fixes #3371
Adding Perf testing for ATS to Silent flows on the Dev App
**Testing**
with the dev app
none
> Perf testing WAM #3371

- Directory.Build.props
- tests/Microsoft.Identity.Test.Common/Microsoft.Identity.Test.Common.csproj
- tests/Microsoft.Identity.Test.LabInfrastructure/Microsoft.Identity.Test.LabInfrastructure.csproj
- tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml.cs
- tests/devapps/XamarinDev/XamarinDev/CachePage.xaml.cs
> Remove some build warnings

- src/client/Microsoft.Identity.Client/PlatformsCommon/Interfaces/IPlatformProxy.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests2.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/ConfidentialAppSettings.cs
- tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/FociTests.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/KeyVaultSecretsProvider.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabServiceApi.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabUserHelper.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/Microsoft.Identity.Test.LabInfrastructure.csproj
Merges #3446 into main after tests are run.
> Replace obsolete KeyVault library (#3446)

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
Fixes # 
Packaging issues
Updated the packaging
**Testing**
Manual
None
> Updated the target frameworks

- MauiStatus.md
- changelog.txt
> Update as per 4.46.0-preview

- src/client/Microsoft.Identity.Client/ConfidentialClientApplication.cs
- src/client/Microsoft.Identity.Client/IConfidentialClientApplication.cs
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
> Hard deprecate AcquireTokenSilent(scopes, login_hint)

- tests/Microsoft.Identity.Test.Integration.netcore/WAM/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/MsalAssert.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
Fixes # 
Adding scopes check to Broker integration tests
Adding scopes check to Broker integration tests
**Testing**
running tests
n/a
> Adding scopes check to Broker integration tests

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
Fixes # 
Support MAUI conditionally
Condition for compiling MAUI
**Testing**
Unit + integration
NA
> Support MAUI conditionally

- tests/Microsoft.Identity.Test.Android.UIAutomation/Microsoft.Identity.Test.Android.UIAutomation.csproj
- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
- tests/Microsoft.Identity.Test.Core.UIAutomation/Microsoft.Identity.Test.UIAutomation.Infrastructure.csproj
- tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.NetCore.csproj
- tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
- tests/Microsoft.Identity.Test.iOS.UIAutomation/Microsoft.Identity.Test.iOS.UIAutomation.csproj
- tests/Microsoft.Identity.Test.iOS.UIAutomation/iOSTests.cs
- tests/devapps/RegionalTestApp/Program.cs
- Update NUnit and related dependencies to the latest versions to remove some obsoletion warnings.
- Remove old reference in perf project.
**Testing**
Pass.
> Mostly update NUnit dependencies for mobile tests

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/Platforms/Android/AndroidHttpClientFactory.cs
Fixes # 
Android conditional compilation for Maui
Add conditional access to platform code
**Testing**
regular unit + integration tests
None.
> Conditional Maui for platform code

- .github/pull_request_template.md
Adds the Documentation section to the pull request template to remind to update any relevant documentation related to the PR changes.
> Add documentation section to pull_request_template

- tests/devapps/DesktopTestApp/DesktopTestApp.csproj
Remove old dev app (Related to #3463)
> Remove Aria Telemetry

- src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
- src/client/Microsoft.Identity.Client/Instance/DstsAuthority.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/DstsAuthorityTests.cs
> Fix IWA for dsts

- src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.Designer.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
Fixes #3477 
Sadly this depends on a Windows update, so I could not test this. But logically it should work. 
**Testing**
> Add multi-cloud support to WAM

- tests/Microsoft.Identity.Test.Android.UIAutomation/Microsoft.Identity.Test.Android.UIAutomation.csproj
- tests/Microsoft.Identity.Test.Core.UIAutomation/Microsoft.Identity.Test.UIAutomation.Infrastructure.csproj
- tests/Microsoft.Identity.Test.iOS.UIAutomation/Microsoft.Identity.Test.iOS.UIAutomation.csproj
> Remove obsolete KeyVault references

- .editorconfig
- .gitattributes
Fixes #3425
Consistent line endings. gitattributes inspired by https://github.com/dotnet/runtime/blob/main/.gitattributes
> Line feed config

- tests/devapps/DesktopTestApp/DesktopTestApp.csproj
- tests/devapps/XForms/XForms.Android/MainActivity.cs
- tests/devapps/XForms/XForms.Android/XForms.Android.csproj
- tests/devapps/XForms/XForms.UWP/App.xaml.cs
- tests/devapps/XForms/XForms.UWP/XForms.UWP.csproj
- tests/devapps/XForms/XForms.iOS/AppDelegate.cs
- tests/devapps/XForms/XForms.iOS/XForms.iOS.csproj
- tests/devapps/XamarinDev/XamarinDev.Android/MainActivity.cs
- tests/devapps/XamarinDev/XamarinDev.iOS/AppDelegate.cs
Cleanup the last of the Aria references...   Can't find anymore now finally :)
> Cleanup last Aria references

- src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
> Bad region log message

- tests/devapps/MauiApps/MauiAppB2C/MSALClient/PCAWrapperB2C.cs
Fixes #
Ref: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3543
Used GetAccountsByPolicy.
**Testing**
Manual
None
NA
> Used GetAccountsByPolicy

- tests/Microsoft.Identity.Test.Integration.netstandard/Microsoft.Identity.Test.Integration.NetStandard.csproj
Fixes #
Fixes OneBranch build
Changing project to net5 instead of net6
**Testing**
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=966474&view=results
> Changing integration project to net5

- src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
Fixes #3550 
Explicit support broker for .net 461 as requested by VS installer and VS feedback teams
**Testing**
dev apps 
none
> Adding Explicit  .net 461 support to new WAM broker

- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedAppTokenCacheAccessor.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedUserTokenCacheAccessor.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
Minor clarifications in caching logs (stemming from the migration question discussion).
> Minor clarifications in caching logs.

- tests/Microsoft.Identity.Test.Unit/Throttling/ThrottlingAcceptanceTests.cs
Fixes #
#3587 
Ignore failing tests until resolved.
**Testing**
> Ignore tests

- tests/devapps/WAM/NetFrameworkWam/Program.cs
Fixes #
Update NetDesktopWinFormsWAM Program.cs add missing required header
**Testing**
none
none
> Update NetDesktopWinFormsWAM Program.cs add missing required header

- src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
fixed the other issues in another PR
> fix spelling of posession to possession

- MauiStatus.md
just a few updates @SameerK-MSFT
> minor updates to maui.md file

- build/pipeline-ci.yaml
- build/pipeline-pullrequest.yaml
- build/template-android-appcenter-tests.yaml
- build/template-build-and-run-all-tests.yaml
- build/template-build-ios-automation.yaml
- build/template-ci-and-pr.yaml
- build/template-ios-appcenter-tests.yaml
- build/template-restore-build-libsandsamples.yaml
- build/template-run-all-tests.yaml
- build/template-run-unit-tests.yaml
In previous PR the build configurations were refactored, the config was changed from Debug to Release in some places. So I updated to use Release everywhere. Plus my guess is maybe it'll make the builds faster too?
> Use Release configuration.

- build/template-build-and-prep-automation.yaml
- build/template-pack-and-sign-packages.yaml
Fixes #
Fixes build by applying workaround described here: https://github.com/actions/runner-images/issues/6082
**Testing**
> Temp build fix (Workaround)

- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
Fixes #
Adds WithExperimentalFeatures to Dev App so PoP can be tested with the new broker
**Testing**
Dev App
none
> Adds WithExperimentalFeatures to Dev App so PoP can be tested with the new broker

- build/template-build-and-run-all-tests.yaml
- build/template-build-ios-automation.yaml
Fixes #3454
Readed AppCenter test for Xamarin forms
**Testing**
AppCenter does it.
None
NA
> Run iOS AppCenter tests

- LibsAndSamples.sln
- changelog.txt
Fixes #
#3618 
Very minor changes only, no code impact:
- Update contents of changelog.txt to point to the correct new CHANGELOG.md location
- Solution file: point to the markdown version of the changelog file, in stead of the plain text version
**Testing**
No explicit testing has been performed.
Not expected
> Fixes: [Documentation] New changelog URL results in 404 #3618

- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- tests/Microsoft.Identity.Test.Unit/TelemetryTests/HttpTelemetryTests.cs
Fixes #
#3547 
Log exceptions which are not converted to MsalExceptions to telemetry
**Testing**
Unit test
None
None
> Log exceptions to telemetry

- src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
Fixes : Interop packaging issue
native interop update
**Testing**
dev apps
none
> Update Microsoft.Identity.Client.NativeInterop to Version 0.12.3

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/LoggerTests.cs
> Remove experimental flag from logging

- src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
- src/client/Microsoft.Identity.Client/Extensibility/PublicClientApplicationExtensions.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/PublicClientApplication.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
Fix typos. Changes to public methods are ok, since they weren't released yet.
> Fix typos.

- src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Cache/Items/MsalCacheItemBase.cs
- src/client/Microsoft.Identity.Client/OAuth2/MsalTokenResponse.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/AadPlugin.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WamBroker/WamAdapters.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/BrokerRequestTests.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Fixes #3637 
**Testing**
unit + manual
there is new logic in hot path, but it is behind the "IsMultiCloud" flag.
> Fix for #3637 - use correct authority in multi-cloud + WAM scenario

- src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
Fixes #
Update RuntimeBroker.cs for Null account
**Testing**
Dev Apps
none
> [WAM Broker] Adding Null account check on RemoveAccountAsync API 

- tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml
- tests/devapps/WAM/NetDesktopWpf/MainWindow.xaml.cs
Fixes #
[WAM Broker]WPF Dev App Update
**Testing**
the app
none
> [WAM Broker]WPF Dev App Update

- src/client/Microsoft.Identity.Client/Http/HttpManager.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/CacheSilentStrategy.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/SilentRequestHelper.cs
- src/client/Microsoft.Identity.Client/MsalServiceException.cs
- src/client/Microsoft.Identity.Client/OAuth2/TokenClient.cs
- tests/Microsoft.Identity.Test.Unit/ExceptionTests/MsalExceptionTests.cs
> Update logic that calculates if exception is retry-able

- build/pipeline-perf-tests-automation.yaml
- tests/Microsoft.Identity.Test.Performance/AcquireTokenForClientCacheTests.cs
- tests/Microsoft.Identity.Test.Performance/AcquireTokenForOboCacheTests.cs
- tests/Microsoft.Identity.Test.Performance/AcquireTokenNoCacheTests.cs
- tests/Microsoft.Identity.Test.Performance/Helpers/PerfConstants.cs
- tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
- tests/Microsoft.Identity.Test.Performance/Program.cs
- tests/Microsoft.Identity.Test.Performance/TokenCacheTests.cs
Partially #3645
Update some constants, update BDN version, update summary results table.
**Testing**
> Minor fixes to perf test project

- src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
- src/client/Microsoft.Identity.Client.Broker/WamAdapters.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
Fixes #
Add extra logging when RemoveAccountAsync fails
**Testing**
Dev Apps
none
> [WAM Broker] Add logging for RemoveAccountAsync failure

- src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
Fixes #
Use "Microsoft.Identity.Client.NativeInterop" Version="0.12.4"
Also include runtime, build and lib assets by adding `all`.
**Testing**
Dev Apps
None
> Update Broker csproj to use "Microsoft.Identity.Client.NativeInterop" Version="0.12.4"

- build/template-build-and-run-all-tests.yaml
- build/template-build-android-automation.yaml
- build/template-build-ios-automation.yaml
Fixes #
Android build is failing
Add frameworks for Android
**Testing**
NA
NA
> Test Android Fix

- src/client/Microsoft.Identity.Client/MsalServiceException.cs
> Make MsalServiceException.StatusCode.set internal

- CHANGELOG.md
Update CHANGELOG.md for MSAL 4.47.1
> Update CHANGELOG.md for MSAL 4.47.1

- src/client/Microsoft.Identity.Client/ApiConfig/WindowsBrokerOptions.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
> Hide 2 APIs which are only for 1p

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
Fixes #3693
Removed Target Framework for MacCatalyst
**Testing**
Manually test apps and inspect the package
None
> Remove MacCatalyst

- CHANGELOG.md
Update CHANGELOG.md for MSAL 4.47.2
> Update CHANGELOG.md for MSAL 4.47.2

- build/template-pack-and-sign-all-nugets.yaml
Fixes #3749 
Change from Nuget command to dotnet command
**Testing**
Ran the test
NA
NA
> Fixed the issue with Signature verification

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByUsernamePasswordParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenInteractiveParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Executors/ClientApplicationBaseExecutor.cs
- src/client/Microsoft.Identity.Client/AppConfig/ApplicationConfiguration.cs
- src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Cache/CacheKeyFactory.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/AuthenticationRequestParameters.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/OAuth2/Throttling/HttpStatusProvider.cs
- src/client/Microsoft.Identity.Client/OAuth2/Throttling/UiRequiredProvider.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/TokenCache.cs
- tests/Microsoft.Identity.Test.Common/TestCommon.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/InstanceDiscoveryManagerTests.cs
- tests/Microsoft.Identity.Test.Unit/pop/PoPTests.cs
Fixes #3767
- We need a better way to figure out if an app config is for CCA or for PCA. Since app config is mutable object, best is to rely on ctor.
- 
**Testing**
> Refactor IsConfidentialClient and remove experimental flag from PCA POP

- src/client/Microsoft.Identity.Client/AuthScheme/TokenType.cs
Fixes #
Make the TokenType enum internal
**Testing**
> Make the enum internal

- tests/Microsoft.Identity.Test.Unit/PublicApiTests/RetryPolicyTests.cs
> retry test fix

- tests/Microsoft.Identity.Test.Android.UIAutomation/androidTests.cs
B2CLocalEditPolicyAcquireTokenTest is failing, disabling to get the release out
> Update androidTests.cs and disable B2CLocalEditPolicyAcquireTokenTest

- src/client/Microsoft.Identity.Client/Instance/Discovery/RegionDiscoveryProvider.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.WithRegion.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithRegionTests.cs
Fixes #3252 
See issue for more details.
> Use <region>.login.microsoft.com for regional ESTS-R

- src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
- src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/MsalLoggerValidator.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/WamLoggerValidator.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
- tests/devapps/WAM/NetFrameworkWam/NetDesktopWinFormsWAM.csproj
- tests/devapps/WAM/NetFrameworkWam/Program.cs
- tests/devapps/XForms/XForms/LogPage.xaml.cs
- tests/devapps/XForms/XForms/MainPage.xaml.cs
- tests/devapps/XForms/XForms/TestPage.xaml.cs
Fixes #
Adds unit tests
Added Unit tests
**Testing**
Unit Tests
None
No doc needed
> MSAL Runtime logging integration

- src/client/Microsoft.Identity.Client/ITokenCacheSerializer.cs
> Updater docs around ADAL 2 MSAL cache migration

- src/client/Microsoft.Identity.Client.Broker/RuntimeBroker.cs
> Fix PII messages

- src/client/Microsoft.Identity.Client.Broker/BrokerExtension.cs
Fixes #3885
Mention that WAM preview doesn't support UWP. Also updated [WAM wiki](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/WAM).
> Update WithBrokerPreview XML comment.

- src/client/Microsoft.Identity.Client/Internal/ClientCredential/CertificateClientCredential.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
Fixes #3896 
remove validation 
**Testing**
sadly no unit test failed, so this block of code was not tested
less code -> faster operation
> Fix for 3896 - remove min key size check

- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenOnBehalfOfParameters.cs
Add additional logs to clarify which long running OBO method was used for the OBO request.
> Add extra long-running OBO logs.

- build/pipeline-perf-tests-automation.yaml
Fixes #
Perf build
**Testing**
> Add dotnet core 3.x target

- tests/devapps/WAM/NetFrameworkWam/Form1.Designer.cs
- tests/devapps/WAM/NetFrameworkWam/Form1.cs
Fixes n/a 
- Dev App Update
- Added a checkbox to make runtime logs optional
- By default logs are turned off. Check the `Enable Runtime Logging` checkbox to view Runtime logs
**Testing**
Dev App
none
> [WAM] Make dev app logs for runtime optional

- src/client/Microsoft.Identity.Client/MsalError.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/InMemoryPartitionedAppTokenCacheAccessor.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/InMemoryPartitionedTokenCacheAccessorTests.cs
Fixes #3218
Add error message for combined flat user and app cache. See issue for more info.
> Add error message for combined flat user and app cache.

- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentitySource.cs
Fixes #3908 
**Testing**
Updated https://aka.ms/msal-net-managed-identity with details.
> Update exception to indicate correlation id

- build/template-build-and-prep-automation.yaml
- build/template-build-android-automation.yaml
- build/template-desktop-unit-and-automation.yaml
- build/template-run-unit-tests.yaml
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
- tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
Fixes #
Disabling .Net 7 target to fix build
Disabling .Net 7 target to fix build
**Testing**
> Disabling .Net 7 target

- src/client/Microsoft.Identity.Client/ApiConfig/AbstractAcquireTokenParameterBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
Updated documentation for issue 2929.
**Testing**
NA
None
> Updated doc for consumers authority

- tests/devapps/WAM/MSIX/WPF.Package/WPF.Package.wapproj
Fixes 
Update MSIX packaging test app to use the latest Interop
**Testing**
Dev App
None
> Update MSIX packaging test app to use the latest Interop

- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/PublicClientApplication.cs
- tests/Microsoft.Identity.Test.Integration.Win8/BrokerOnWin8Tests.cs
- tests/Microsoft.Identity.Test.Unit/AppConfigTests/PublicClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Unit/BrokerTests/WamTests.cs
- tests/devapps/NetCoreTestApp/Program.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
Reverts AzureAD/microsoft-authentication-library-for-dotnet#3928
> Obsolete IsBrokerAvailable on mobile platforms

- README.md
Some of the documentation links in the README were out of date. This PR addresses those.
> Update README with latest links

- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
Fix some build warnings and test proj
> Internal cleanup of warnings

- tests/Microsoft.Identity.Test.Unit/AppConfigTests/ConfidentialClientApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit/CryptographyTests.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
Fixes #
Release build roslyn errors
Add suppress message
**Testing**
> Add suppress message for roslyn analyzers for tests

- tests/devapps/Managed Identity apps/ManagedIdentityAppVM/Program.cs
Add WithExperimentalFeatures to Dev App
> Add WithExperimentalFeatures to MSI Dev App

- tests/devapps/WAM/MSIX/WPF.Package/Package.appxmanifest
Update publisher name for WPF test project
> Update publisher name for WPF test project

- tests/devapps/Managed Identity apps/MSIHelperService/AzureFunction/GetEnvironmentVariables.cs
- tests/devapps/Managed Identity apps/MSIHelperService/Controllers/EnvironmentVariablesController.cs
- tests/devapps/Managed Identity apps/MSIHelperService/Controllers/MSITokenController.cs
- tests/devapps/Managed Identity apps/MSIHelperService/Helper/MSIHelper.cs
- tests/devapps/Managed Identity apps/MSIHelperService/RunBookJobStatus.cs
> MI : fix few dev app warnings

- LibsAndSamples.sln
- ManagedIdentityWebApi/Controllers/AppServiceController.cs
- ManagedIdentityWebApi/ManagedIdentityWebApi.csproj
- ManagedIdentityWebApi/Program.cs
- ManagedIdentityWebApi/Properties/launchSettings.json
- ManagedIdentityWebApi/appsettings.Development.json
- ManagedIdentityWebApi/appsettings.json
Fixes #
Add a dev app for managed identity app service
**Testing**
> Add dev app to test managed identity on app service

- build/template-build-android-automation.yaml
- build/template-restore-build-libsandsamples.yaml
Changes in this fix
- For MAUI Dev Apps include only MAUI Android workload
> For MAUI Dev Apps include only MAUI Android workload

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OboTests2.cs
Update Service Principal OBO RT test after fix on AAD side.
> Fix Service Principal OBO RT test.

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ManagedIdentityTests.cs
> Fix few more cases where test names have spaces

- src/client/Microsoft.Identity.Client/AppConfig/ManagedIdentityApplicationBuilder.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ManagedIdentityTests.cs
- tests/Microsoft.Identity.Test.Unit/AppConfigTests/ManagedIdentityApplicationBuilderTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/AppServiceTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/AzureArcTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/CloudShellTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ServiceFabricTests.cs
- tests/devapps/Managed Identity apps/ManagedIdentityAppVM/Program.cs
- tests/devapps/Managed Identity apps/ManagedIdentityWebApi/Controllers/AppServiceController.cs
Fixes #4125 
Remove experimental flag from MI
**Testing**
> Remove experimental flag from MI

- Directory.Build.props
Update to Microsoft.Identity.Client.NativeInterop version 0.13.8
>  Update to Microsoft.Identity.Client.NativeInterop version 0.13.8

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/CiamIntegrationTests.cs
Update Ciam Integration Tests and remove the QP pointing to ESTS test slice
> Update Ciam Integration Tests and remove the QP pointing to ESTS test slice

- src/client/Microsoft.Identity.Client/Cache/CacheLevel.cs
issue as seen [here](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1104287&view=logs&j=47387727-c0d7-5e0b-1dc0-d55e5ab2b07c&t=3f6ac161-9cb1-5510-9a1a-2f4ceea7d21d&l=21)
> Fix for badly formed XML -- 'Expected an end tag for element 'summary'.'

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ManagedIdentityTests.cs
Office move is now complete, trying to see if Azure ARC tests work now
> [Managed identity] Enable Azure Arc tests 

- src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
Update XML comment based on user interaction.
> Update WithAzureRegion XML comment

- src/client/Microsoft.Identity.Client/WwwAuthenticateParameters.cs
> Update docs #4166

- build/pipeline-releasebuild.yaml
- build/template-build-and-run-all-tests.yaml
> Enable CodeQL

- src/client/Microsoft.Identity.Client/IPublicClientApplication.cs
- src/client/Microsoft.Identity.Client/PublicClientApplication.cs
Updates the XML comments with some documentation tweaks.
> Documentation updates

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- tests/devapps/WAM/UWPWam/MainPage.xaml.cs
We are now able to install the Windows 10 SDK (v 17763), I will follow that up with a[ OneBranch PR](https://identitydivision.visualstudio.com/IDDP/_git/MSAL.NET-OneBranch/pullrequest/9068). This fix will add back UAP to OneBranch again.
> [OneBranch] Adding UAP back into the pipeline

- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManager.cs
- tests/Microsoft.Identity.Test.Performance/AcquireTokenNoCacheTests.cs
- tests/Microsoft.Identity.Test.Performance/CryptoManagerTests.cs
- tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
- tests/Microsoft.Identity.Test.Performance/Program.cs
NoCache tests were failing due to refactoring of Mock Http Handler
> Fix MockHttpManager, fix perf tests

- .github/auto_assign.yml
- .github/workflows/auto_assign_reviewer.yml
> Auto assign reviewers

- src/client/Microsoft.Identity.Client/Cache/TokenCacheJsonSerializer.cs
- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/CacheFailureTests.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
- tests/devapps/WAM/NetCoreWinFormsWam/Form1.cs
> Improve error message when cache deserialization fails

- CHANGELOG.md
- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/AzureCloud.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
Fixes #4256 
Remove keyword national 
**Testing**
> Remove keyword "national" to fix policheck

- CHANGELOG.md
> Update CHANGELOG.md for MSAL 4.55 release

- src/client/Microsoft.Identity.Client/Platforms/netdesktop/Native/RSACng.cs
> Fix typo in RSACng.cs

- src/client/Microsoft.Identity.Client/json/Serialization/DefaultContractResolver.cs
Fixes #
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2665899
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2665900
These work items were generated through a static analysis scan by PoliCheck. For more information on PoliCheck, please click here: http://toolbox/policheck.
More information on this specific issue, including guidance, can be found in the bugs listed above.
This work item contains 2 'policheck' issue(s) detected in https://identitydivision.visualstudio.com/IDDP/_git/MSAL.NET-OneBranch. Click the 'Scans' tab (above bugs) to review results. If the 'Scans' tab is not present, please open the attached SARIF in one of the viewers below.
> Fix Policheck issues

- tests/Microsoft.Identity.Test.Performance/Program.cs
> Fix ADO perf build

- build/pipeline-perf-tests-automation.yaml
- tests/Microsoft.Identity.Test.Performance/Program.cs
> Fix perf builds again

- src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/WamAdapters.cs
While investigating an issue for the photo app, the logs were misleading. Updating to `RuntimeBroker`
> Update logging for Runtime Broker

- src/client/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj
Update cache extensions to use netstandard 2.0 only
> Add netcore3.1 and net45 to cache extensions

- .github/ISSUE_TEMPLATE/bug_report.yaml
> Simplify bug template

- tests/Microsoft.Identity.Test.Common/Core/Helpers/ECDCertificatePopCryptoProvider.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/RSACertificatePopCryptoProvider.cs
- Changes padding to Pss.
- Uses a different constructor for ECDSA singing.
> Fixes for CodeQL + spelling fixes.

- src/client/Microsoft.Identity.Client/Cache/Items/MsalRefreshTokenCacheItem.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
Fixes #3957
Print refresh token cache keys to logs
**Testing**
Unit tests. Manual testing
> Print refresh token cache keys to logs

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.WithRegion.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OnBehalfOfTests.cs
- tests/devapps/RegionalTestApp/Program.cs
Fixes #4381
Remove regional flag from tests; there'll be a different way to run these tests on build machines.
> Update regional tests.

- build/template-build-android-automation.yaml
- build/template-restore-build-libsandsamples.yaml
> Add Java 11 to build for android

- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/DeviceAuthHelper.cs
> Fix for #4445 - do not advertise pkeyauth on Mac, Linux

- src/Directory.Build.props
- src/client/Microsoft.Identity.Client.Broker/Microsoft.Identity.Client.Broker.csproj
- tests/Directory.Build.props
- tests/Microsoft.Identity.Test.Integration.netcore/Microsoft.Identity.Test.Integration.NetCore.csproj
- tests/Microsoft.Identity.Test.Integration.netfx/Microsoft.Identity.Test.Integration.NetFx.csproj
- tests/Microsoft.Identity.Test.Performance/Microsoft.Identity.Test.Performance.csproj
- tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
- tests/devapps/DesktopTestApp/DesktopTestApp.csproj
- tests/devapps/FociTestApp/FociTestApp.csproj
- tests/devapps/Intune-xamarin-Android/Intune-xamarin-Android.csproj
- tests/devapps/Intune-xamarin-ios/IntuneMAMSampleiOS.csproj
- tests/devapps/MultiCloudTestApp/MultiCloudTestApp.csproj
- tests/devapps/NetFxConsoleTestApp/NetFxConsoleApp.csproj
- tests/devapps/WAM/NetDesktopWpf/NetDesktopWpfWAM.csproj
- tests/devapps/WAM/NetFrameworkWam/NetDesktopWinFormsWAM.csproj
- tests/devapps/WAM/UWPWam/UWP standalone WAM.csproj
Related to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2184#issue-1824984342
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#defaults
> update langVersion to 12

- src/client/Microsoft.Identity.Client.Extensions.Msal/Accessors/LinuxKeyRingAccessor.cs
- src/client/Microsoft.Identity.Client.Extensions.Msal/Shared/SharedUtilities.cs
- src/client/Microsoft.Identity.Client/ClientApplicationBase.cs
- src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsManagedIdentitySource.cs
- tests/Microsoft.Identity.Test.Unit/CacheExtension/TestHelper.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheNotificationTests.cs
since less code. and already used in other locations in the codebase
> use some default literals

- src/client/Microsoft.Identity.Client/Platforms/Features/WebView2WebUi/WebView2WebUi.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WebView2WebUi/WinFormsPanelWithWebView2.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/WebUI.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/WinFormsLegacyWebUi/WindowsFormsWebAuthenticationDialogBase.cs
- src/client/Microsoft.Identity.Client/Prompt.cs
- tests/Microsoft.Identity.Test.Performance/Helpers/CertificateHelper.cs
- tests/devapps/WebApi/Misc/TestSize.cs
> remove some redundant casts where is applies

- build/template-run-integration-tests.yaml
- build/template-run-unit-tests.yaml
Fixes #
Resolves missing tests in pipeline
Updating value for classic test run to enable logic to work properly
**Testing**
> Resolving missing test issue in classic pipeline

- src/client/Microsoft.Identity.Client/Platforms/Features/RuntimeBroker/WamAdapters.cs
since it has not been assigned
> remove redundant string.IsNullOrEmpty(authorityUrl)

- src/client/Microsoft.Identity.Client/Utils/StringExtensions.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/StringExtensionTests.cs
> remove StringReplace

- src/client/Microsoft.Identity.Client/AppConfig/AuthorityInfo.cs
> remove duplicate AbsolutePath.Substring in ValidateAndCreateAuthorityUri

- tests/devapps/Managed Identity apps/MSIHelperService/Controllers/EnvironmentVariablesController.cs
- tests/devapps/Managed Identity apps/MSIHelperService/Controllers/MSITokenController.cs
- tests/devapps/Managed Identity apps/MSIHelperService/MSIHelperService.csproj
- tests/devapps/Managed Identity apps/MSIHelperService/Program.cs
- tests/devapps/Managed Identity apps/MSIHelperService/Properties/launchSettings.json
- tests/devapps/Managed Identity apps/MSIHelperService/readme.md
- tests/devapps/Managed Identity apps/ManagedIdentityWebApi/Controllers/AppServiceController.cs
- tests/devapps/Managed Identity apps/ManagedIdentityWebApi/ManagedIdentityWebApi.csproj
- tests/devapps/Managed Identity apps/ManagedIdentityWebApi/Program.cs
- tests/devapps/Managed Identity apps/ManagedIdentityWebApi/Properties/launchSettings.json
Fixes #
[Security Bug](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzureAD%2Fmicrosoft-authentication-library-for-dotnet%2Fblob%2F6f7017410e630dbe6851afd95b16e0520fbf77db%2Ftests%2Fdevapps%2FManaged%2520Identity%2520apps%2FMSIHelperService%2FProgram.cs%23L30&data=05%7C02%7CNeha.Bhargava%40microsoft.com%7Ce80460b41c17411968cb08dc21a952ca%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638422258356301625%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=hDPgGk%2FH%2FD9YxhKfLq2eyD75hppBUr%2FeqJtXPO94LH8%3D&reserved=0)
Remove swagger from MSiHelperService
**Testing**
> Remove swagger from the helper service

- src/client/Microsoft.Identity.Client/WwwAuthenticateParameters.cs
- tests/Microsoft.Identity.Test.Unit/WwwAuthenticateParametersTests.cs
Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4416
Updating wwwAuthenticateParsing to handle v2.0 path
**Testing**
unit testing
> Updating wwwAuthenticateParsing to handle v2.0

- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/ClientCredentialsTests.cs
Fixes #
Build break
remove collection literals 
**Testing**
build tests 
none
> Collection literals is not supported by the onebranch agents

- tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/ConfidentialAppSettings.cs
Fixes #
Build break
Update test to use lab ppe tenant
**Testing**
build tests
none
> Update test to use lab ppe tenant

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/design_proposal.md
- .github/ISSUE_TEMPLATE/engineering_task.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Main update is to note that Blazor WebAssembly issues should be created in the MSAL.js repo.
Other minor updates.
> Update issue templates

- src/client/Microsoft.Identity.Client/Cache/Items/MsalCacheKeys.cs
- src/client/Microsoft.Identity.Client/Cache/Items/MsalRefreshTokenCacheItem.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/Internal/Events/ApiEvent.cs
- src/client/Microsoft.Identity.Client/TelemetryCore/TelemetryConstants.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/OnBehalfOfServicePrincipalTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/PoPTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/UsernamePasswordIntegrationTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/HttpTelemetryRecorder.cs
- tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/ConfidentialClientAuthorizationTests.cs
- tests/Microsoft.Identity.Test.Integration.netfx/SeleniumTests/InteractiveFlowTests.cs
- tests/Microsoft.Identity.Test.Unit/TelemetryTests/HttpTelemetryTests.cs
- tests/Microsoft.Identity.Test.Unit/TelemetryTests/RegionalTelemetryTests.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
> Fix some analyzer warnings

- src/client/Microsoft.Identity.Client/AppConfig/AbstractApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Instance/Oidc/OidcRetrieverWithCache.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpMessageHandler.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/GenericAuthorityTests.cs
- tests/devapps/Net5TestApp/Program.cs
- tests/devapps/NetFxConsoleTestApp/Program.cs
> Support for ODIC with query parameters (without ExtraQP)

- src/client/Microsoft.Identity.Client/Cache/CacheSessionManager.cs
- src/client/Microsoft.Identity.Client/Http/HttpManager.cs
- src/client/Microsoft.Identity.Client/Internal/Logger/DurationLogHelper.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- src/client/Microsoft.Identity.Client/Utils/MeasureDurationResult.cs
- src/client/Microsoft.Identity.Client/Utils/StopWatchService.cs
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/4615
> Stopwatch Updates

- src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- tests/Microsoft.Identity.Test.Integration.netfx/HeadlessTests/GenericAuthorityTests.cs
- tests/Microsoft.Identity.Test.Unit/ApiConfigTests/AuthorityTests.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/InstanceTests/GenericAuthorityTests.cs
- tests/devapps/Net5TestApp/Program.cs
> WithOidcAuthority

- src/client/Microsoft.Identity.Client/Internal/Requests/RequestBase.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTestsWithB2C.cs
> Fix for #4652

- build/InstallAndroid.ps1
Update InstallAndroid.ps1 and install android 31
> [OneBranch] Update InstallAndroid.ps1 and install android 31 

- tests/Microsoft.Identity.Test.Core.UIAutomation/CoreUiTestConstants.cs
- tests/Microsoft.Identity.Test.Integration.netfx/Infrastructure/SeleniumExtensions.cs
Fixes #
Selenium tests failing on one branch
**Testing**
> Try to fix the tests failing on one branch

- src/client/Microsoft.Identity.Client.Broker/BrokerExtension.cs
- src/client/Microsoft.Identity.Client/AppConfig/ConfidentialClientApplicationBuilder.cs
Fixes #
Warnings on the one branch build
**Testing**
> Fix xml comments warnings

- CHANGELOG.md
Update CHANGELOG.md for MSAL 4.60.1
> Update CHANGELOG.md for MSAL 4.60.1

- src/client/Microsoft.Identity.Client/Platforms/Android/EmbeddedWebview/AuthenticationAgentActivity.cs
> Ashok's fix

- CHANGELOG.md
> Updating changelog for 4.60.3

- tests/Microsoft.Identity.Test.LabInfrastructure/LabUserHelper.cs
> Fix lab api concurrency issue

- src/client/Microsoft.Identity.Client/AppConfig/PublicClientApplicationBuilder.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/DesktopOS/Kerberos/TicketCacheReader.cs
- src/client/Microsoft.Identity.Client/Platforms/Features/DesktopOS/Kerberos/TicketCacheWriter.cs
> Update Kerberos docs and make some api internal

- tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
- tests/Microsoft.Identity.Test.LabInfrastructure/LabServiceApi.cs
Fixes 
Remove authenticating to Lab API using secret and use cert instead.
**Testing**
> Update to use cert

- src/client/Microsoft.Identity.Client/Platforms/netcore/NetCoreWebUIFactory.cs
> Fix typo in error message

- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsTests.NetFwk.cs
- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/PoPTests.NetFwk.cs
- tests/Microsoft.Identity.Test.Integration.netcore/Infrastructure/ConfidentialAppSettings.cs
Fixes 
Update the location of secret
**Testing**
> Update secret location for CCA tests

- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/CiamIntegrationTests.cs
Ignore few CIAM tests in OneBranch due to some infra issues
> Ignore CIAM tests in OneBranch

- Directory.Packages.props
> Update NativeInterop version to 0.16.1

- src/client/Microsoft.Identity.Client/AppConfig/AssertionRequestOptions.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ConfidentialClientApplicationTests.cs
> Make the AssertionRequestOptions mutable (testable)

- CHANGELOG.md
> Changelog for 4.61.2

- tests/Microsoft.Identity.Test.LabInfrastructure/LabAuthenticationHelper.cs
Update LabAuthenticationHelper.cs to use new lab scope
> Update LabAuthenticationHelper.cs to use new lab scope

- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForClientParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenForManagedIdentityParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenOnBehalfOfParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenSilentParameterBuilder.cs
- src/client/Microsoft.Identity.Client/Extensibility/ICustomWebUI.cs
Docs only
Fixes #4808 and #4809
> Doc fix for 4808 and 4809

- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/CiamIntegrationTests.cs
Migrating CIAM tests to use new tenant (CIAM 6)
**Testing**
> Updating CIAM tests to use new CIAM Lab 6 tenant

- Directory.Packages.props
Fix Component Governance Alerts for Azure.Security.KeyVault packages
Fixes #4829
update to latest azure keyvault packages
**Testing**
build tests
none
> Fix Component Governance Alerts for Azure.Security.KeyVault packages

- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs
- src/client/Microsoft.Identity.Client/ManagedIdentityApplication.cs
- tests/Microsoft.Identity.Test.Common/Core/Helpers/ManagedIdentityTestUtil.cs
- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ManagedIdentityTests.NetFwk.cs
> Remove static caching of managed identity source

- src/client/Microsoft.Identity.Client/Http/IHttpManager.cs
Fixes #
Update comments to match the params
**Testing**
> Fix warnings on the build

- .github/workflows/label-issues.yml
Ensures that appropriate tags are used for inbound issues.
> Add automated logic for tagging issues

- .github/workflows/label-issues.yml
Adds a check for the issue body to make sure that I can validate that the issue was successfully obtained.
> Update issue tagger action

- .github/workflows/label-issues.yml
> Fix token use

- src/client/Microsoft.Identity.Client.Extensions.Msal/Microsoft.Identity.Client.Extensions.Msal.csproj
Adds a reference to the README so it shows up on NuGet.org
> Update with NuGet README

- tests/devapps/KerberosConsole/KerberosConsole.csproj
Fixes #4882
fixes https://identitydivision.visualstudio.com/IDDP/_componentGovernance/MSAL.NET-OneBranch?_a=alerts&typeId=10379874&alerts-view-option=active 
update to latest https://www.nuget.org/packages/Kerberos.NET
**Testing**
none 
none
> Update KerberosConsole.csproj  to use latest Kerberos.NET package

- src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/AppServiceManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/AzureArcManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/CloudShellManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ServiceFabricManagedIdentitySource.cs
Fixes Remove the link references to Azure SDK for managed identity
**Testing**
> Remove the links to Azure SDK for managed identity since these will be updated soon.

- Directory.Packages.props
> Update interop package to 0.16.2

- src/client/Microsoft.Identity.Client/Internal/JsonWebToken.cs
- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
Fixes #
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4868
**Testing**
> Changing the handling of client claims to use JSON

- LibsAndSamples.sln
- tests/devapps/WAM/WAMMauiApp/WAMMauiApp/WAMMauiApp.csproj
More details about the warnings are here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/4884
> Fix warnings in WAMMauiApp

- CHANGELOG.md
- src/client/Microsoft.Identity.Client/ApiConfig/AcquireTokenByUsernameAndPasswordConfidentialParameterBuilder.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Executors/ConfidentialClientExecutor.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AbstractAcquireTokenConfidentialClientParameters.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByAuthorizationCodeParameters.cs
- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenByUsernamePasswordParameters.cs
- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/UsernamePasswordIntegrationTests.NetFwk.cs
- tests/Microsoft.Identity.Test.Unit/PublicApiTests/ClientCredentialWithCertTest.cs
> Fix for 4913 - sendX5C for ROPC CCA

- build/NuGet.config
Partially Fixes #4893 (main fix in [OneBranch](https://dev.azure.com/IdentityDivision/IDDP/_git/MSAL.NET-OneBranch/pullrequest/14465))
- OneBranch build updates for internal builds 
- NuGet.config update in github to support test job 
**Testing**
builds
n/a
> Add IDDP NuGet feed for internal consumption 

- src/client/Microsoft.Identity.Client/Extensibility/AbstractConfidentialClientAcquireTokenParameterBuilderExtension.cs
fix the warning - XML comment has badly formed XML
> fix the warning - XML comment has badly formed XML

- Directory.Packages.props
Update System.Text.Json to a non vulnerable version
more info : https://github.com/advisories/GHSA-8g4q-xg66-9fp4
> Update System.Text.Json to a non vulnerable version

- CHANGELOG.md
> Update CHANGELOG.md for 4.66.0

- CHANGELOG.md
Update CHANGELOG.md for MSAL 4.66.1
> Update CHANGELOG.md for MSAL 4.66.1

- CHANGELOG.md
> Update CHANGELOG.md for MSAL 4.66.2

- build/template-OneBranch-CI-libsandsamples.yaml
- build/template-restore-build-libsandsamples.yaml
> Bump default version to 4.60

- src/client/Microsoft.Identity.Client.Desktop/Microsoft.Identity.Client.Desktop.csproj
- src/client/Microsoft.Identity.Client.Desktop/PublicApi/PublicAPI.Shipped.txt
See comment in the code for the reason for this.
> Remove public API analyzer from desktop project

- build/template-OneBranch-Tests-libsandsamples.yaml
> Remove Net6 from OB tests

- build/template-OneBranch-CI-libsandsamples.yaml
- build/template-pack-and-sign-packages.yaml
- build/template-restore-build-libsandsamples.yaml
Fixes #5010
Remove Java 11 and choco 
**Testing**
Tests and Builds 
None
- N/A
> Remove Java 11

- src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- tests/Microsoft.Identity.Test.Unit/TelemetryTests/HttpTelemetryTests.cs
> Stop sending x-app-name and x-app-ver as they are ignored

- src/client/Microsoft.Identity.Client/Internal/Requests/Silent/CacheSilentStrategy.cs
- src/client/Microsoft.Identity.Client/TokenCache.ITokenCacheInternal.cs
- tests/Microsoft.Identity.Test.Unit/RequestsTests/FociTests.cs
> restrict FOCI to PCA and improve logging

- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsTests.cs
This pull request introduces changes to the Managed Identity tests to enhance code coverage, particularly for error handling scenarios involving HTTP status codes like BadRequest, BadGateway, and GatewayTimeout. The improvements include parameterized tests to efficiently handle multiple scenarios with varied HTTP status responses.
**Code Coverage Improvement:** From the [baseline coverage](https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1408768&view=logs&j=b518b04f-6c84-5938-67f2-8f2b5bcbaf6d&t=261fd3dc-9d48-5045-9354-3fd555de47ed) of 82.74% to 82.86%
- Modified `ImdsTests` to use `[DataTestMethod]` for handling various HTTP error scenarios in a single consolidated test method.
- Added multiple mock handlers to simulate retries for `GatewayTimeout` to reflect …
> Enhance IMDS Tests for Improved Code Coverage

- .github/workflows/benchmark-action.yml
Needed for .NET CDN change
see https://github.com/dotnet/core/issues/9671
and: https://github.com/AzureAD/microsoft-identity-web/pull/3175
> Update setup dotnet action

- CHANGELOG.md
Update CHANGELOG.md for MSAL 4.67.1
> Update CHANGELOG.md for MSAL 4.67.1

- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/ClientCredentialsMtlsPopTests.cs
Disable MTLS Pop tests to get the build going for a patch release
> Disable MTLS Pop tests

- CHANGELOG.md
This pull request includes a small change to the `CHANGELOG.md` file. The change documents a bug fix related to Managed Identity source detection prioritization, which resolves an issue where Azure ML was incorrectly prioritized over Azure App Service, leading to token acquisition failures. 
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR1-R5): Added version 4.67.2 with a bug fix for Managed Identity source detection prioritization issue.
> Update CHANGELOG.md for MSAL 4.67.2

- src/client/Microsoft.Identity.Client/MsalErrorMessage.cs
- src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/WsTrustTests/WsTrustTests.cs
Fixes #5080 
Fix code ql issue by logging the response instead of sending it in the exception.
**Testing**
> Fix code ql by logging the response and not sending it in exception

- docs/cache_extensibility.md
> Cache key extensibility spec proposal

- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/PoPTests.NetFwk.cs
- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/RuntimeBrokerTests.cs
> Fix some WAM tests

- CHANGELOG.md
> Update CHANGELOG.md for 4.68.0

- src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
> Updating shipped public api for 4.68.0

- .github/workflows/RunIssueSentinel.yml
Enable Issue-Sentinel to scan for similar issues
Onboarding reference document - https://github.com/Azure/issue-Sentinel?tab=readme-ov-file
> Enable Issue-Sentinel to scan for similar issues

- tests/Microsoft.Identity.Test.Unit/WebUITests/HttpListenerInterceptorTests.cs
Fixes #5152
This pull request includes changes to the `ValidateHttpListenerRedirectUriAsync` test method in the `tests/Microsoft.Identity.Test.Unit/WebUITests/HttpListenerInterceptorTests.cs` file. The changes aim to improve the reliability of the test by ensuring the HTTP listener has sufficient time to bind and handle requests.
Improvements to test reliability:
* [`tests/Microsoft.Identity.Test.Unit/WebUITests/HttpListenerInterceptorTests.cs`](diffhunk://#diff-133a913271e98be4c6fdba31ac3c30d5c5f2a3a83aae48ffbd20f16837ef7f80L93-R116): Simplified the initialization of `HttpListenerInterceptor` using target-typed new expression.
* [`tests/Microsoft.Identity.Test.Unit/WebUITests/HttpListenerInterceptorTests.cs`](diffhunk://#diff-133a913271e98be4c6fdba31ac …
> [Test Issue] Fixes Flaky Test: Ensure HTTP Listener is Ready Before Sending Request

- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
> Update Microsoft.Identity.Client.csproj to remove unwanted files

- CHANGELOG.md
Fixes #
Update CHANGELOG.md for 4.69.1
Update CHANGELOG.md for 4.69.1
**Testing**
> Update CHANGELOG.md for 4.69.1

- docs/imds_retry_based_on_errors.md
Fixes 
This pull request introduces a comprehensive error handling and retry strategy for MSAL when interacting with the IMDS endpoint for Managed Identity token acquisition. The document outlines specific actions and retry delays for various HTTP status codes and scenarios.
Key changes include:
* Added a detailed table specifying HTTP status codes, error reasons, recommended actions, and retry delay strategies.
* Introduced identity propagation handling for "Identity Not Found" errors with a recommended exponential backoff retry sequence.
* Defined an updated retry strategy using exponential backoff for 5xx errors, timeouts, and certain transient 4xx errors.
* Included a mermaid diagram to visually represent the retry logic flow for various error …
> IMDS Retry specification

- CHANGELOG.md
Update CHANGELOG.md for MSAL 4.70.0
> Update CHANGELOG.md for MSAL 4.70.0

- build/platform_and_feature_flags.props
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/SimpleHttpClientFactory.cs
Fixes #5172
This pull request includes changes to improve platform compatibility and code simplification. The most important changes include updating the target framework conditions in the `platform_and_feature_flags.props` file and simplifying the creation of `HttpClientHandler` in the `SimpleHttpClientFactory` class.
* [`build/platform_and_feature_flags.props`](diffhunk://#diff-ab8426b220a9645209f54a0e3e841745bcac9689b4506e8f1eb8ce959b6bd058L8-R8): Updated the condition to include `$(TargetFrameworkNetStandard)` for defining `SUPPORTS_MTLS` constants.
* [`src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/SimpleHttpClientFactory.cs`](diffhunk://#diff-c3cb436aeedc6aedc1e600b05baa129916cb26e430db7f54e4fca6c76fc6cc97L50-R50): Simplified the …
> Adds NetStandard support for MTLS

- tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/ConfidentialClientAuthorizationTests.cs
Fixes #
Changing tests to use LAbAuth certificate.
Tests: GetTokenByAuthCode_WithPKCE_Async, GetTokenByAuthCode_HybridSPA_Async, SeleniumGetAuthCode_RedeemForAt_CommonAuthority_Async
**Testing**
> Updating cert to fix tests

- src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
Adds a comment to suppress a codeQL false positive that's been reviewed by the team.
**Testing**
N/A
N/A
> Suppress codeQL false positive

- CHANGELOG.md
> Add changelog for 4.71.0

- src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Shipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
> Move unshipped to shipped public APIs for 4.71.0 release

- src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ServiceFabricTests.cs
Fixes #5243 
Pass the Validate function to the http manager. 
**Testing**
> Pass the validate function to the http manager

- src/client/Microsoft.Identity.Client/Internal/Constants.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsManagedIdentitySource.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHttpManagerExtensions.cs
Fixes #4911 
Update code and mocks
**Testing**
> Change the resource id param for IMDS

- src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
The previous  CodeQL suppression didn't work and adding the suppression comment just before the parameter.
> Add the CodeQL suppression in the right place for wstrustrequest parameter.

- CHANGELOG.md
> Update CHANGELOG.md for 4.72.0

- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/RuntimeBrokerTests.cs
- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/WwwAuthenticateParametersIntegrationTests.NetFwk.cs
Tracking here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/5305
**Testing**
> Disabling tests since testingsts.azurewebsites.net is down

- global.json
- src/client/Microsoft.Identity.Client/Http/Retry/DefaultRetryPolicy.cs
- src/client/Microsoft.Identity.Client/Http/Retry/IRetryPolicyFactory.cs
- src/client/Microsoft.Identity.Client/Http/Retry/RetryPolicyFactory.cs
- src/client/Microsoft.Identity.Client/Instance/Region/RegionManager.cs
- src/client/Microsoft.Identity.Client/Instance/Validation/AdfsAuthorityValidator.cs
- src/client/Microsoft.Identity.Client/Internal/Constants.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/AzureArcManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ImdsManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityRequest.cs
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- src/client/Microsoft.Identity.Client/WsTrust/WsTrustWebRequestManager.cs
- tests/Microsoft.Identity.Test.Unit/CoreTests/HttpTests/HttpManagerTests.cs
- tests/Microsoft.Identity.Test.Unit/Helpers/TestRetryPolicies.cs
- tests/Microsoft.Identity.Test.Unit/Helpers/TestRetryPolicyFactory.cs
> Moved RequestType enum from Constants to IRetryPolicyFactory

- build/template-build-and-run-all-tests.yaml
- build/template-build-on-mac.yaml
Fixes #
A new pipeline task building MacConsoleAppWithBroker on mac:
https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=1488056&view=logs&j=ce470401-531d-5542-b9c3-5842005cc0c9&t=221f610b-1df0-566a-17b3-402ba62c112b
**Testing**
> Add a pipeline building mac console app with broker

- tests/Microsoft.Identity.Test.Common/TestConstants.cs
- tests/Microsoft.Identity.Test.Integration.netcore/SeleniumTests/FociTests.cs
Remove some fake secrets from the build
> Use the actual client IDs for FOCI

- tests/devapps/Managed Identity apps/MSIHelperService/readme.md
Fixes #
This pull request makes extensive updates to the `readme.md` file of the `MSIHelperService` project, primarily focusing on improving clarity, fixing errors, and removing outdated or redundant sections. The changes simplify the documentation, making it more concise and easier to follow for developers.
* Corrected a typographical error in the term "Managded Identity" to "Managed Identity" for better readability. (`[tests/devapps/Managed Identity apps/MSIHelperService/readme.mdL20-R20](diffhunk://#diff-82ef05a10883839e91e6d4eacaee81b97dfd3cd8f3b088cb26b5342971c8cd51L20-R20)`)
* Removed outdated and redundant sections about deploying Function Apps, Virtual Machines, and Azure ARC setups, including detailed explanations of OMS (Operations Management …
> Update readme for MSI Helper Service

- tests/Microsoft.Identity.Test.Integration.netcore/HeadlessTests/FmiIntegrationTests.cs
- tests/devapps/Managed Identity apps/MSIHelperService/readme.md
Update FMI tests: 
1. Delete non-regional versions, since we expect region to always be used
2. Update test for flow 4, which mentions getting a FIC
3. Disable test for flow, because it doesn't return a valid token
4. Update some names
5. Enable all tests to run on the CI
> Update FMI tests

- Directory.Packages.props
- tests/devapps/MacConsoleAppWithBroker/MacConsoleAppWithBroker.csproj
- tests/devapps/MacMauiAppWithBroker/MacMauiAppWithBroker.csproj
Fixes #5346
The fix is available in NativeInterop 0.19.2, updating the version in MSAL.NET
**Testing**
> Update native interop to 0.19.2

- src/client/Microsoft.Identity.Client/Http/Retry/HttpRetryCondition.cs
- src/client/Microsoft.Identity.Client/Http/Retry/ImdsRetryPolicy.cs
- src/client/Microsoft.Identity.Client/Http/Retry/RetryPolicyFactory.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/ManagedIdentityAuthRequest.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/CredentialManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/CredentialProbeManager.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityClient.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityRequest.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/PublicApi/net462/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net472/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-android/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0-ios/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/net8.0/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/PublicApi/netstandard2.0/PublicAPI.Unshipped.txt
- src/client/Microsoft.Identity.Client/RequestType.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Common/TestCommon.cs
- tests/Microsoft.Identity.Test.Unit/Helpers/TestRetryPolicyFactory.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/AzureArcTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/CloudShellTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/CredentialTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/DefaultRetryPolicyTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/MachineLearningTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ManagedIdentityTests.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ServiceFabricTests.cs
Fixes [3187132](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/3187132)
Add probe logic to check if Credential source exists
**Testing**
unit tests 
none
> MSI With MAA + KG - Credential Probe

- src/client/Microsoft.Identity.Client/ApiConfig/Executors/ManagedIdentityExecutor.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/AccessTokenClient.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/AttestationClient.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/CredentialIssuerClient.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/CredentialStore.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/CsrHelper.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/ImdsMetadataClient.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/KeyGuardHelper.cs
- src/client/Microsoft.Identity.Client/Internal/Credential/KeyMaterial.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/CredentialManagedIdentityAuthRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/LegacyManagedIdentityAuthRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/ManagedIdentityAuthRequest.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/CredentialProbeManager.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/ManagedIdentityCredentialResponse.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/PlatformMetadataResponse.cs
- src/client/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj
- src/client/Microsoft.Identity.Client/OAuth2/OAuth2Client.cs
- src/client/Microsoft.Identity.Client/Platforms/net/MsalJsonSerializerContext.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/CredentialTests.cs
> [DRAFT] MSI v2 - Prototype

- Directory.Packages.props
- prototype/MsiWithSlc/MsiSlcPublicApis/MsiSlcPublicApis.sln
- prototype/MsiWithSlc/MsiSlcPublicApis/MsiSlcPublicApis/MsiSlcPublicApis.csproj
- prototype/MsiWithSlc/MsiSlcPublicApis/MsiSlcPublicApis/Program.cs
- prototype/MsiWithSlc/readme.md
Fixes 
msi slc demo app 
**Testing**
using the app
none
> msi with slc prototype using a demo app

- .codespellignore
- .github/workflows/spellcheck.yml
- CHANGELOG.md
- src/client/Microsoft.Identity.Client.Extensions.Msal/MsalCacheHelper.cs
- src/client/Microsoft.Identity.Client/AppConfig/AssertionRequestOptions.cs
- src/client/Microsoft.Identity.Client/Cache/cache.readme.md
- src/client/Microsoft.Identity.Client/Extensibility/AbstractConfidentialClientAcquireTokenParameterBuilderExtension.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/ClientCredentialRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/IntegratedWindowsAuthRequest.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/Interactive/InteractiveRequest.cs
- src/client/Microsoft.Identity.Client/MsalError.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/TokenCacheHelper.cs
- tests/Microsoft.Identity.Test.Unit/CacheTests/TokenCacheTests.cs
Fixes - Add a spell checker
This pull request introduces a new spell-checking workflow to the repository. The changes include adding a GitHub Actions workflow configuration file and an ignore file for the `codespell` tool.
docs - https://github.com/codespell-project/actions-codespell 
* [`.github/workflows/spellcheck.yml`](diffhunk://#diff-203285d1aa85b30b7cd672df926f6239c419f1308a5b1cbe3c5df4a0497f1dafR1-R13): Added a new GitHub Actions workflow named "Spell check" to automatically check for spelling errors in pull requests. The workflow uses the `codespell` tool and scans both file contents and filenames, referencing an ignore file for exceptions.
* [`.codespellignore`](diffhunk://#diff-259bb2c0ef38bb482f6cad3b732cee88f05752aaa14e0e60658da22e365d28feR …
> adds a new spell-checking workflow to the repository

- README.md
This pull request updates the supported versions listed in the `README.md` file for the MSAL.NET library. The change reflects an update to the minimum supported version from `4.61.2` to `4.71.2`.
> Update README.md for supported versions

- docs/msi_v2/msi_with_credential_design.md
Fixes update to the msi design doc
updates based on new design 
**Testing**
n/a
none
> Update MSI with credentials design

- docs/msiv1_token_revocation.md
Fixes docs
This pull request adds a detailed explanation and diagram to the `msiv1_token_revocation.md` documentation, describing a new hash-based, cluster-wide cache-bypass optimization for token revocation. The update clarifies how this approach efficiently handles token refreshes in large distributed systems, minimizing redundant requests to Azure AD.
**Documentation improvements:**
* Added a new section with a mermaid sequence diagram illustrating the hash-based cache-bypass flow across nodes in a cluster, showing how only one Azure AD call is made per unique revoked token.
* Provided a step-by-step breakdown of the process for both the first node encountering a stale token and subsequent nodes, highlighting the efficiency of the hash-based …
> Update msiv1_token_revocation.md and explain hash logic in detail

- global.json
- src/client/Microsoft.Identity.Client/ManagedIdentity/V2/CertificateRequestBody.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/V2/ImdsV2ManagedIdentitySource.cs
- src/client/Microsoft.Identity.Client/Platforms/net/MsalJsonSerializerContext.cs
- src/client/Microsoft.Identity.Client/PlatformsCommon/Shared/CommonCryptographyManager.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs
These are necessary changes that were discovered from manual testing.
> ImdsV2: Miscellanious Updates Discovered by Manual Testing

- src/client/Microsoft.Identity.Client/ApiConfig/Parameters/AcquireTokenForManagedIdentityParameters.cs
- src/client/Microsoft.Identity.Client/Internal/Requests/ManagedIdentityAuthRequest.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/AbstractManagedIdentity.cs
- src/client/Microsoft.Identity.Client/ManagedIdentity/V2/ImdsV2ManagedIdentitySource.cs
- tests/Microsoft.Identity.Test.Common/Core/Mocks/MockHelpers.cs
- tests/Microsoft.Identity.Test.Unit/ManagedIdentityTests/ImdsV2Tests.cs
- tests/Microsoft.Identity.Test.Unit/Microsoft.Identity.Test.Unit.csproj
Integrated .WithMtlsProofOfPossession (#5483 ) into ImdsV2ManagedIdentity.cs
Added unit tests
> ImdsV2: Integrated .WithMtlsProofOfPossession
